# -*- coding: utf-8 -*-
# 最后8种补齐 (batch10) - 精确1000
EIGHT = [
 {"name":"大食蚁兽","englishName":"Giant Anteater","scientificName":"Myrmecophaga tridactyla","category":"哺乳类","habitat":"中南美洲的草原和森林","diet":"蚂蚁和白蚁","size":"体长1.8-2.2m,体重25-40kg","weight":"25-40kg","length":"2m","status":"易危(VU)","emoji":"🐜","description":"长长的管状嘴和大扫帚尾,黑白斜纹披肩,前爪可撕开蚁穴,每天吃3万只蚂蚁。","imagePrompt":"A photorealistic wildlife photograph of a giant anteater (Myrmecophaga tridactyla) with a long tubular snout and huge bushy tail foraging on the South American savanna, black and white shoulder stripes, morning light, National Geographic style"},
 {"name":"九带犰狳","englishName":"Nine-banded Armadillo","scientificName":"Dasypus novemcinctus","category":"哺乳类","habitat":"美洲的热带和亚热带","diet":"昆虫、蠕虫和小动物","size":"体长0.4-0.6m,体重2.5-7kg","weight":"2.5-7kg","length":"0.5m","status":"无危(LC)","emoji":"🦔","description":"身披骨质鳞甲,遇惊蜷缩成球,擅长挖洞和游泳,是穿铠甲的挖掘机。","imagePrompt":"A photorealistic wildlife photograph of a nine-banded armadillo (Dasypus novemcinctus) with armored shell plates digging in the forest floor, pointy snout, dirt flying, warm woodland light, National Geographic style"},
 {"name":"中华穿山甲","englishName":"Chinese Pangolin","scientificName":"Manis pentadactyla","category":"哺乳类","habitat":"中国南方和东南亚的森林","diet":"蚂蚁和白蚁","size":"体长40-58cm,体重2.5-7kg","weight":"2.5-7kg","length":"0.5m","status":"极危(CR)","emoji":"🦔","description":"全身覆盖角质鳞片,遇险蜷成球,长舌伸出40厘米舔食蚂蚁,是走私最多的动物。","imagePrompt":"A photorealistic wildlife photograph of a Chinese pangolin (Manis pentadactyla) covered in overlapping scales walking on the forest floor, long snout, curled tail, warm dappled light, National Geographic style"},
 {"name":"雪兔","englishName":"Mountain Hare","scientificName":"Lepus timidus","category":"哺乳类","habitat":"欧亚大陆北部的高山冻原","diet":"草、树皮和嫩芽","size":"体长45-65cm,体重2-5kg","weight":"2-5kg","length":"0.55m","status":"无危(LC)","emoji":"🐇","description":"冬天变白夏天变褐的变色兔,大眼睛长耳朵,雪地里的跳跃精灵。","imagePrompt":"A photorealistic wildlife photograph of a mountain hare (Lepus timidus) in white winter coat hopping on snowy tundra, long ears, black ear tips, snowflakes, cold light, National Geographic style"},
 {"name":"西非海牛","englishName":"West African Manatee","scientificName":"Trichechus senegalensis","category":"哺乳类","habitat":"西非的河流和海岸","diet":"水生植物","size":"体长2.5-4m,体重200-500kg","weight":"200-500kg","length":"3.2m","status":"易危(VU)","emoji":"🦭","description":"温顺的河海巨兽,圆胖身材和桨状前肢,是美人鱼传说的原型之一。","imagePrompt":"A photorealistic underwater photograph of a West African manatee (Trichechus senegalensis) gliding through murky tropical river water, plump grey body, paddle flippers, gentle face, aquatic plants, soft light, National Geographic style"},
 {"name":"环斑海豹","englishName":"Ringed Seal","scientificName":"Pusa hispida","category":"哺乳类","habitat":"北极海域","diet":"鱼和甲壳类","size":"体长1.2-1.6m,体重50-110kg","weight":"50-110kg","length":"1.4m","status":"无危(LC)","emoji":"🦭","description":"身上有环形斑纹的小海豹,在冰上凿呼吸孔,是北极最小的海豹。","imagePrompt":"A photorealistic wildlife photograph of a ringed seal (Pusa hispida) resting on arctic pack ice, grey body with ring-shaped spots, large dark eyes, snow and ice, cold blue light, National Geographic style"},
 {"name":"南美海狮","englishName":"South American Sea Lion","scientificName":"Otaria flavescens","category":"哺乳类","habitat":"南美洲的太平洋海岸","diet":"鱼、鱿鱼和甲壳类","size":"体长1.8-2.7m,体重150-350kg","weight":"150-350kg","length":"2.3m","status":"无危(LC)","emoji":"🦭","description":"鬃毛浓密的海狮,成群躺在沙滩上晒太阳,叫声洪亮,是海岸的主人。","imagePrompt":"A photorealistic wildlife photograph of South American sea lions (Otaria flavescens) hauled out on a rocky Patagonian beach, brown bodies with manes, ocean waves, golden light, National Geographic style"},
 {"name":"座头鲸","englishName":"Humpback Whale","scientificName":"Megaptera novaeangliae","category":"哺乳类","habitat":"全球海洋,迁徙距离最长","diet":"磷虾和小鱼","size":"体长12-16m,体重25-30吨","weight":"25-30吨","length":"14m","status":"无危(LC)","emoji":"🐋","description":"以跃出水面和动听的歌声闻名,长胸鳍达体长三分之一,是海洋的歌唱家。","imagePrompt":"A photorealistic photograph of a humpback whale (Megaptera novaeangliae) breaching fully out of the ocean, long white pectoral fins, splash and spray, golden sunset ocean, National Geographic style"},
]
