# -*- coding: utf-8 -*-
# 补充批次:65种珍稀/特色动物 (batch6) - 凑满1000种
EXTRA = [
 # ===== 哺乳类补充 15种 =====
 {"name":"水豚","englishName":"Capybara","scientificName":"Hydrochoerus hydrochaeris","category":"哺乳类","habitat":"南美洲的河流、湖泊和湿地","diet":"水生植物和草","size":"体长1-1.3m,体重35-66kg","weight":"35-66kg","length":"1.15m","status":"无危(LC)","emoji":"🦫","description":"世界上最大的啮齿动物,圆滚滚的身材泡在水里,性格温顺,是动物界的社交达人。","imagePrompt":"A photorealistic wildlife photograph of a capybara (Hydrochoerus hydrochaeris) relaxing in a South American river with its round body half-submerged, reddish-brown fur, peaceful expression, water plants around, golden light, National Geographic style"},
 {"name":"羊驼","englishName":"Alpaca","scientificName":"Vicugna pacos","category":"哺乳类","habitat":"南美洲安第斯山脉的高原","diet":"草和干草","size":"肩高0.8-1m,体重45-84kg","weight":"45-84kg","length":"1.3m","status":"无危(LC)","emoji":"🦙","description":"毛茸茸的安第斯高原精灵,长长的脖子和温柔的眼神,羊毛柔软珍贵,萌态十足。","imagePrompt":"A photorealistic wildlife photograph of an alpaca (Vicugna pacos) with fluffy wool standing on an Andean highland meadow, long neck, soft eyes, snow-capped mountains behind, golden light, National Geographic style"},
 {"name":"蜜獾","englishName":"Honey Badger","scientificName":"Mellivora capensis","category":"哺乳类","habitat":"非洲和南亚的草原、沙漠","diet":"蜂蜜、蛇、蝎子和小型动物","size":"体长55-77cm,体重7-16kg","weight":"7-16kg","length":"0.65m","status":"无危(LC)","emoji":"🦡","description":"吉尼斯认证的最无畏动物,黑背白腹,敢和狮子对峙,连毒蛇都不放在眼里。","imagePrompt":"A photorealistic wildlife photograph of a honey badger (Mellivora capensis) with its distinctive black back and white belly standing on African savanna, bold stance, alert eyes, dry grassland, dramatic light, National Geographic style"},
 {"name":"兔狲","englishName":"Pallas's Cat","scientificName":"Otocolobus manul","category":"哺乳类","habitat":"中亚和青藏高原的草原荒漠","diet":"鼠兔、旱獭等小型啮齿动物","size":"体长46-65cm,体重2.5-4.5kg","weight":"2.5-4.5kg","length":"0.55m","status":"无危(LC)","emoji":"🐱","description":"表情最凶狠的猫科动物,其实胆小温顺,毛发浓密厚实,圆脸小短腿,行走的表情包。","imagePrompt":"A photorealistic wildlife photograph of a Pallas's cat (Otocolobus manul) with dense fluffy grey fur and a flat grumpy face crouching in a rocky steppe, piercing yellow eyes, snow dust, dramatic light, National Geographic style"},
 {"name":"狞猫","englishName":"Caracal","scientificName":"Caracal caracal","category":"哺乳类","habitat":"非洲和中亚的草原、半沙漠","diet":"鸟类、啮齿动物和小型羚羊","size":"体长60-90cm,体重7-19kg","weight":"7-19kg","length":"0.75m","status":"无危(LC)","emoji":"🐱","description":"耳朵上长着黑色长毛簇,红棕色皮毛优雅高贵,能跳起3米高捕捉飞鸟。","imagePrompt":"A photorealistic wildlife photograph of a caracal (Caracal caracal) with distinctive long black ear tufts standing on African savanna grass, reddish-brown coat, elegant posture, golden hour light, National Geographic style"},
 {"name":"薮猫","englishName":"Serval","scientificName":"Leptailurus serval","category":"哺乳类","habitat":"非洲的草原和湿地","diet":"鼠类、鸟类和蛙类","size":"体长70-100cm,体重7-18kg","weight":"7-18kg","length":"0.85m","status":"无危(LC)","emoji":"🐱","description":"大耳朵大长腿的猫科动物,身上的黑色斑点花纹,跳跃捕食时如弹簧般矫健。","imagePrompt":"A photorealistic wildlife photograph of a serval (Leptailurus serval) with huge ears and long legs walking through tall savanna grass, golden coat with black spots, alert posture, warm African light, National Geographic style"},
 {"name":"猞猁","englishName":"Eurasian Lynx","scientificName":"Lynx lynx","category":"哺乳类","habitat":"欧亚大陆的针叶林和山地","diet":"野兔、鹿和鸟类","size":"体长80-130cm,体重15-30kg","weight":"15-30kg","length":"1m","status":"无危(LC)","emoji":"🐱","description":"耳朵尖的黑毛簇和雪白的大脚掌,灰色皮毛带斑点,是森林里神秘的大猫。","imagePrompt":"A photorealistic wildlife photograph of a Eurasian lynx (Lynx lynx) with tufted ears and a short tail walking through snowy boreal forest, thick grey spotted fur, intense green eyes, winter atmosphere, National Geographic style"},
 {"name":"鬃狼","englishName":"Maned Wolf","scientificName":"Chrysocyon brachyurus","category":"哺乳类","habitat":"南美洲的草原和稀树草原","diet":"小型动物、果实和昆虫","size":"肩高1m,体重20-30kg","weight":"20-30kg","length":"1.3m","status":"近危(NT)","emoji":"🐺","description":"大长腿配红棕色皮毛,像踩着高跷的狐狸,是南美草原上最优雅的犬科动物。","imagePrompt":"A photorealistic wildlife photograph of a maned wolf (Chrysocyon brachyurus) with extraordinarily long legs and reddish fur standing in the South American cerrado grassland, black mane, tall grass, golden light, National Geographic style"},
 {"name":"独角鲸","englishName":"Narwhal","scientificName":"Monodon monoceros","category":"哺乳类","habitat":"北极圈的海域","diet":"鱼、鱿鱼和虾","size":"体长4-5.5m,体重800-1600kg","weight":"800-1600kg","length":"4.5m","status":"无危(LC)","emoji":"🐋","description":"海洋独角兽,雄性长长的螺旋长牙可达3米,其实是一颗特化的牙齿。","imagePrompt":"A photorealistic underwater photograph of a narwhal (Monodon monoceros) with its long spiral tusk swimming in arctic waters, grey mottled body, ice floes above, cold blue light, National Geographic style"},
 {"name":"白鲸","englishName":"Beluga Whale","scientificName":"Delphinapterus leucas","category":"哺乳类","habitat":"北极和亚北极的海域","diet":"鱼、鱿鱼和甲壳类","size":"体长4-5.5m,体重700-1600kg","weight":"700-1600kg","length":"4.7m","status":"无危(LC)","emoji":"🐋","description":"海洋中的金丝雀,全身雪白,会发出各种悦耳叫声,圆圆的额头会变色。","imagePrompt":"A photorealistic underwater photograph of a beluga whale (Delphinapterus leucas) with pure white body surfacing in arctic water, round bulbous forehead, gentle smile, ice in background, cold light, National Geographic style"},
 {"name":"抹香鲸","englishName":"Sperm Whale","scientificName":"Physeter macrocephalus","category":"哺乳类","habitat":"全球海洋,深潜之王","diet":"大王乌贼和深海鱼","size":"体长11-18m,体重14-57吨","weight":"14-57吨","length":"15m","status":"易危(VU)","emoji":"🐋","description":"头部占身体三分之一,是潜水最深的哺乳动物,可下潜2200米追捕大王乌贼。","imagePrompt":"A photorealistic underwater photograph of a sperm whale (Physeter macrocephalus) with its massive square head floating at the ocean surface, wrinkled grey skin, spout of water, deep blue sea, dramatic light, National Geographic style"},
 {"name":"南美貘","englishName":"Lowland Tapir","scientificName":"Tapirus terrestris","category":"哺乳类","habitat":"南美洲的热带雨林","diet":"树叶、果实和水生植物","size":"体长1.8-2.5m,体重150-250kg","weight":"150-250kg","length":"2.2m","status":"易危(VU)","emoji":"🦏","description":"深褐色的南美貘,短鼻子像小象,是亚马逊雨林里的活化石,夜行性。","imagePrompt":"A photorealistic wildlife photograph of a lowland tapir (Tapirus terrestris) with dark brown body and short trunk-like snout walking along an Amazon rainforest riverbank, misty jungle, soft light, National Geographic style"},
 {"name":"懒熊","englishName":"Sloth Bear","scientificName":"Melursus ursinus","category":"哺乳类","habitat":"印度和斯里兰卡的森林","diet":"白蚁、蚂蚁、蜂蜜和果实","size":"体长1.5-1.9m,体重55-145kg","weight":"55-145kg","length":"1.7m","status":"易危(VU)","emoji":"🐻","description":"长着白色V形胸斑和长鼻子,专门吸食白蚁,是印度次大陆独特的熊。","imagePrompt":"A photorealistic wildlife photograph of a sloth bear (Melursus ursinus) with shaggy black fur and a white V-shaped chest mark foraging in an Indian forest, long snout, termite mound, soft light, National Geographic style"},
 {"name":"眼镜熊","englishName":"Spectacled Bear","scientificName":"Tremarctos ornatus","category":"哺乳类","habitat":"南美洲安第斯山脉的云雾林","diet":"果实、植物和蜂蜜","size":"体长1.3-2m,体重64-155kg","weight":"64-155kg","length":"1.7m","status":"易危(VU)","emoji":"🐻","description":"眼睛周围有米色斑纹像戴眼镜,是南美洲唯一的熊,爬树高手。","imagePrompt":"A photorealistic wildlife photograph of a spectacled bear (Tremarctos ornatus) with cream-colored markings around its eyes climbing a tree in a misty Andean cloud forest, black fur, lush vegetation, soft light, National Geographic style"},
 {"name":"跳羚","englishName":"Springbok","scientificName":"Antidorcas marsupialis","category":"哺乳类","habitat":"非洲南部的草原和荒漠","diet":"草和灌木","size":"体长1.2-1.5m,体重25-40kg","weight":"25-40kg","length":"1.35m","status":"无危(LC)","emoji":"🦌","description":"南非的国兽,受惊时会笔直跳起3米高,背部展开白色绒毛像扇子一样炫耀。","imagePrompt":"A photorealistic wildlife photograph of a springbok (Antidorcas marsupialis) leaping high in the air with its back arched and white crest raised, sandy-brown coat with dark stripe, Kalahari grassland, golden light, National Geographic style"},

 # ===== 鸟类补充 15种 =====
 {"name":"黑脸琵鹭","englishName":"Black-faced Spoonbill","scientificName":"Platalea minor","category":"鸟类","habitat":"东亚沿海的湿地和滩涂","diet":"小鱼、虾和蟹","size":"体长74-82cm,翼展1.2m","weight":"1.5-2.1kg","length":"0.78m","status":"濒危(EN)","emoji":"🦩","description":"全球仅存约6000只的珍稀水鸟,黑色脸部和匙状长嘴是标志,是湿地保护旗舰物种。","imagePrompt":"A photorealistic wildlife photograph of a black-faced spoonbill (Platalea minor) with a distinctive black face and spoon-shaped beak wading in a coastal wetland, white plumage, water reflections, golden light, National Geographic style"},
 {"name":"白琵鹭","englishName":"Eurasian Spoonbill","scientificName":"Platalea leucorodia","category":"鸟类","habitat":"欧亚大陆的湿地和湖泊","diet":"小鱼、虾和昆虫","size":"体长80-93cm,翼展1.2-1.3m","weight":"1.5-2.1kg","length":"0.85m","status":"无危(LC)","emoji":"🦩","description":"雪白羽毛配铲子般的长嘴,在水中左右扫动觅食,优雅的白衣舞者。","imagePrompt":"A photorealistic wildlife photograph of a Eurasian spoonbill (Platalea leucorodia) with its spoon-shaped black-tipped beak sweeping through shallow water, white plumage, marsh background, soft morning light, National Geographic style"},
 {"name":"北极海鹦","englishName":"Atlantic Puffin","scientificName":"Fratercula arctica","category":"鸟类","habitat":"北大西洋的岛屿海岸","diet":"小鱼(尤其沙鳗)","size":"体长28-34cm,体重0.4-0.5kg","weight":"0.4-0.5kg","length":"0.3m","status":"易危(VU)","emoji":"🐧","description":"彩色大嘴和企鹅般的黑白羽毛,被称为海上小丑,叼着满嘴小鱼的样子可爱至极。","imagePrompt":"A photorealistic wildlife photograph of Atlantic puffins (Fratercula arctica) with colorful striped beaks standing on a rocky North Atlantic cliff, black and white plumage, fish in beaks, ocean waves, bright light, National Geographic style"},
 {"name":"蛇鹫","englishName":"Secretary Bird","scientificName":"Sagittarius serpentarius","category":"鸟类","habitat":"非洲的草原和稀树草原","diet":"蛇、蜥蜴、鼠和昆虫","size":"身高1.2-1.5m,翼展2m","weight":"2.3-4.3kg","length":"1.35m","status":"濒危(EN)","emoji":"🦅","description":"大长腿配头顶笔状羽毛,专吃毒蛇,一脚能把蛇踩晕,是非洲草原的蛇类克星。","imagePrompt":"A photorealistic wildlife photograph of a secretary bird (Sagittarius serpentarius) with long legs and quill-like head feathers striding through African savanna grass, grey plumage, hunting pose, golden light, National Geographic style"},
 {"name":"食火鸡","englishName":"Southern Cassowary","scientificName":"Casuarius casuarius","category":"鸟类","habitat":"澳洲北部和新几内亚的热带雨林","diet":"果实、种子和小动物","size":"身高1.5-1.8m,体重30-60kg","weight":"30-60kg","length":"1.6m","status":"无危(LC)","emoji":"🦩","description":"头戴骨质头盔,脖子蓝红相间,是世界上第三大的鸟,被称为最危险的鸟。","imagePrompt":"A photorealistic wildlife photograph of a southern cassowary (Casuarius casuarius) with a bony casque and vivid blue neck walking through a tropical rainforest, glossy black feathers, lush green, soft light, National Geographic style"},
 {"name":"琴鸟","englishName":"Superb Lyrebird","scientificName":"Menura novaehollandiae","category":"鸟类","habitat":"澳大利亚东南部的雨林","diet":"昆虫和小型无脊椎动物","size":"体长80-100cm(含尾),体重0.9-1.1kg","weight":"0.9-1.1kg","length":"0.9m","status":"无危(LC)","emoji":"🐦","description":"尾羽展开如古希腊竖琴,能模仿任何声音,包括电锯和相机快门,是鸟中的口技大师。","imagePrompt":"A photorealistic wildlife photograph of a superb lyrebird (Menura novaehollandiae) displaying its magnificent lyre-shaped tail feathers in an Australian rainforest, brown bird, intricate tail plumage, soft forest light, National Geographic style"},
 {"name":"笑翠鸟","englishName":"Laughing Kookaburra","scientificName":"Dacelo novaeguineae","category":"鸟类","habitat":"澳大利亚和新几内亚的林地","diet":"蛇、蜥蜴、鼠和昆虫","size":"体长39-45cm,体重0.3-0.5kg","weight":"0.3-0.5kg","length":"0.42m","status":"无危(LC)","emoji":"🐦","description":"叫声像人类大笑的翠鸟,是澳洲丛林的闹钟,灰白色羽毛配大嘴。","imagePrompt":"A photorealistic wildlife photograph of a laughing kookaburra (Dacelo novaeguineae) perched on a eucalyptus branch with its head tilted back in a laughing call, brown and white plumage, large beak, Australian bush, golden light, National Geographic style"},
 {"name":"大极乐鸟","englishName":"Greater Bird-of-paradise","scientificName":"Paradisaea apoda","category":"鸟类","habitat":"新几内亚的热带雨林","diet":"果实和昆虫","size":"体长33-43cm(含饰羽),体重0.1-0.25kg","weight":"0.1-0.25kg","length":"0.4m","status":"无危(LC)","emoji":"🐦","description":"世界上最华丽的鸟,金黄和翠绿色的饰羽如丝绸瀑布,求偶舞姿惊艳绝伦。","imagePrompt":"A photorealistic wildlife photograph of a greater bird-of-paradise (Paradisaea apoda) male with cascading golden and emerald plumes performing a courtship display in a rainforest, iridescent feathers, dramatic pose, soft light, National Geographic style"},
 {"name":"彩虹蜂虎","englishName":"Rainbow Bee-eater","scientificName":"Merops ornatus","category":"鸟类","habitat":"澳大利亚和东南亚的开阔林地","diet":"蜜蜂、黄蜂等飞行昆虫","size":"体长23-25cm,体重0.03-0.05kg","weight":"30-50g","length":"0.24m","status":"无危(LC)","emoji":"🐦","description":"绿蓝金橙彩虹般的羽毛,优雅地捕食蜜蜂,是澳大利亚色彩最鲜艳的小鸟。","imagePrompt":"A photorealistic wildlife photograph of a rainbow bee-eater (Merops ornatus) with iridescent green, blue and gold plumage perched on a branch holding a bee, eucalyptus woodland, soft light, National Geographic style"},
 {"name":"白眉鸫","englishName":"White's Thrush","scientificName":"Zoothera aurea","category":"鸟类","habitat":"东亚的森林","diet":"昆虫、蚯蚓和果实","size":"体长26-30cm,体重0.08-0.12kg","weight":"80-120g","length":"0.28m","status":"无危(LC)","emoji":"🐦","description":"鳞片状花纹的美丽鸫鸟,白色眉纹清晰,鸣声悠扬,是森林里的低调歌手。","imagePrompt":"A photorealistic wildlife photograph of a White's thrush (Zoothera aurea) with scaly patterned plumage perched on a mossy forest floor, white eye stripe, autumn leaves, soft light, National Geographic style"},
 {"name":"红嘴鸥","englishName":"Black-headed Gull","scientificName":"Chroicocephalus ridibundus","category":"鸟类","habitat":"欧亚大陆的湖泊、河流和海岸","diet":"鱼、昆虫和人类食物","size":"体长35-39cm,翼展0.86-0.99m","weight":"0.2-0.35kg","length":"0.37m","status":"无危(LC)","emoji":"🕊️","description":"头戴咖啡色小帽(繁殖期),红嘴红脚,昆明翠湖每年冬天的老朋友。","imagePrompt":"A photorealistic wildlife photograph of black-headed gulls (Chroicocephalus ridibundus) with chocolate-brown hoods flying over a winter lake, white bodies, red beaks, urban lake background, morning light, National Geographic style"},
 {"name":"蓝胸佛法僧","englishName":"Blue Roller","scientificName":"Eurystomus glaucurus","category":"鸟类","habitat":"非洲和东南亚的林地","diet":"昆虫,尤其甲虫","size":"体长27-30cm,体重0.1-0.2kg","weight":"100-200g","length":"0.28m","status":"无危(LC)","emoji":"🐦","description":"宝蓝色的羽毛在阳光下泛着金属光泽,捕食时在空中翻滚,如同蓝色火焰。","imagePrompt":"A photorealistic wildlife photograph of a broad-billed roller (Eurystomus glaucurus) with brilliant blue plumage perched on a dead branch, metallic sheen, African savanna background, golden light, National Geographic style"},
 {"name":"红腹角雉","englishName":"Temminck's Tragopan","scientificName":"Tragopan temminckii","category":"鸟类","habitat":"中国西南和东南亚的高山森林","diet":"果实、嫩芽和昆虫","size":"体长50-65cm,体重1-1.8kg","weight":"1-1.8kg","length":"0.58m","status":"无危(LC)","emoji":"🐦","description":"求偶时喉下肉裙展开如彩绘扇子,红橙蓝三色交织,是中国特有雉类的珍品。","imagePrompt":"A photorealistic wildlife photograph of a Temminck's tragopan (Tragopan temminckii) male displaying its colorful blue and orange lappet in a mountain forest, crimson plumage with white spots, soft light, National Geographic style"},
 {"name":"红嘴相思鸟","englishName":"Red-billed Leiothrix","scientificName":"Leiothrix lutea","category":"鸟类","habitat":"中国南方和东南亚的山地森林","diet":"果实、昆虫和花蜜","size":"体长14-15cm,体重0.02-0.04kg","weight":"20-40g","length":"0.145m","status":"无危(LC)","emoji":"🐦","description":"红嘴黄喉绿背,羽毛鲜艳鸣声悦耳,是著名的观赏鸟,象征忠贞的爱情。","imagePrompt":"A photorealistic wildlife photograph of a red-billed leiothrix (Leiothrix lutea) with bright red beak and yellow throat perched on a flowering branch, olive-green plumage, mountain forest, soft light, National Geographic style"},
 {"name":"华丽军舰鸟","englishName":"Magnificent Frigatebird","scientificName":"Fregata magnificens","category":"鸟类","habitat":"热带海洋和岛屿","diet":"鱼和鱿鱼(抢其他海鸟的食物)","size":"体长89-114cm,翼展2.1-2.4m","weight":"1-1.7kg","length":"1m","status":"无危(LC)","emoji":"🦅","description":"雄性喉囊在求偶时鼓起如鲜红气球,翅膀展开近2.5米,是天生的飞行家。","imagePrompt":"A photorealistic wildlife photograph of a magnificent frigatebird (Fregata magnificens) male with its inflatable red throat pouch displayed, black silhouette soaring over tropical ocean, dramatic sky, National Geographic style"},

 # ===== 鱼类补充 15种 =====
 {"name":"黄鳍金枪鱼","englishName":"Yellowfin Tuna","scientificName":"Thunnus albacares","category":"鱼类","habitat":"全球热带和亚热带海域","diet":"鱼、鱿鱼和甲壳类","size":"体长1-2.4m,体重50-200kg","weight":"50-200kg","length":"1.8m","status":"近危(NT)","emoji":"🐟","description":"金黄色的鳍条和侧线,游泳健将,是生鱼片和寿司的高级食材。","imagePrompt":"A photorealistic underwater photograph of a yellowfin tuna (Thunnus albacares) with bright yellow finlets swimming in deep blue ocean, torpedo-shaped metallic body, school behind, sunbeams, National Geographic style"},
 {"name":"东星斑","englishName":"Leopard Coral Grouper","scientificName":"Plectropomus leopardus","category":"鱼类","habitat":"印度洋和西太平洋的珊瑚礁","diet":"鱼和甲壳类","size":"体长60-120cm,体重5-20kg","weight":"5-20kg","length":"0.9m","status":"无危(LC)","emoji":"🐟","description":"红褐底色布满蓝色小斑点的石斑鱼,是海鱼中的贵族,肉质细嫩。","imagePrompt":"A photorealistic underwater photograph of a leopard coral grouper (Plectropomus leopardus) with reddish-brown body covered in blue spots swimming over a coral reef, tropical water, sun rays, National Geographic style"},
 {"name":"多宝鱼","englishName":"Turbot","scientificName":"Scophthalmus maximus","category":"鱼类","habitat":"大西洋东部和地中海的沙质海底","diet":"鱼、蟹和贝类","size":"体长40-70cm,体重2-8kg","weight":"2-8kg","length":"0.55m","status":"无危(LC)","emoji":"🐟","description":"欧洲名贵的比目鱼,双眼长在左侧,体型圆扁,是海鲜宴上的贵宾。","imagePrompt":"A photorealistic underwater photograph of a turbot (Scophthalmus maximus) with flat diamond-shaped body resting camouflaged on sandy seabed, mottled brown color, both eyes on left side, soft water light, National Geographic style"},
 {"name":"花罗汉鱼","englishName":"Flowerhorn Cichlid","scientificName":"Hybrid cichlid","category":"鱼类","habitat":"人工培育的观赏鱼,源自南美慈鲷","diet":"颗粒饲料、虾和小鱼","size":"体长20-40cm,体重0.5-2kg","weight":"0.5-2kg","length":"0.3m","status":"无危(LC)","emoji":"🐠","description":"额头隆起如寿星公,全身鳞片花纹千变万化,是亚洲水族界的风水鱼。","imagePrompt":"A photorealistic underwater photograph of a flowerhorn cichlid with its prominent nuchal hump and vivid red-orange marbled body swimming in an aquarium, flowing fins, dramatic aquarium light, National Geographic style"},
 {"name":"七彩神仙鱼","englishName":"Discus","scientificName":"Symphysodon aequifasciatus","category":"鱼类","habitat":"南美洲亚马逊河流域","diet":"小型无脊椎动物和昆虫幼虫","size":"体长15-25cm,体重0.1-0.3kg","weight":"0.1-0.3kg","length":"0.2m","status":"无危(LC)","emoji":"🐠","description":"圆盘形的身体上有彩虹般的条纹,是热带观赏鱼之王,被称为水中皇后。","imagePrompt":"A photorealistic underwater photograph of discus fish (Symphysodon aequifasciatus) with round disc-shaped bodies and vivid blue-red vertical stripes swimming in planted aquarium, elegant, soft light, National Geographic style"},
 {"name":"红绿灯鱼","englishName":"Neon Tetra","scientificName":"Paracheirodon innesi","category":"鱼类","habitat":"南美洲亚马逊河流域","diet":"小型浮游生物和昆虫","size":"体长3-4cm,体重1-3g","weight":"1-3g","length":"0.035m","status":"无危(LC)","emoji":"🐠","description":"身上一条蓝色霓虹光带配红色下腹,群游时如流动的光带,水族箱的经典。","imagePrompt":"A photorealistic underwater photograph of neon tetras (Paracheirodon innesi) with glowing blue and red stripes swimming in a school in dark aquarium water, tiny luminous fish, macro detail, National Geographic style"},
 {"name":"接吻鱼","englishName":"Kissing Gourami","scientificName":"Helostoma temminckii","category":"鱼类","habitat":"东南亚的河流和湖泊","diet":"藻类和浮游生物","size":"体长20-30cm,体重0.3-0.8kg","weight":"0.3-0.8kg","length":"0.25m","status":"无危(LC)","emoji":"🐠","description":"两条鱼用嘴对嘴亲吻,其实是在争夺地盘,粉白色的身体十分可爱。","imagePrompt":"A photorealistic underwater photograph of kissing gouramis (Helostoma temminckii) touching mouths in a pond, pale pinkish bodies with thick lips, water plants, soft light, National Geographic style"},
 {"name":"中华胭脂鱼","englishName":"Chinese High-fin Banded Shark","scientificName":"Myxocyprinus asiaticus","category":"鱼类","habitat":"中国长江流域的江河","diet":"底栖无脊椎动物和藻类","size":"体长30-100cm,体重0.5-5kg","weight":"0.5-5kg","length":"0.7m","status":"易危(VU)","emoji":"🐟","description":"中国特有的珍稀淡水鱼,背鳍高高扬起如帆,身上有胭脂般的红色斑纹。","imagePrompt":"A photorealistic underwater photograph of a Chinese high-fin banded shark (Myxocyprinus asiaticus) with its tall sail-like dorsal fin swimming in a clear river, reddish-brown body with dark bands, river stones, soft light, National Geographic style"},
 {"name":"银龙鱼","englishName":"Silver Arowana","scientificName":"Osteoglossum bicirrhosum","category":"鱼类","habitat":"南美洲亚马逊河流域","diet":"鱼、昆虫和蛙类","size":"体长60-120cm,体重2-5kg","weight":"2-5kg","length":"0.9m","status":"无危(LC)","emoji":"🐟","description":"银光闪闪的长形身体,能跃出水面捕食,是水族界的银龙之王。","imagePrompt":"A photorealistic underwater photograph of a silver arowana (Osteoglossum bicirrhosum) with elongated metallic silver body swimming in dark aquarium water, large scales, barbels, dramatic light, National Geographic style"},
 {"name":"翻车鲀","englishName":"Southern Sunfish","scientificName":"Mola alexandrini","category":"鱼类","habitat":"全球温带和热带海域","diet":"水母和小鱼","size":"体长可达3.3m,体重可达2吨","weight":"可达2吨","length":"3m","status":"易危(VU)","emoji":"🐟","description":"身体像一个巨大的煎饼,是海洋里最重的硬骨鱼之一,喜欢晒太阳。","imagePrompt":"A photorealistic underwater photograph of a southern sunfish (Mola alexandrini) with its huge oval body swimming near the surface, silver-grey color, small fins, open ocean, soft light, National Geographic style"},
 {"name":"刀鱼","englishName":"Sawfish","scientificName":"Pristis pristis","category":"鱼类","habitat":"热带和亚热带的沿海和河口","diet":"小鱼和底栖生物","size":"体长4-7m,体重300-500kg","weight":"300-500kg","length":"5m","status":"极危(CR)","emoji":"🐟","description":"长吻如锯条般布满牙齿,是鲨鱼的近亲,被称为海洋中的链锯。","imagePrompt":"A photorealistic underwater photograph of a sawfish (Pristis pristis) with its long saw-like rostrum swimming in shallow coastal water, large flat body, sandy seabed, dramatic light, National Geographic style"},
 {"name":"墨鱼","englishName":"Cuttlefish","scientificName":"Sepia officinalis","category":"软体类","habitat":"大西洋和地中海的沿海","diet":"小鱼、虾和蟹","size":"体长30-50cm,体重1-5kg","weight":"1-5kg","length":"0.4m","status":"无危(LC)","emoji":"🐙","description":"会变色的伪装大师,体内有墨囊可喷墨逃生,还会用腕足跳舞迷惑猎物。","imagePrompt":"A photorealistic underwater photograph of a cuttlefish (Sepia officinalis) displaying rippling color patterns and wavy fins on sandy seabed, camouflage display, tentacles visible, soft blue water light, National Geographic style"},
 {"name":"线纹海马","englishName":"Lined Seahorse","scientificName":"Hippocampus erectus","category":"鱼类","habitat":"大西洋西部的海草床","diet":"小型甲壳类和浮游生物","size":"体长12-20cm,体重5-30g","weight":"5-30g","length":"0.15m","status":"易危(VU)","emoji":"🐴","description":"用卷曲的尾巴钩住海草,由雄性孵化育儿,是海洋里的温柔父亲。","imagePrompt":"A photorealistic underwater macro photograph of a lined seahorse (Hippocampus erectus) with curled tail anchored to seagrass in a marine meadow, ornate body pattern, soft blue water, National Geographic style"},
 {"name":"鲍鱼","englishName":"Abalone","scientificName":"Haliotis discus","category":"软体类","habitat":"西太平洋的岩礁海岸","diet":"海藻","size":"壳径10-20cm,体重0.2-1kg","weight":"0.2-1kg","length":"0.15m","status":"无危(LC)","emoji":"🐚","description":"壳上一排呼吸孔,腹足吸附岩壁力大无穷,是八珍之首的海珍品。","imagePrompt":"A photorealistic underwater photograph of abalones (Haliotis discus) with ear-shaped shells attached to a rocky reef, iridescent inner shell visible, green algae, clear water, National Geographic style"},
 {"name":"海蛞蝓","englishName":"Nudibranch","scientificName":"Chromodoris willani","category":"软体类","habitat":"印度洋和太平洋的珊瑚礁","diet":"海绵和水螅","size":"体长2-10cm,体重5-50g","weight":"5-50g","length":"0.05m","status":"无危(LC)","emoji":"🐌","description":"被称为海底的彩虹,艳丽的颜色和奇幻的形态,是潜水员最爱的拍摄对象。","imagePrompt":"A photorealistic underwater macro photograph of a nudibranch (Chromodoris willani) with vivid blue body and orange-edged gills crawling on coral, striking colors, extreme macro detail, National Geographic style"},

 # ===== 爬行类补充 10种 =====
 {"name":"巴西龟","englishName":"Red-eared Slider","scientificName":"Trachemys scripta elegans","category":"爬行类","habitat":"原产美洲,已遍布全球淡水水域","diet":"鱼、虾、水生植物和昆虫","size":"甲长15-30cm,体重0.5-2.5kg","weight":"0.5-2.5kg","length":"0.25m","status":"无危(LC)","emoji":"🐢","description":"耳后有红色条纹的小龟,是最常见的宠物龟,也是著名的入侵物种。","imagePrompt":"A photorealistic wildlife photograph of a red-eared slider (Trachemys scripta elegans) basking on a log in a pond, green shell with red ear stripes, head stretched out, water reflections, soft light, National Geographic style"},
 {"name":"变色龙","englishName":"Panther Chameleon","scientificName":"Furcifer pardalis","category":"爬行类","habitat":"马达加斯加的热带雨林","diet":"昆虫","size":"体长30-50cm,体重0.1-0.5kg","weight":"0.1-0.5kg","length":"0.4m","status":"无危(LC)","emoji":"🦎","description":"色彩最艳丽的变色龙,绿蓝橙红随心变换,眼睛可独立转动360度。","imagePrompt":"A photorealistic wildlife photograph of a panther chameleon (Furcifer pardalis) with vivid turquoise and red bands perched on a branch, independently rotating eyes, curled tail, Madagascar rainforest, National Geographic style"},
 {"name":"睫角守宫","englishName":"Crested Gecko","scientificName":"Correlophus ciliatus","category":"爬行类","habitat":"新喀里多尼亚的热带雨林","diet":"果实和昆虫","size":"体长20-25cm,体重0.03-0.06kg","weight":"30-60g","length":"0.22m","status":"无危(LC)","emoji":"🦎","description":"眼上长着睫毛般的突起,尾巴可再生长,是宠物市场的明星守宫。","imagePrompt":"A photorealistic wildlife photograph of a crested gecko (Correlophus ciliatus) with eyelash-like crests perched on a tropical leaf, mottled orange and brown pattern, large eyes, macro detail, soft light, National Geographic style"},
 {"name":"泰加蜥","englishName":"Argentine Black and White Tegu","scientificName":"Salvator merianae","category":"爬行类","habitat":"南美洲的草原和森林","diet":"杂食:昆虫、果实、蛋和小动物","size":"体长1-1.4m,体重2-5kg","weight":"2-5kg","length":"1.2m","status":"无危(LC)","emoji":"🦎","description":"黑白相间斑纹的大型蜥蜴,智力高会认主人,是智商最高的蜥蜴之一。","imagePrompt":"A photorealistic wildlife photograph of an Argentine black and white tegu (Salvator merianae) with bold black and white banded pattern walking on grassland, forked tongue flicking, South American pampas, golden light, National Geographic style"},
 {"name":"网纹蟒","englishName":"Reticulated Python","scientificName":"Malayopython reticulatus","category":"爬行类","habitat":"东南亚的热带雨林","diet":"鼠、鹿、野猪等哺乳动物","size":"体长5-8m,体重50-140kg","weight":"50-140kg","length":"7m","status":"无危(LC)","emoji":"🐍","description":"世界上最长的蛇,可超过8米,网纹如钻石般的花纹,是蟒蛇中的巨无霸。","imagePrompt":"A photorealistic wildlife photograph of a reticulated python (Malayopython reticulatus) draped over a rainforest branch, extremely long body with intricate diamond net pattern, jungle canopy, dappled light, National Geographic style"},
 {"name":"蝮蛇","englishName":"Mamushi","scientificName":"Gloydius blomhoffii","category":"爬行类","habitat":"东亚的草丛、山地和农田","diet":"鼠、蛙和鸟","size":"体长0.5-0.8m,体重0.1-0.4kg","weight":"0.1-0.4kg","length":"0.65m","status":"无危(LC)","emoji":"🐍","description":"日本和中国常见的毒蛇,灰褐色带深色斑纹,毒性较强,是田野间的危险者。","imagePrompt":"A photorealistic wildlife photograph of a mamushi (Gloydius blomhoffii) coiled on a mossy rock, brownish-grey body with dark blotches, triangular head, forest floor, soft light, National Geographic style"},
 {"name":"草龟","englishName":"Yellow-margined Box Turtle","scientificName":"Cuora flavomarginata","category":"爬行类","habitat":"中国南方和台湾的山地森林","diet":"昆虫、蚯蚓、果实和菌类","size":"甲长12-18cm,体重0.3-0.8kg","weight":"0.3-0.8kg","length":"0.15m","status":"濒危(EN)","emoji":"🐢","description":"背甲隆起如穹顶,腹甲可完全闭合,是陆生性的箱龟,中国特有的珍稀龟。","imagePrompt":"A photorealistic wildlife photograph of a yellow-margined box turtle (Cuora flavomarginata) with domed shell walking on a forest floor, dark shell with yellow margin, leaf litter, soft light, National Geographic style"},
 {"name":"盲蛇","englishName":"Brahminy Blind Snake","scientificName":"Indotyphlops braminus","category":"爬行类","habitat":"全球热带和亚热带的地下","diet":"蚂蚁和白蚁的幼虫","size":"体长6-10cm,体重1-3g","weight":"1-3g","length":"0.08m","status":"无危(LC)","emoji":"🐍","description":"像蚯蚓一样的小蛇,眼睛退化,生活在地下,是全世界最小的蛇之一。","imagePrompt":"A photorealistic macro photograph of a brahminy blind snake (Indotyphlops braminus) resembling a shiny earthworm slithering on moist soil, tiny glossy dark body, underground habitat, macro detail, soft light, National Geographic style"},

 # ===== 两栖类补充 10种 =====
 {"name":"非洲爪蟾","englishName":"African Clawed Frog","scientificName":"Xenopus laevis","category":"两栖类","habitat":"非洲南部的池塘和河流","diet":"昆虫、小鱼和水生无脊椎动物","size":"体长8-13cm,体重0.1-0.3kg","weight":"0.1-0.3kg","length":"0.11m","status":"无危(LC)","emoji":"🐸","description":"实验室里著名的模式生物,无舌无眼睑,后足有爪,全球最早的克隆动物。","imagePrompt":"A photorealistic underwater photograph of an African clawed frog (Xenopus laevis) swimming in clear water, flattened grey body with clawed back feet, smooth skin, aquarium plants, soft light, National Geographic style"},
 {"name":"东方蝾螈","englishName":"Oriental Fire-bellied Newt","scientificName":"Cynops orientalis","category":"两栖类","habitat":"中国东部的池塘和稻田","diet":"昆虫幼虫、水蚤和小型无脊椎动物","size":"体长6-10cm,体重5-15g","weight":"5-15g","length":"0.08m","status":"无危(LC)","emoji":"🦎","description":"背部黑色腹部橙红色,遇到危险会翻肚露出警戒色,是常见的水生宠物。","imagePrompt":"A photorealistic macro photograph of an oriental fire-bellied newt (Cynops orientalis) swimming in clear water, black back with bright orange-red belly visible, aquatic plants, macro detail, National Geographic style"},
 {"name":"玻璃蛙","englishName":"Glass Frog","scientificName":"Hyalinobatrachium fleischmanni","category":"两栖类","habitat":"中南美洲的热带雨林溪流","diet":"昆虫和小型无脊椎动物","size":"体长2-3.5cm,体重2-5g","weight":"2-5g","length":"0.03m","status":"无危(LC)","emoji":"🐸","description":"腹部皮肤透明,能看到跳动的心脏和内脏,是自然界最神奇的透明生物。","imagePrompt":"A photorealistic macro photograph of a glass frog (Hyalinobatrachium fleischmanni) on a leaf showing its transparent belly with visible internal organs and heart, lime green body, extreme macro, dark jungle background, National Geographic style"},
 {"name":"火蝾螈","englishName":"Fire Salamander","scientificName":"Salamandra salamandra","category":"两栖类","habitat":"欧洲的山地森林","diet":"昆虫、蜘蛛和蚯蚓","size":"体长15-25cm,体重0.02-0.05kg","weight":"20-50g","length":"0.2m","status":"无危(LC)","emoji":"🦎","description":"黑色身体配黄色斑纹,传说能从火中逃生,皮肤分泌的毒素用于自卫。","imagePrompt":"A photorealistic wildlife photograph of a fire salamander (Salamandra salamandra) with black body and vivid yellow spots on damp forest floor, glossy skin, moss and fallen leaves, soft light, National Geographic style"},
 {"name":"海蟾蜍","englishName":"Cane Toad","scientificName":"Rhinella marina","category":"两栖类","habitat":"中南美洲,已入侵澳洲和东南亚","diet":"几乎什么都吃:昆虫、鼠、鸟","size":"体长10-20cm,体重0.5-2kg","weight":"0.5-2kg","length":"0.15m","status":"无危(LC)","emoji":"🐸","description":"世界上最大的蟾蜍,毒腺分泌蟾毒素,在澳洲造成严重生态灾难。","imagePrompt":"A photorealistic wildlife photograph of a cane toad (Rhinella marina) on a tropical road at night, huge warty brown body, prominent parotoid glands, night lighting, dramatic shadows, National Geographic style"},
 {"name":"树蛙","englishName":"Common Tree Frog","scientificName":"Polypedates leucomystax","category":"两栖类","habitat":"南亚和东南亚的林地、竹丛","diet":"昆虫","size":"体长4-7cm,体重5-15g","weight":"5-15g","length":"0.06m","status":"无危(LC)","emoji":"🐸","description":"黄褐色带深色斑点,脚趾有吸盘可爬玻璃,是树蛙中常见的一员。","imagePrompt":"A photorealistic macro photograph of a common tree frog (Polypedates leucomystax) clinging to a green leaf, brownish body with dark spots, suction toe pads visible, macro detail, soft light, National Geographic style"},
 {"name":"蛙嘴龙","englishName":"Surinam Toad","scientificName":"Pipa pipa","category":"两栖类","habitat":"南美洲亚马逊河流域","diet":"小鱼和无脊椎动物","size":"体长10-20cm,体重0.1-0.3kg","weight":"0.1-0.3kg","length":"0.15m","status":"无危(LC)","emoji":"🐸","description":"身体扁平如枯叶,卵在母亲背部皮肤中孵化,是自然界最奇特的水生蛙。","imagePrompt":"A photorealistic underwater photograph of a Surinam toad (Pipa pipa) with flat leaf-like body resting on a riverbed, textured skin with embedded eggs, Amazon river, soft light, National Geographic style"},
 {"name":"大绿蛙","englishName":"Green Pond Frog","scientificName":"Pelophylax plancyi","category":"两栖类","habitat":"东亚的稻田和池塘","diet":"昆虫和蜘蛛","size":"体长6-9cm,体重20-60g","weight":"20-60g","length":"0.075m","status":"无危(LC)","emoji":"🐸","description":"通体翠绿,是中国南方稻田最常见的蛙类,与人类生活密切相伴。","imagePrompt":"A photorealistic wildlife photograph of a green pond frog (Pelophylax plancyi) sitting on a lotus leaf in a rice paddy, bright green body, water reflections, summer light, National Geographic style"},
 {"name":"姬蛙","englishName":"Ornate Narrow-mouthed Frog","scientificName":"Microhyla ornata","category":"两栖类","habitat":"东亚和南亚的湿地","diet":"蚂蚁和白蚁","size":"体长2-3cm,体重2-5g","weight":"2-5g","length":"0.025m","status":"无危(LC)","emoji":"🐸","description":"体长仅2-3厘米的小蛙,背上花纹如大理石,是稻田里的小不点。","imagePrompt":"A photorealistic macro photograph of an ornate narrow-mouthed frog (Microhyla ornata) tiny frog on a green leaf, marble-like back pattern, extreme macro, dew drops, soft light, National Geographic style"},
 {"name":"林蛙","englishName":"Dybowsky's Brown Frog","scientificName":"Rana dybowskii","category":"两栖类","habitat":"东亚的森林和湿地","diet":"昆虫和蜘蛛","size":"体长5-8cm,体重15-40g","weight":"15-40g","length":"0.065m","status":"无危(LC)","emoji":"🐸","description":"褐色的林蛙,生活在森林溪流边,是哈士蟆油的来源,东北的珍品。","imagePrompt":"A photorealistic wildlife photograph of a Dybowsky's brown frog (Rana dybowskii) perched on a mossy forest rock near a stream, brown body with dark markings, moist skin, soft forest light, National Geographic style"},

 # ===== 补充2条独特动物 =====
 {"name":"蜜袋鼯","englishName":"Sugar Glider","scientificName":"Petaurus breviceps","category":"哺乳类","habitat":"澳大利亚和新几内亚的森林","diet":"花蜜、树汁、昆虫和小动物","size":"体长12-32cm(含尾),体重95-160g","weight":"95-160g","length":"0.2m","status":"无危(LC)","emoji":"🐿️","description":"会滑翔的小型有袋动物,四肢间的翼膜展开如降落伞,能在树间滑翔50米。","imagePrompt":"A photorealistic wildlife photograph of a sugar glider (Petaurus breviceps) gliding between trees with its membrane stretched, grey body with dark stripe, Australian forest at dusk, soft light, National Geographic style"},
 {"name":"鸮鹦鹉","englishName":"Kakapo","scientificName":"Strigops habroptilus","category":"鸟类","habitat":"新西兰的原始森林","diet":"植物、果实和种子","size":"体长58-64cm,体重1.5-4kg","weight":"1.5-4kg","length":"0.6m","status":"极危(CR)","emoji":"🦜","description":"世界上唯一不会飞的鹦鹉,夜行性,全球仅存200余只,是新西兰的国宝。","imagePrompt":"A photorealistic wildlife photograph of a kakapo (Strigops habroptilus) with mossy green plumage and owl-like face walking on a forest floor at night, flightless parrot, New Zealand rainforest, soft moonlight, National Geographic style"},
]

