# -*- coding: utf-8 -*-
# 两栖类20 + 昆虫类16 + 甲壳类5 + 软体类5 = 46种 (batch 5)
AMPHIBIANS = [
 {"name":"中国大鲵","englishName":"Chinese Giant Salamander","scientificName":"Andrias davidianus","category":"两栖类","habitat":"中国长江、黄河中上游的清澈山溪","diet":"鱼、虾、蟹、蛙和水生昆虫","size":"体长60-180cm,体重5-50kg","weight":"5-50kg","length":"1m","status":"极危(CR)","emoji":"🦎","description":"娃娃鱼,现存最大的两栖动物,叫声像婴儿啼哭,已在野外生活了3.5亿年。","imagePrompt":"A photorealistic underwater photograph of a Chinese giant salamander (Andrias davidianus) resting on rocks in a clear mountain stream, huge dark brown body with wrinkled skin, flat head with small eyes, cold clean water, National Geographic style"},
 {"name":"东方蝾螈","englishName":"Oriental Fire-bellied Newt","scientificName":"Cynops orientalis","category":"两栖类","habitat":"中国东部的池塘和稻田","diet":"昆虫幼虫、水蚤和小型无脊椎动物","size":"体长6-10cm,体重5-15g","weight":"5-15g","length":"0.08m","status":"无危(LC)","emoji":"🦎","description":"背部黑色腹部橙红色,遇到危险会翻肚露出警戒色,是常见的水生宠物。","imagePrompt":"A photorealistic macro photograph of an oriental fire-bellied newt (Cynops orientalis) swimming in clear water, black back with bright orange-red belly visible, aquatic plants, macro detail, National Geographic style"},
 {"name":"中国林蛙","englishName":"Chinese Brown Frog","scientificName":"Rana chensinensis","category":"两栖类","habitat":"中国北方和东北的山地森林","diet":"昆虫、蜘蛛和蠕虫","size":"体长5-8cm,体重15-40g","weight":"15-40g","length":"0.07m","status":"无危(LC)","emoji":"🐸","description":"雪蛤的原型,秋末钻入水底冬眠,雌蛙输卵管是珍贵的滋补品。","imagePrompt":"A photorealistic wildlife photograph of a Chinese brown frog (Rana chensinensis) perched on a mossy forest rock, brown body with dark markings, moist skin, forest stream background, soft light, National Geographic style"},
 {"name":"牛蛙","englishName":"American Bullfrog","scientificName":"Lithobates catesbeianus","category":"两栖类","habitat":"原产北美,现全球引进","diet":"昆虫、鱼、蛙、鼠,几乎什么都吃","size":"体长10-20cm,体重0.2-1kg","weight":"0.2-1kg","length":"0.15m","status":"无危(LC)","emoji":"🐸","description":"叫声如牛吼的巨型青蛙,大鼓膜和贪吃的胃口,是世界入侵物种之一。","imagePrompt":"A photorealistic wildlife photograph of an American bullfrog (Lithobates catesbeianus) sitting in a pond, large green body with distinctive tympanum ear drums, water lilies, golden light, National Geographic style"},
 {"name":"金色箭毒蛙","englishName":"Golden Poison Frog","scientificName":"Phyllobates terribilis","category":"两栖类","habitat":"哥伦比亚的热带雨林","diet":"蚂蚁、甲虫和白蚁","size":"体长3-6cm,体重1-5g","weight":"1-5g","length":"0.05m","status":"濒危(EN)","emoji":"🐸","description":"世界上最毒的动物之一,一只蛙的毒素可毒死10个成年人,金黄色警告色。","imagePrompt":"A photorealistic macro photograph of a golden poison frog (Phyllobates terribilis) perched on a rainforest leaf, brilliant yellow-orange skin, tiny size, vivid color warning, lush green background, National Geographic style"},
 {"name":"红眼树蛙","englishName":"Red-eyed Tree Frog","scientificName":"Agalychnis callidryas","category":"两栖类","habitat":"中南美洲的热带雨林","diet":"蟋蟀、飞蛾和昆虫","size":"体长5-8cm,体重5-15g","weight":"5-15g","length":"0.07m","status":"无危(LC)","emoji":"🐸","description":"红色大眼睛,翠绿身体,橙色脚趾,蓝黄条纹侧腹,是雨林中最上镜的青蛙。","imagePrompt":"A photorealistic macro photograph of a red-eyed tree frog (Agalychnis callidryas) perched on a green leaf, vivid red eyes, emerald green body, orange toes, blue and yellow side stripes, macro detail, National Geographic style"},
 {"name":"玻璃蛙","englishName":"Glass Frog","scientificName":"Hyalinobatrachium fleischmanni","category":"两栖类","habitat":"中南美洲的热带雨林溪流","diet":"昆虫和小型无脊椎动物","size":"体长2-3.5cm,体重2-5g","weight":"2-5g","length":"0.03m","status":"无危(LC)","emoji":"🐸","description":"腹部皮肤透明,能看到跳动的心脏和内脏,是自然界最神奇的透明生物。","imagePrompt":"A photorealistic macro photograph of a glass frog (Hyalinobatrachium fleischmanni) on a leaf showing its transparent belly with visible internal organs and heart, lime green body, extreme macro, dark jungle background, National Geographic style"},
 {"name":"非洲爪蟾","englishName":"African Clawed Frog","scientificName":"Xenopus laevis","category":"两栖类","habitat":"非洲南部的池塘和河流","diet":"昆虫、小鱼和水生无脊椎动物","size":"体长8-13cm,体重0.1-0.3kg","weight":"0.1-0.3kg","length":"0.11m","status":"无危(LC)","emoji":"🐸","description":"实验室里著名的模式生物,无舌无眼睑,后足有爪,全球最早的克隆动物。","imagePrompt":"A photorealistic underwater photograph of an African clawed frog (Xenopus laevis) swimming in clear water, flattened grey body with clawed back feet, smooth skin, aquarium plants, soft light, National Geographic style"},
 {"name":"中华蟾蜍","englishName":"Asiatic Toad","scientificName":"Bufo gargarizans","category":"两栖类","habitat":"中国和东亚的农田、庭院和林地","diet":"昆虫、蚯蚓和蜗牛","size":"体长6-12cm,体重0.03-0.1kg","weight":"30-100g","length":"0.1m","status":"无危(LC)","emoji":"🐸","description":"癞蛤蟆,全身疙瘩分泌蟾酥,是农田的害虫卫士,民间有蟾宫折桂的典故。","imagePrompt":"A photorealistic wildlife photograph of an Asiatic toad (Bufo gargarizans) sitting on garden soil at dusk, warty brown skin with parotoid glands, patient pose, soft evening light, National Geographic style"},
 {"name":"海蟾蜍","englishName":"Cane Toad","scientificName":"Rhinella marina","category":"两栖类","habitat":"中南美洲,已入侵澳洲和东南亚","diet":"几乎什么都吃:昆虫、鼠、鸟","size":"体长10-20cm,体重0.5-2kg","weight":"0.5-2kg","length":"0.15m","status":"无危(LC)","emoji":"🐸","description":"世界上最大的蟾蜍,毒腺分泌蟾毒素,在澳洲造成严重生态灾难。","imagePrompt":"A photorealistic wildlife photograph of a cane toad (Rhinella marina) on a tropical road at night, huge warty brown body, prominent parotoid glands, night lighting, dramatic shadows, National Geographic style"},
 {"name":"角蛙","englishName":"Horned Frog","scientificName":"Ceratophrys ornata","category":"两栖类","habitat":"南美洲的雨林地面","diet":"昆虫、鼠、鱼,甚至其他青蛙","size":"体长8-15cm,体重0.1-0.5kg","weight":"0.1-0.5kg","length":"0.12m","status":"无危(LC)","emoji":"🐸","description":"嘴大如盆的守株待兔型猎手,绿色带角状突起的可爱圆脸,是受欢迎的宠物蛙。","imagePrompt":"A photorealistic macro photograph of an ornate horned frog (Ceratophrys ornata) buried in moist soil with only head visible, round green body with horn-like ridges, big mouth, macro detail, National Geographic style"},
 {"name":"墨西哥钝口螈","englishName":"Axolotl","scientificName":"Ambystoma mexicanum","category":"两栖类","habitat":"墨西哥城的湖泊(野外已濒危)","diet":"蠕虫、昆虫和小鱼","size":"体长20-30cm,体重0.1-0.3kg","weight":"0.1-0.3kg","length":"0.25m","status":"极危(CR)","emoji":"🦎","description":"六角恐龙,永远保持幼体形态,头上三对外鳃如花瓣,断肢可再生,科学明星。","imagePrompt":"A photorealistic underwater photograph of a pink axolotl (Ambystoma mexicanum) with external feathery gills swimming in clear water, pale pink body, dark eyes, aquatic plants, soft aquarium light, National Geographic style"},
 {"name":"火蝾螈","englishName":"Fire Salamander","scientificName":"Salamandra salamandra","category":"两栖类","habitat":"欧洲的山地森林","diet":"昆虫、蜘蛛和蚯蚓","size":"体长15-25cm,体重0.02-0.05kg","weight":"20-50g","length":"0.2m","status":"无危(LC)","emoji":"🦎","description":"黑色身体配黄色斑纹,传说能从火中逃生,皮肤分泌的毒素用于自卫。","imagePrompt":"A photorealistic wildlife photograph of a fire salamander (Salamandra salamandra) with black body and vivid yellow spots on damp forest floor, glossy skin, moss and fallen leaves, soft light, National Geographic style"},
 {"name":"黑斑侧褶蛙","englishName":"Black-spotted Frog","scientificName":"Pelophylax nigromaculatus","category":"两栖类","habitat":"中国和东亚的稻田、池塘","diet":"昆虫和蜘蛛","size":"体长6-10cm,体重15-50g","weight":"15-50g","length":"0.08m","status":"无危(LC)","emoji":"🐸","description":"稻田里的绿衣卫士,背上有不规则的黑色斑点,蛙声一片是夏天的记忆。","imagePrompt":"A photorealistic wildlife photograph of a black-spotted frog (Pelophylax nigromaculatus) sitting on a lotus leaf in a rice paddy, green body with dark spots, water reflections, golden summer light, National Geographic style"},
 {"name":"斑腿泛树蛙","englishName":"Spot-legged Tree Frog","scientificName":"Polypedates megacephalus","category":"两栖类","habitat":"中国南方和东南亚的林地、竹丛","diet":"昆虫","size":"体长4-7cm,体重5-15g","weight":"5-15g","length":"0.06m","status":"无危(LC)","emoji":"🐸","description":"黄褐色带深色斑点,脚趾有吸盘可爬玻璃,是树蛙中常见的一员。","imagePrompt":"A photorealistic macro photograph of a spot-legged tree frog (Polypedates megacephalus) clinging to a green leaf, brownish body with dark spots, suction toe pads visible, macro detail, soft light, National Geographic style"},
 {"name":"虎纹蛙","englishName":"Indian Bullfrog","scientificName":"Hoplobatrachus tigerinus","category":"两栖类","habitat":"南亚和东南亚的稻田、池塘","diet":"昆虫、鱼和其他蛙类","size":"体长8-15cm,体重0.05-0.3kg","weight":"50-300g","length":"0.12m","status":"无危(LC)","emoji":"🐸","description":"背上有虎纹般的条纹,繁殖期雄性变成鲜黄色配蓝色声囊,是蛙界的变色龙。","imagePrompt":"A photorealistic wildlife photograph of an Indian bullfrog (Hoplobatrachus tigerinus) in breeding colors, yellow body with blue vocal sacs, sitting in pond water, dramatic colors, golden light, National Geographic style"},
 {"name":"雨蛙","englishName":"European Tree Frog","scientificName":"Hyla arborea","category":"两栖类","habitat":"欧洲和亚洲的灌木、葡萄园","diet":"昆虫","size":"体长3-5cm,体重3-10g","weight":"3-10g","length":"0.04m","status":"无危(LC)","emoji":"🐸","description":"鲜绿色的身体带黑色眼线,脚趾吸盘能吸附叶片,雨后歌声最响亮。","imagePrompt":"A photorealistic macro photograph of a European tree frog (Hyla arborea) perched on a vine leaf, bright green body with black eye stripe, suction toes, dew drops on leaves, soft light, National Geographic style"},
 {"name":"石蛙","englishName":"Chinese Edible Frog","scientificName":"Quasipaa spinosa","category":"两栖类","habitat":"中国南方的山溪石涧","diet":"昆虫、虾和小鱼","size":"体长8-15cm,体重0.1-0.4kg","weight":"0.1-0.4kg","length":"0.12m","status":"易危(VU)","emoji":"🐸","description":"棘胸蛙,生活在清澈山溪中,肉质鲜美被誉为山珍,现在多为人工养殖。","imagePrompt":"A photorealistic wildlife photograph of a Chinese edible frog (Quasipaa spinosa) resting on wet rocks in a mountain stream, dark olive body with rough skin, rushing water, misty forest, soft light, National Geographic style"},
 {"name":"锯缘龟蛙","englishName":"Burrowing Frog","scientificName":"Rhinophrynus dorsalis","category":"两栖类","habitat":"中美洲的热带低地","diet":"白蚁和蚂蚁","size":"体长5-8cm,体重0.02-0.05kg","weight":"20-50g","length":"0.06m","status":"无危(LC)","emoji":"🐸","description":"圆滚滚像皮球的蛙,前足铲状用于挖洞,下雨时才钻出地面鸣叫。","imagePrompt":"A photorealistic macro photograph of a burrowing frog (Rhinophrynus dorsalis) with round balloon-like body sitting on wet earth after rain, brown with red dorsal stripe, tiny pointed head, macro detail, soft light, National Geographic style"},
]

INSECTS = [
 {"name":"中华蜜蜂","englishName":"Chinese Honey Bee","scientificName":"Apis cerana","category":"昆虫类","habitat":"中国和东亚的森林、果园","diet":"花蜜和花粉","size":"体长1-1.5cm,体重0.1-0.3g","weight":"0.1-0.3g","length":"0.012m","status":"无危(LC)","emoji":"🐝","description":"中国本土的蜜蜂,耐寒抗螨,中华土蜂蜜的酿造者,对生态传粉至关重要。","imagePrompt":"A photorealistic macro photograph of a Chinese honey bee (Apis cerana) collecting nectar on a yellow flower, fuzzy yellow and black striped body, translucent wings, pollen on legs, macro detail, National Geographic style"},
 {"name":"意大利蜂","englishName":"Western Honey Bee","scientificName":"Apis mellifera","category":"昆虫类","habitat":"全球广泛饲养","diet":"花蜜和花粉","size":"体长1.2-1.5cm,体重0.1-0.2g","weight":"0.1-0.2g","length":"0.013m","status":"无危(LC)","emoji":"🐝","description":"全世界最普遍饲养的蜜蜂,产蜜量高,分工明确,蜂王、工蜂、雄蜂各司其职。","imagePrompt":"A photorealistic macro photograph of western honey bees (Apis mellifera) on a honeycomb, golden hexagonal cells, bees working, honey droplets, macro detail, warm light, National Geographic style"},
 {"name":"帝王蝶","englishName":"Monarch Butterfly","scientificName":"Danaus plexippus","category":"昆虫类","habitat":"北美洲,迁徙至墨西哥越冬","diet":"幼虫吃马利筋,成虫吸花蜜","size":"翼展8-10cm,体重0.3-0.5g","weight":"0.3-0.5g","length":"0.09m","status":"无危(LC)","emoji":"🦋","description":"橙黑相间的王者之蝶,每年数百万只迁徙4000公里到墨西哥过冬,场面震撼。","imagePrompt":"A photorealistic macro photograph of monarch butterflies (Danaus plexippus) with orange and black patterned wings clustered on a tree branch, thousands of butterflies, forest background, soft light, National Geographic style"},
 {"name":"枯叶蝶","englishName":"Indian Leaf Butterfly","scientificName":"Kallima inachus","category":"昆虫类","habitat":"东南亚和中国的雨林","diet":"树液和腐烂果实","size":"翼展8-10cm,体重0.3-0.8g","weight":"0.3-0.8g","length":"0.08m","status":"无危(LC)","emoji":"🦋","description":"合翅时像一片枯叶,叶脉叶柄俱全,是拟态艺术的巅峰之作。","imagePrompt":"A photorealistic macro photograph of an Indian leaf butterfly (Kallima inachus) with wings closed looking exactly like a dried brown leaf with veins, perched on a branch, camouflage masterpiece, soft forest light, National Geographic style"},
 {"name":"柑橘凤蝶","englishName":"Swallowtail Butterfly","scientificName":"Papilio xuthus","category":"昆虫类","habitat":"东亚的果园和花园","diet":"幼虫吃柑橘叶,成虫吸花蜜","size":"翼展7-10cm,体重0.3-0.8g","weight":"0.3-0.8g","length":"0.08m","status":"无危(LC)","emoji":"🦋","description":"黄黑色条纹配蓝色红斑的后翅,拖着燕尾状尾突,是城市花园常见的大蝴蝶。","imagePrompt":"A photorealistic macro photograph of a swallowtail butterfly (Papilio xuthus) with yellow and black striped wings resting on a pink flower, tail extensions visible, wing detail, soft garden light, National Geographic style"},
 {"name":"乌桕大蚕蛾","englishName":"Atlas Moth","scientificName":"Attacus atlas","category":"昆虫类","habitat":"东南亚和中国的热带森林","diet":"幼虫吃乌桕、樟树等树叶","size":"翼展可达25cm,体重5-15g","weight":"5-15g","length":"0.25m","status":"无危(LC)","emoji":"🦋","description":"世界上最大的蛾,翼展可达25厘米,翅尖如蛇头吓退天敌,飞蛾中的巨无霸。","imagePrompt":"A photorealistic macro photograph of an atlas moth (Attacus atlas) with enormous 25cm wingspan perched on a tree trunk, reddish-brown wings with snake-head wing tips, intricate patterns, macro detail, National Geographic style"},
 {"name":"独角仙","englishName":"Japanese Rhinoceros Beetle","scientificName":"Allomyrina dichotoma","category":"昆虫类","habitat":"东亚的阔叶林","diet":"幼虫吃腐木,成虫吸树液和水果","size":"体长4-8cm,体重10-40g","weight":"10-40g","length":"0.06m","status":"无危(LC)","emoji":"🪲","description":"头部长着威武的Y形巨角,甲虫中的大力士,能举起自身体重850倍的物体。","imagePrompt":"A photorealistic macro photograph of a Japanese rhinoceros beetle (Allomyrina dichotoma) with a large Y-shaped horn on a tree branch, glossy dark brown armor, powerful pose, macro detail, soft forest light, National Geographic style"},
 {"name":"锹甲","englishName":"Stag Beetle","scientificName":"Lucanus maculifemoratus","category":"昆虫类","habitat":"东亚和欧洲的森林","diet":"树液和腐烂果实","size":"体长2-8cm(含颚),体重5-30g","weight":"5-30g","length":"0.06m","status":"无危(LC)","emoji":"🪲","description":"雄虫上颚如鹿角般巨大,用于争夺配偶,是昆虫收藏家钟爱的明星。","imagePrompt":"A photorealistic macro photograph of a stag beetle (Lucanus maculifemoratus) with enormous antler-like mandibles perched on tree bark, dark glossy armor, imposing pose, macro detail, forest light, National Geographic style"},
 {"name":"萤火虫","englishName":"Firefly","scientificName":"Luciola lateralis","category":"昆虫类","habitat":"东亚的湿地、稻田和溪流","diet":"幼虫吃蜗牛,成虫只喝露水","size":"体长1-1.5cm,体重0.05-0.1g","weight":"0.05-0.1g","length":"0.012m","status":"近危(NT)","emoji":"✨","description":"腹末发光器闪烁如流星,夏夜里的童话之光,是环境良好的指示物种。","imagePrompt":"A photorealistic macro photograph of fireflies (Luciola lateralis) glowing in a summer meadow at night, hundreds of tiny yellow-green lights floating in darkness, long exposure light trails, magical night atmosphere, National Geographic style"},
 {"name":"中华大刀螳","englishName":"Chinese Mantis","scientificName":"Tenodera sinensis","category":"昆虫类","habitat":"中国和东亚的草地、灌木","diet":"昆虫、蜘蛛,甚至小鸟和蛙","size":"体长5-10cm,体重3-8g","weight":"3-8g","length":"0.08m","status":"无危(LC)","emoji":"🦗","description":"绿色的大刀客,前足如镰刀闪电出击,是农田的益虫,也是猎杀高手。","imagePrompt":"A photorealistic macro photograph of a Chinese mantis (Tenodera sinensis) perched on a green stem, long green body, raptorial forelegs raised in hunting pose, triangular head with large compound eyes, macro detail, National Geographic style"},
 {"name":"碧伟蜓","englishName":"Green Darner Dragonfly","scientificName":"Anax parthenope","category":"昆虫类","habitat":"欧亚大陆的池塘和湖泊","diet":"飞行中捕食蚊子、苍蝇等","size":"体长6-8cm,翼展8-10cm,体重0.5-1g","weight":"0.5-1g","length":"0.07m","status":"无危(LC)","emoji":"🪰","description":"翠绿色的身体配透明的四片翅膀,空中格斗士,俯冲时速可达50公里。","imagePrompt":"A photorealistic macro photograph of a green darner dragonfly (Anax parthenope) hovering above pond water, bright green thorax, four transparent veined wings, blue abdomen, water reflections, macro detail, National Geographic style"},
 {"name":"黑蚱蝉","englishName":"Black Cicada","scientificName":"Cryptotympana atrata","category":"昆虫类","habitat":"中国和东亚的树林","diet":"幼虫吸树根汁液,成虫吸树汁","size":"体长3-5cm,翼展8-12cm,体重1-3g","weight":"1-3g","length":"0.04m","status":"无危(LC)","emoji":"🪰","description":"蝉噪林逾静的蝉,雄虫鸣声可传数百米,在地下蛰伏数年才出土羽化。","imagePrompt":"A photorealistic macro photograph of a black cicada (Cryptotympana atrata) with translucent veined wings perched on a tree trunk, black body, morning dew, bark texture, macro detail, soft light, National Geographic style"},
 {"name":"斗蟋","englishName":"Cricket","scientificName":"Velarifictorus micado","category":"昆虫类","habitat":"东亚的草地和墙缝","diet":"植物嫩芽、果实和昆虫","size":"体长1.5-2.5cm,体重0.3-1g","weight":"0.3-1g","length":"0.02m","status":"无危(LC)","emoji":"🦗","description":"蟋蟀,促织,中国斗蟋文化千年,雄虫好斗,鸣声清脆,曾是宫廷游戏的主角。","imagePrompt":"A photorealistic macro photograph of a cricket (Velarifictorus micado) on a stone in moonlight, dark brown body, long antennae, glossy wings, night atmosphere, macro detail, National Geographic style"},
 {"name":"东亚飞蝗","englishName":"Oriental Migratory Locust","scientificName":"Locusta migratoria manilensis","category":"昆虫类","habitat":"亚洲的草原和农田","diet":"禾本科植物,可形成蝗灾","size":"体长3-6cm,体重1-3g","weight":"1-3g","length":"0.05m","status":"无危(LC)","emoji":"🦗","description":"引发蝗灾的主角,成灾时遮天蔽日,食量惊人,是农业的头号害虫。","imagePrompt":"A photorealistic macro photograph of a migratory locust (Locusta migratoria) on a grass stem, brown and green mottled body, powerful jumping legs, grassland background, dramatic light, National Geographic style"},
 {"name":"日本弓背蚁","englishName":"Carpenter Ant","scientificName":"Camponotus japonicus","category":"昆虫类","habitat":"东亚的森林和庭园","diet":"蜜露、昆虫和小动物尸体","size":"体长0.5-1.5cm,体重5-50mg","weight":"5-50mg","length":"0.012m","status":"无危(LC)","emoji":"🐜","description":"大个头黑色蚂蚁,能搬动自身体重50倍的物体,社会分工严密的建筑大师。","imagePrompt":"A photorealistic macro photograph of carpenter ants (Camponotus japonicus) carrying leaves in a line on tree bark, shiny black bodies, teamwork, macro detail, forest floor light, National Geographic style"},
 {"name":"七星瓢虫","englishName":"Seven-spotted Ladybug","scientificName":"Coccinella septempunctata","category":"昆虫类","habitat":"欧亚大陆的农田和花园","diet":"蚜虫,一天可吃上百只","size":"体长0.5-0.8cm,体重20-50mg","weight":"20-50mg","length":"0.007m","status":"无危(LC)","emoji":"🐞","description":"红底黑点的吉祥小甲虫,花大姐,是蚜虫的天敌,农田的小卫士。","imagePrompt":"A photorealistic macro photograph of a seven-spotted ladybug (Coccinella septempunctata) with red wings and seven black spots on a green leaf with aphids, dew drops, macro detail, soft light, National Geographic style"},
 {"name":"竹节虫","englishName":"Stick Insect","scientificName":"Phasmatodea","category":"昆虫类","habitat":"全球热带的森林","diet":"树叶","size":"体长10-30cm,体重5-30g","weight":"5-30g","length":"0.2m","status":"无危(LC)","emoji":"🪲","description":"伪装成树枝的隐身大师,静止时与树枝无异,是世界上体长最长的昆虫。","imagePrompt":"A photorealistic macro photograph of a stick insect (Phasmatodea) perfectly camouflaged as a twig on a tree branch, long slender green-brown body, legs aligned with branch, extreme camouflage, macro detail, National Geographic style"},
 {"name":"吉丁虫","englishName":"Jewel Beetle","scientificName":"Chrysochroa fulgidissima","category":"昆虫类","habitat":"东亚的森林","diet":"幼虫蛀木,成虫吃树液","size":"体长3-6cm,体重1-5g","weight":"1-5g","length":"0.045m","status":"无危(LC)","emoji":"🪲","description":"金属彩虹色的甲虫,壳上流光溢彩,被称为宝石甲虫,日本称玉虫。","imagePrompt":"A photorealistic macro photograph of a jewel beetle (Chrysochroa fulgidissima) with iridescent rainbow metallic shell on tree bark, green and gold colors shifting in light, macro detail, National Geographic style"},
 {"name":"家蚕","englishName":"Silkworm","scientificName":"Bombyx mori","category":"昆虫类","habitat":"中国起源,全球饲养","diet":"桑叶","size":"体长4-6cm,体重2-5g","weight":"2-5g","length":"0.05m","status":"无危(LC)","emoji":"🐛","description":"丝绸之路的起点,吐丝结茧已驯化5000年,蚕丝是中国的伟大发明。","imagePrompt":"A photorealistic macro photograph of silkworms (Bombyx mori) feeding on fresh mulberry leaves, white caterpillars, silk threads, traditional farming scene, soft natural light, National Geographic style"},
 {"name":"枯叶螳螂","englishName":"Dead Leaf Mantis","scientificName":"Deroplatys desiccata","category":"昆虫类","habitat":"东南亚的热带雨林","diet":"昆虫和小型动物","size":"体长6-9cm,体重3-10g","weight":"3-10g","length":"0.075m","status":"无危(LC)","emoji":"🦗","description":"伪装成枯叶的完美猎手,连叶脉和腐烂斑点都模仿,是拟态大师。","imagePrompt":"A photorealistic macro photograph of a dead leaf mantis (Deroplatys desiccata) camouflaged as a dried brown leaf on forest floor, body shaped like a leaf with veins, raptorial forelegs hidden, macro detail, National Geographic style"},
]

CRUSTACEANS = [
 {"name":"中华绒螯蟹","englishName":"Chinese Mitten Crab","scientificName":"Eriocheir sinensis","category":"甲壳类","habitat":"中国东部沿海和长江流域","diet":"鱼、虾、螺和水生植物","size":"壳宽5-10cm,体重0.1-0.5kg","weight":"0.1-0.5kg","length":"0.08m","status":"无危(LC)","emoji":"🦀","description":"大闸蟹,螯足上密布绒毛,秋风起蟹脚痒,阳澄湖大闸蟹是中国餐桌的贵族。","imagePrompt":"A photorealistic wildlife photograph of a Chinese mitten crab (Eriocheir sinensis) with hairy claws on a bamboo steamer with ginger, fresh water droplets, culinary scene, warm light, National Geographic style"},
 {"name":"帝王蟹","englishName":"Red King Crab","scientificName":"Paralithodes camtschaticus","category":"甲壳类","habitat":"北太平洋的寒冷深海","diet":"贝类、海星、鱼和藻类","size":"腿展开可达1.8m,体重5-10kg","weight":"5-10kg","length":"1.8m","status":"无危(LC)","emoji":"🦀","description":"阿拉斯加的红宝石,全身红色甲壳,腿长如帝王权杖,是深海捕捞的珍贵海鲜。","imagePrompt":"A photorealistic underwater photograph of a red king crab (Paralithodes camtschaticus) walking on rocky cold seabed, bright red armor, enormous long legs, deep cold water, dramatic lighting, National Geographic style"},
 {"name":"中华锦绣龙虾","englishName":"Chinese Spiny Lobster","scientificName":"Panulirus ornatus","category":"甲壳类","habitat":"中国南海和西太平洋的珊瑚礁","diet":"贝类、海胆和小型动物","size":"体长30-50cm,体重1-5kg","weight":"1-5kg","length":"0.4m","status":"无危(LC)","emoji":"🦞","description":"五彩斑斓的龙虾,蓝绿橙红的花纹,没有大螯却有长须,是海鲜中的奢侈品。","imagePrompt":"A photorealistic underwater photograph of a Chinese spiny lobster (Panulirus ornatus) with colorful blue-green-orange shell and long antennae on a coral reef, vivid colors, tropical water, National Geographic style"},
 {"name":"波士顿龙虾","englishName":"American Lobster","scientificName":"Homarus americanus","category":"甲壳类","habitat":"大西洋西北部的岩石海底","diet":"贝类、鱼、蟹和海胆","size":"体长20-60cm,体重0.5-7kg","weight":"0.5-7kg","length":"0.45m","status":"无危(LC)","emoji":"🦞","description":"北美大龙虾,墨绿色甲壳,一对巨大的螯,寿命可达100年,是西餐的招牌海鲜。","imagePrompt":"A photorealistic underwater photograph of an American lobster (Homarus americanus) with dark green shell and huge claws walking on rocky seabed, antennae raised, cold water, dramatic light, National Geographic style"},
 {"name":"虾蛄","englishName":"Mantis Shrimp","scientificName":"Odontodactylus scyllarus","category":"甲壳类","habitat":"印度洋和太平洋的珊瑚礁","diet":"蟹、贝类、鱼和螺","size":"体长15-30cm,体重0.1-0.5kg","weight":"0.1-0.5kg","length":"0.2m","status":"无危(LC)","emoji":"🦐","description":"皮皮虾,螳螂虾,前足如弹簧拳击,拳速可击碎玻璃,拥有世界上最复杂的眼睛。","imagePrompt":"A photorealistic underwater photograph of a peacock mantis shrimp (Odontodactylus scyllarus) with iridescent rainbow-colored shell on coral reef, raptorial claws folded, vivid colors, macro detail, National Geographic style"},
]

MOLLUSKS = [
 {"name":"章鱼","englishName":"Common Octopus","scientificName":"Octopus vulgaris","category":"软体类","habitat":"全球温带和热带海域的岩礁","diet":"蟹、虾、贝类和小鱼","size":"腕展可达1m,体重1-10kg","weight":"1-10kg","length":"1m","status":"无危(LC)","emoji":"🐙","description":"拥有三个心脏和蓝色血液,能瞬间变色拟态,会开瓶盖解谜题,海洋中的智者。","imagePrompt":"A photorealistic underwater photograph of a common octopus (Octopus vulgaris) with eight arms exploring a coral reef, reddish-brown color changing to blend with rocks, suction cups visible, tentacles spread, deep blue water, National Geographic style"},
 {"name":"蓝环章鱼","englishName":"Blue-ringed Octopus","scientificName":"Hapalochlaena lunulata","category":"软体类","habitat":"印度洋和西太平洋的潮间带","diet":"蟹、虾和小鱼","size":"体长10-20cm,体重0.01-0.1kg","weight":"10-100g","length":"0.15m","status":"无危(LC)","emoji":"🐙","description":"小巧可爱却剧毒无比,受惊时蓝色圆环闪烁,毒液可致人死亡,海洋的警告色。","imagePrompt":"A photorealistic underwater photograph of a blue-ringed octopus (Hapalochlaena lunulata) with glowing blue rings on yellow body, small size on coral rubble, warning colors bright, tide pool, macro detail, National Geographic style"},
 {"name":"大王乌贼","englishName":"Giant Squid","scientificName":"Architeuthis dux","category":"软体类","habitat":"全球深海","diet":"鱼和其他鱿鱼","size":"体长可达13m,体重可达275kg","weight":"可达275kg","length":"12m","status":"无危(LC)","emoji":"🐙","description":"深海巨兽,眼睛如餐盘大小,与抹香鲸的深海搏斗是海洋传说,2012年才首次拍摄到活体。","imagePrompt":"A photorealistic underwater photograph of a giant squid (Architeuthis dux) in the dark deep ocean, enormous body with huge eyes and long tentacles, bioluminescent glow, mysterious abyss atmosphere, National Geographic style"},
 {"name":"鹦鹉螺","englishName":"Chambered Nautilus","scientificName":"Nautilus pompilius","category":"软体类","habitat":"印度洋和西太平洋的珊瑚礁深海","diet":"腐肉、蟹和小鱼","size":"壳径15-25cm,体重0.5-2kg","weight":"0.5-2kg","length":"0.2m","status":"易危(VU)","emoji":"🐚","description":"螺旋壳里的活化石,已在地球生存5亿年,黄金分割比例的完美体现。","imagePrompt":"A photorealistic underwater photograph of a chambered nautilus (Nautilus pompilius) with a beautiful spiral shell swimming in deep blue water, cream and orange striped shell, many tentacles, deep sea atmosphere, National Geographic style"},
 {"name":"非洲大蜗牛","englishName":"Giant African Land Snail","scientificName":"Lissachatina fulica","category":"软体类","habitat":"非洲,已入侵全球热带地区","diet":"植物、果实,几乎什么都吃","size":"壳长10-20cm,体重0.1-0.5kg","weight":"0.1-0.5kg","length":"0.15m","status":"无危(LC)","emoji":"🐌","description":"世界上最大的陆生蜗牛,可长到20厘米,繁殖力惊人,是危险的入侵物种。","imagePrompt":"A photorealistic macro photograph of a giant African land snail (Lissachatina fulica) with large spiral brown shell crawling on a tropical leaf, long tentacles, glistening slime trail, macro detail, soft light, National Geographic style"},
]
