# -*- coding: utf-8 -*-
# 最终补充批次 43种 (batch8) - 补足1000种
FINAL = [
 # ===== 哺乳类 12 =====
 {"name":"白鲸","englishName":"Beluga Whale","scientificName":"Delphinapterus leucas","category":"哺乳类","habitat":"北极和亚北极海域","diet":"鱼、鱿鱼和甲壳类","size":"体长4-5.5m,体重700-1600kg","weight":"700-1600kg","length":"4.7m","status":"无危(LC)","emoji":"🐋","description":"海洋中的金丝雀,全身雪白,会发出悦耳的鸣叫,被称为北冰洋的微笑天使。","imagePrompt":"A photorealistic underwater photograph of a beluga whale (Delphinapterus leucas) with a pure white body surfacing in arctic waters, rounded forehead, gentle smile, ice floes in background, cold blue light, National Geographic style"},
 {"name":"独角鲸","englishName":"Narwhal","scientificName":"Monodon monoceros","category":"哺乳类","habitat":"北极海域","diet":"鱼、鱿鱼和虾","size":"体长4-5.5m,体重800-1600kg","weight":"800-1600kg","length":"4.5m","status":"无危(LC)","emoji":"🐋","description":"海洋独角兽,雄鲸的长牙可达3米,其实是特化的犬齿,神秘而优雅。","imagePrompt":"A photorealistic underwater photograph of a narwhal (Monodon monoceros) with a long spiral tusk swimming in icy arctic water, grey mottled body, ice chunks above, dramatic cold light, National Geographic style"},
 {"name":"儒艮","englishName":"Dugong","scientificName":"Dugong dugon","category":"哺乳类","habitat":"印度洋和西太平洋的温暖浅海","diet":"海草","size":"体长2.4-3.4m,体重230-500kg","weight":"230-500kg","length":"3m","status":"易危(VU)","emoji":"🦭","description":"美人鱼传说的原型,圆胖身材和铲状尾巴,温顺地啃食海草床。","imagePrompt":"A photorealistic underwater photograph of a dugong (Dugong dugon) grazing on seagrass in clear shallow tropical water, plump grey body, paddle tail, gentle eyes, sunbeams through turquoise water, National Geographic style"},
 {"name":"美洲河狸","englishName":"North American Beaver","scientificName":"Castor canadensis","category":"哺乳类","habitat":"北美的河流和湖泊","diet":"树皮、嫩枝和水生植物","size":"体长0.8-1.2m,体重15-30kg","weight":"15-30kg","length":"1m","status":"无危(LC)","emoji":"🦫","description":"动物界的工程师,用牙齿伐树筑坝,扁平的桨状尾是标志,会建造庞大的水坝。","imagePrompt":"A photorealistic wildlife photograph of a North American beaver (Castor canadensis) gnawing a tree trunk by a pond, flat paddle tail, glossy brown fur, wooden dam and lodge in background, golden evening light, National Geographic style"},
 {"name":"水豚","englishName":"Lesser Capybara","scientificName":"Hydrochoerus isthmius","category":"哺乳类","habitat":"南美洲的湿地","diet":"水生植物和草","size":"体长0.9-1.2m,体重25-40kg","weight":"25-40kg","length":"1.05m","status":"数据缺乏(DD)","emoji":"🦫","description":"小水豚,圆滚滚的身材泡在水里,温顺可爱,是动物界的社交明星。","imagePrompt":"A photorealistic wildlife photograph of a lesser capybara (Hydrochoerus isthmius) with a round reddish-brown body relaxing in a tropical wetland, peaceful expression, water plants, golden light, National Geographic style"},
 {"name":"树懒","englishName":"Two-toed Sloth","scientificName":"Choloepus didactylus","category":"哺乳类","habitat":"南美洲的热带雨林","diet":"树叶、嫩芽和果实","size":"体长50-70cm,体重4-8kg","weight":"4-8kg","length":"0.6m","status":"无危(LC)","emoji":"🦥","description":"世界上最慢的动物之一,前肢两趾,倒挂在树上悠闲度日,憨态可掬。","imagePrompt":"A photorealistic wildlife photograph of a two-toed sloth (Choloepus didactylus) hanging upside down from a rainforest branch, shaggy brown fur, relaxed sleepy face, lush green canopy, soft light, National Geographic style"},
 {"name":"小熊猫","englishName":"Red Panda","scientificName":"Ailurus fulgens","category":"哺乳类","habitat":"喜马拉雅山麓的竹林","diet":"竹子、果实和昆虫","size":"体长40-60cm,体重3-6kg","weight":"3-6kg","length":"0.5m","status":"濒危(EN)","emoji":"🦝","description":"红褐色的皮毛配蓬松大尾,像猫像熊又像浣熊,是竹林里最萌的精灵。","imagePrompt":"A photorealistic wildlife photograph of a red panda (Ailurus fulgens) with rust-red fur and a bushy ringed tail sitting on a mossy branch eating bamboo, adorable face, green bamboo forest, soft light, National Geographic style"},
 {"name":"藏狐","englishName":"Tibetan Fox","scientificName":"Vulpes ferrilata","category":"哺乳类","habitat":"青藏高原的高山草甸","diet":"鼠兔、旱獭和昆虫","size":"体长50-70cm,体重3-6kg","weight":"3-6kg","length":"0.6m","status":"无危(LC)","emoji":"🦊","description":"方脸大耳的狐狸,表情自带喜感,是高原上的表情包之王。","imagePrompt":"A photorealistic wildlife photograph of a Tibetan fox (Vulpes ferrilata) with a distinctive square face and bushy tail standing on a highland meadow, reddish-grey fur, snow mountains behind, golden light, National Geographic style"},
 {"name":"浣熊","englishName":"Crab-eating Raccoon","scientificName":"Procyon cancrivorus","category":"哺乳类","habitat":"中南美洲的湿地和森林","diet":"蟹、虾、果实和小动物","size":"体长40-60cm,体重3-8kg","weight":"3-8kg","length":"0.5m","status":"无危(LC)","emoji":"🦝","description":"爱吃螃蟹的浣熊,蒙面大盗的标志性面纹,前爪灵活会在水中摸蟹。","imagePrompt":"A photorealistic wildlife photograph of a crab-eating raccoon (Procyon cancrivorus) with bandit mask markings catching a crab in shallow water, grey fur with ringed tail, wetland background, soft light, National Geographic style"},
 {"name":"鲸鲨","englishName":"Whale Shark","scientificName":"Rhincodon typus","category":"鱼类","habitat":"全球热带暖水海域","diet":"浮游生物和磷虾(滤食)","size":"体长9-18m,体重9-20吨","weight":"9-20吨","length":"14m","status":"濒危(EN)","emoji":"🦈","description":"世界上最大的鱼,温顺的巨兽,身上繁星般的白色斑点独一无二。","imagePrompt":"A photorealistic underwater photograph of a whale shark (Rhincodon typus) with star-like white spots swimming in clear tropical water, enormous gentle giant, divers for scale, sunbeams, National Geographic style"},
 {"name":"大熊猫","englishName":"Giant Panda","scientificName":"Ailuropoda melanoleuca","category":"哺乳类","habitat":"中国四川、陕西、甘肃的山区竹林","diet":"以竹子为主(99%)","size":"体长1.2-1.8m,体重70-125kg","weight":"70-125kg","length":"1.5m","status":"易危(VU)","emoji":"🐼","description":"中国的国宝,黑白相间的毛色独具特色,憨态可掬,是世界自然基金会的标志。","imagePrompt":"A photorealistic wildlife photograph of a giant panda (Ailuropoda melanoleuca) sitting in a lush green bamboo forest, thick black and white fur, distinctive black eye patches, chewing bamboo, soft light, National Geographic style"},
 {"name":"长颈鹿","englishName":"Reticulated Giraffe","scientificName":"Giraffa reticulata","category":"哺乳类","habitat":"非洲东部的稀树草原","diet":"金合欢树叶","size":"身高4.5-5.5m,体重800-1200kg","weight":"800-1200kg","length":"5m","status":"易危(VU)","emoji":"🦒","description":"网纹长颈鹿,白色网格状斑纹如地图,是非洲草原最高的守望者。","imagePrompt":"A photorealistic wildlife photograph of a reticulated giraffe (Giraffa reticulata) with geometric net-like pattern stretching its long neck to eat acacia leaves, Kenyan savanna, golden light, National Geographic style"},
 # ===== 鸟类 10 =====
 {"name":"白腹锦鸡","englishName":"Lady Amherst's Pheasant","scientificName":"Chrysolophus amherstiae","category":"鸟类","habitat":"中国西南部的山地森林","diet":"植物种子、嫩芽和昆虫","size":"体长60-150cm(含尾),体重0.6-1kg","weight":"0.6-1kg","length":"1.1m","status":"无危(LC)","emoji":"🐦","description":"黑白色块相间的华丽雉鸡,超长白色尾羽,红蓝点缀,是中国特有种。","imagePrompt":"A photorealistic wildlife photograph of a Lady Amherst's pheasant (Chrysolophus amherstiae) male with black and white scalloped plumage and extremely long white tail feathers, red and blue accents, mountain forest, soft light, National Geographic style"},
 {"name":"丹顶鹤","englishName":"Red-crowned Crane","scientificName":"Grus japonensis","category":"鸟类","habitat":"中国东北和东亚的湿地","diet":"鱼、虾、昆虫和植物根茎","size":"体长120-160cm,翼展2.4m","weight":"7-10.5kg","length":"1.4m","status":"濒危(EN)","emoji":"🦢","description":"头顶鲜红冠羽,仙风道骨,是中国文化中的仙鹤,翩翩起舞时优雅绝伦。","imagePrompt":"A photorealistic wildlife photograph of a red-crowned crane (Grus japonensis) with a bright red crown patch dancing in a misty wetland, white body with black neck, wings spread, morning fog, National Geographic style"},
 {"name":"白鹭","englishName":"Cattle Egret","scientificName":"Bubulcus ibis","category":"鸟类","habitat":"全球温暖地区的湿地和牧场","diet":"昆虫、蛙和小鱼","size":"体长46-56cm,翼展0.88-0.96m","weight":"0.3-0.5kg","length":"0.5m","status":"无危(LC)","emoji":"🦢","description":"会跟着牛群吃虫的白鹭,繁殖期头胸变成橙黄色,是牧场的好帮手。","imagePrompt":"A photorealistic wildlife photograph of a cattle egret (Bubulcus ibis) perched on a cow's back in a green pasture, white plumage with orange breeding plumes, peaceful farm scene, soft light, National Geographic style"},
 {"name":"翠鸟","englishName":"Pied Kingfisher","scientificName":"Ceryle rudis","category":"鸟类","habitat":"非洲和亚洲的河流湖泊","diet":"小鱼和虾","size":"体长25cm,体重60-90g","weight":"60-90g","length":"0.25m","status":"无危(LC)","emoji":"🐦","description":"黑白斑点的翠鸟,能在空中悬停后俯冲捕鱼,是捕鱼高手。","imagePrompt":"A photorealistic wildlife photograph of a pied kingfisher (Ceryle rudis) hovering above river water with black and white plumage, diving pose, water splash, soft light, National Geographic style"},
 {"name":"红隼","englishName":"Common Kestrel","scientificName":"Falco tinnunculus","category":"鸟类","habitat":"欧亚大陆的田野和城市","diet":"鼠类、昆虫和小鸟","size":"体长30-36cm,翼展0.65-0.8m","weight":"0.15-0.3kg","length":"0.33m","status":"无危(LC)","emoji":"🦅","description":"会空中悬停的小猛禽,像直升机一样定在半空搜寻猎物,红棕色羽毛优雅。","imagePrompt":"A photorealistic wildlife photograph of a common kestrel (Falco tinnunculus) hovering in mid-air with wings fluttering, reddish-brown plumage with black spots, blue sky, hunting pose, National Geographic style"},
 {"name":"喜鹊","englishName":"Common Magpie","scientificName":"Pica pica","category":"鸟类","habitat":"欧亚大陆的城镇和乡村","diet":"昆虫、果实和种子","size":"体长44-46cm,体重0.2-0.3kg","weight":"0.2-0.3kg","length":"0.45m","status":"无危(LC)","emoji":"🐦","description":"黑白羽毛泛蓝绿光泽,中国传统文化中的报喜鸟,喜鹊登梅寓意吉祥。","imagePrompt":"A photorealistic wildlife photograph of a common magpie (Pica pica) perched on a plum blossom branch, black and white plumage with iridescent blue sheen, spring flowers, soft light, National Geographic style"},
 {"name":"火烈鸟","englishName":"Lesser Flamingo","scientificName":"Phoeniconaias minor","category":"鸟类","habitat":"非洲的咸水湖","diet":"蓝藻和浮游生物","size":"身高0.8-0.9m,体重1.2-2.7kg","weight":"1.2-2.7kg","length":"0.85m","status":"近危(NT)","emoji":"🦩","description":"最粉红的火烈鸟,上百万只聚在纳特龙湖,如粉色云霞,场面震撼。","imagePrompt":"A photorealistic wildlife photograph of lesser flamingos (Phoeniconaias minor) in a huge flock on a soda lake, vivid pink feathers, curved necks, water reflections, dramatic sunset, National Geographic style"},
 {"name":"鸵鸟","englishName":"Common Ostrich","scientificName":"Struthio camelus","category":"鸟类","habitat":"非洲的草原和荒漠","diet":"草、种子和果实","size":"身高2.1-2.8m,体重100-160kg","weight":"100-160kg","length":"2.4m","status":"无危(LC)","emoji":"🦩","description":"现存最大的鸟,不会飞但奔跑时速70公里,双腿强健能踢倒狮子。","imagePrompt":"A photorealistic wildlife photograph of a common ostrich (Struthio camelus) running across the African savanna, long powerful legs, black and white feathers, dust rising, golden light, National Geographic style"},
 {"name":"黑天鹅","englishName":"Black Swan","scientificName":"Cygnus atratus","category":"鸟类","habitat":"澳大利亚的湖泊和湿地","diet":"水生植物和小动物","size":"体长110-140cm,翼展1.6-2m","weight":"3.7-9kg","length":"1.2m","status":"无危(LC)","emoji":"🦢","description":"全身漆黑配鲜红鸟喙,展翅时露出白色飞羽,高贵而神秘。","imagePrompt":"A photorealistic wildlife photograph of a black swan (Cygnus atratus) with glossy black plumage and bright red beak gliding on a calm lake, white wing tips visible, water ripples, soft light, National Geographic style"},
 {"name":"帝企鹅","englishName":"Emperor Penguin","scientificName":"Aptenodytes forsteri","category":"鸟类","habitat":"南极洲的海冰","diet":"鱼、磷虾和鱿鱼","size":"身高1.1-1.3m,体重22-45kg","weight":"22-45kg","length":"1.2m","status":"近危(NT)","emoji":"🐧","description":"现存最大的企鹅,在南极严酷的冬天孵蛋,是伟大的父亲。","imagePrompt":"A photorealistic wildlife photograph of emperor penguins (Aptenodytes forsteri) huddled together on antarctic sea ice, black and white plumage with yellow ear patches, blizzard wind, cold blue light, National Geographic style"},
 # ===== 鱼类 8 =====
 {"name":"小丑鱼","englishName":"Ocellaris Clownfish","scientificName":"Amphiprion ocellaris","category":"鱼类","habitat":"印度洋和太平洋的珊瑚礁","diet":"藻类和小型甲壳类","size":"体长8-11cm,体重10-50g","weight":"10-50g","length":"0.1m","status":"无危(LC)","emoji":"🐠","description":"海底总动员尼莫的原型,橙白条纹,和海葵共生,是珊瑚礁的明星。","imagePrompt":"A photorealistic underwater photograph of ocellaris clownfish (Amphiprion ocellaris) with orange and white stripes swimming among colorful anemone tentacles, coral reef background, bright tropical water, National Geographic style"},
 {"name":"蓝吊","englishName":"Blue Tang","scientificName":"Paracanthurus hepatus","category":"鱼类","habitat":"印度洋和太平洋的珊瑚礁","diet":"藻类","size":"体长15-30cm,体重100-500g","weight":"100-500g","length":"0.25m","status":"无危(LC)","emoji":"🐠","description":"多莉的原型,宝蓝色身体配黑色花纹和黄色尾巴,是珊瑚礁的蓝宝石。","imagePrompt":"A photorealistic underwater photograph of blue tangs (Paracanthurus hepatus) with vivid royal blue bodies and yellow tails swimming over a coral reef, black pattern, bright tropical water, National Geographic style"},
 {"name":"金枪鱼","englishName":"Pacific Bluefin Tuna","scientificName":"Thunnus orientalis","category":"鱼类","habitat":"太平洋","diet":"鱼、鱿鱼和甲壳类","size":"体长2-3m,体重150-450kg","weight":"150-450kg","length":"2.5m","status":"近危(NT)","emoji":"🐟","description":"太平洋蓝鳍金枪鱼,海中法拉利,游泳时速可达70公里,是寿司的顶级食材。","imagePrompt":"A photorealistic underwater photograph of a Pacific bluefin tuna (Thunnus orientalis) swimming at high speed in deep blue ocean, torpedo-shaped metallic body, school in background, sunbeams, National Geographic style"},
 {"name":"海马","englishName":"Common Seahorse","scientificName":"Hippocampus kuda","category":"鱼类","habitat":"印度洋和西太平洋的海草床","diet":"小型甲壳类","size":"体长15-25cm,体重20-80g","weight":"20-80g","length":"0.18m","status":"易危(VU)","emoji":"🐴","description":"由雄性怀孕生子的奇鱼,头部像马,卷尾钩住海草,是海洋的温柔骑士。","imagePrompt":"A photorealistic underwater macro photograph of a common seahorse (Hippocampus kuda) with curled tail anchored to seagrass, horse-like head, golden-brown color, coral background, soft light, National Geographic style"},
 {"name":"翻车鱼","englishName":"Ocean Sunfish","scientificName":"Mola mola","category":"鱼类","habitat":"全球热带和温带海域","diet":"水母和小鱼","size":"体长可达3.3m,体重可达2.3吨","weight":"可达2.3吨","length":"3m","status":"易危(VU)","emoji":"🐟","description":"形状像被砍掉尾巴的鱼,是世界上最大的硬骨鱼,喜欢浮在海面晒太阳。","imagePrompt":"A photorealistic underwater photograph of an ocean sunfish (Mola mola) with its odd half-body shape swimming near the surface, huge grey body, tropical water, National Geographic style"},
 {"name":"石斑鱼","englishName":"Giant Grouper","scientificName":"Epinephelus lanceolatus","category":"鱼类","habitat":"印度洋和西太平洋的珊瑚礁","diet":"鱼、蟹和龙虾","size":"体长可达2.7m,体重可达400kg","weight":"可达400kg","length":"2.4m","status":"易危(VU)","emoji":"🐟","description":"石斑鱼之王,可长到400公斤,花纹如迷彩,是珊瑚礁上的巨无霸。","imagePrompt":"A photorealistic underwater photograph of a giant grouper (Epinephelus lanceolatus) with massive body and mottled camouflage pattern resting near a coral reef, huge mouth, dark water, National Geographic style"},
 {"name":"河豚","englishName":"Pufferfish","scientificName":"Takifugu rubripes","category":"鱼类","habitat":"西太平洋的沿海","diet":"贝类、甲壳类和藻类","size":"体长30-50cm,体重1-3kg","weight":"1-3kg","length":"0.4m","status":"无危(LC)","emoji":"🐡","description":"遇险时鼓起成球,体内毒素极强,经过专业处理是日本料理的顶级美味。","imagePrompt":"A photorealistic underwater photograph of a pufferfish (Takifugu rubripes) inflated into a round ball with spikes raised, spotted body, coral background, dramatic light, National Geographic style"},
 {"name":"金鱼","englishName":"Goldfish","scientificName":"Carassius auratus","category":"鱼类","habitat":"原产中国,全球人工饲养","diet":"植物、藻类和小型无脊椎动物","size":"体长10-30cm,体重0.1-1kg","weight":"0.1-1kg","length":"0.2m","status":"无危(LC)","emoji":"🐠","description":"从野生鲫鱼驯化而来,中国培育千年,是吉祥的象征,品种数百。","imagePrompt":"A photorealistic underwater photograph of an orange goldfish (Carassius auratus) with flowing fins swimming in a pond, bright orange scales, water plants, sunlight through water, National Geographic style"},
 # ===== 爬行类 5 =====
 {"name":"绿海龟","englishName":"Green Sea Turtle","scientificName":"Chelonia mydas","category":"爬行类","habitat":"全球热带和亚热带海域","diet":"海草和藻类","size":"体长0.8-1.4m,体重65-250kg","weight":"65-250kg","length":"1.1m","status":"濒危(EN)","emoji":"🐢","description":"背着厚重龟壳的海洋旅行家,会回到出生海滩产卵,是海洋的游牧者。","imagePrompt":"A photorealistic underwater photograph of a green sea turtle (Chelonia mydas) swimming over a coral reef, olive-green shell with patterns, graceful flippers, clear tropical water, sun rays, National Geographic style"},
 {"name":"扬子鳄","englishName":"Chinese Alligator","scientificName":"Alligator sinensis","category":"爬行类","habitat":"中国长江中下游的湿地","diet":"鱼、虾、螺和蛙","size":"体长1.5-2.1m,体重30-50kg","weight":"30-50kg","length":"1.8m","status":"极危(CR)","emoji":"🐊","description":"中国特有的淡水鳄,活化石,性情温顺,野外仅存百余条。","imagePrompt":"A photorealistic wildlife photograph of a Chinese alligator (Alligator sinensis) basking on a riverbank in a Chinese wetland, armored dark body, blunt snout, reeds, soft morning light, National Geographic style"},
 {"name":"变色龙","englishName":"Chameleon","scientificName":"Chamaeleo chamaeleon","category":"爬行类","habitat":"地中海沿岸的灌木","diet":"昆虫","size":"体长25-35cm,体重0.1-0.3kg","weight":"0.1-0.3kg","length":"0.3m","status":"无危(LC)","emoji":"🦎","description":"会变色的爬虫,眼睛可独立转动,舌头弹出速度惊人,是伪装大师。","imagePrompt":"A photorealistic wildlife photograph of a chameleon (Chamaeleo chamaeleon) with green body perched on a branch, independently rotating eyes, curled tail, Mediterranean scrubland, soft light, National Geographic style"},
 {"name":"眼镜蛇","englishName":"Indian Cobra","scientificName":"Naja naja","category":"爬行类","habitat":"南亚的森林和农田","diet":"鼠、蛙和鸟","size":"体长1.5-2.2m,体重1-3kg","weight":"1-3kg","length":"1.8m","status":"无危(LC)","emoji":"🐍","description":"颈部展开时露出眼镜状斑纹,印度玩蛇人的主角,被尊为神蛇。","imagePrompt":"A photorealistic wildlife photograph of an Indian cobra (Naja naja) with hood expanded showing spectacle markings, dark grey body, raised posture, dramatic light, National Geographic style"},
 {"name":"科摩多巨蜥","englishName":"Komodo Dragon","scientificName":"Varanus komodoensis","category":"爬行类","habitat":"印尼科摩多群岛","diet":"鹿、野猪和水牛","size":"体长2-3m,体重70-90kg","weight":"70-90kg","length":"2.6m","status":"濒危(EN)","emoji":"🦎","description":"现存最大的蜥蜴,口中带致命细菌和毒腺,咬一口等猎物中毒倒下。","imagePrompt":"A photorealistic wildlife photograph of a Komodo dragon (Varanus komodoensis) with forked tongue flicking on a volcanic island, massive muscular lizard, grey-brown armored skin, dramatic light, National Geographic style"},
 # ===== 两栖类 3 =====
 {"name":"牛蛙","englishName":"American Bullfrog","scientificName":"Lithobates catesbeianus","category":"两栖类","habitat":"原产北美,全球引进","diet":"昆虫、鱼、蛙、鼠","size":"体长10-20cm,体重0.2-1kg","weight":"0.2-1kg","length":"0.15m","status":"无危(LC)","emoji":"🐸","description":"叫声如牛吼的巨型青蛙,大鼓膜和贪吃的胃口,是世界入侵物种之一。","imagePrompt":"A photorealistic wildlife photograph of an American bullfrog (Lithobates catesbeianus) sitting in a pond, large green body with distinctive tympanum, water lilies, golden light, National Geographic style"},
 {"name":"箭毒蛙","englishName":"Green Poison Frog","scientificName":"Dendrobates auratus","category":"两栖类","habitat":"中南美洲的热带雨林","diet":"蚂蚁和甲虫","size":"体长3-4cm,体重2-5g","weight":"2-5g","length":"0.035m","status":"无危(LC)","emoji":"🐸","description":"翠绿和黑色相间的毒蛙,鲜艳的警示色,是雨林中的小毒王。","imagePrompt":"A photorealistic macro photograph of a green poison frog (Dendrobates auratus) perched on a rainforest leaf, emerald green and black pattern, tiny size, vivid colors, macro detail, National Geographic style"},
 {"name":"树蛙","englishName":"Japanese Tree Frog","scientificName":"Hyla japonica","category":"两栖类","habitat":"东亚的池塘和稻田","diet":"昆虫","size":"体长3-5cm,体重3-10g","weight":"3-10g","length":"0.04m","status":"无危(LC)","emoji":"🐸","description":"鲜绿色的树蛙,脚趾有吸盘能爬玻璃,雨后歌声最响亮。","imagePrompt":"A photorealistic macro photograph of a Japanese tree frog (Hyla japonica) perched on a green leaf, bright green body, suction toes, dew drops, soft light, National Geographic style"},
 # ===== 昆虫类 5 =====
 {"name":"长戟大兜虫","englishName":"Hercules Beetle","scientificName":"Dynastes hercules","category":"昆虫类","habitat":"中南美洲的热带雨林","diet":"树液和成熟果实","size":"体长4-17cm,体重20-100g","weight":"20-100g","length":"0.15m","status":"无危(LC)","emoji":"🪲","description":"世界上最长的甲虫,雄性有巨大犄角,能举起自身体重850倍的重物。","imagePrompt":"A photorealistic macro photograph of a Hercules beetle (Dynastes hercules) with enormous horns on a rainforest branch, glossy greenish-black armor, powerful pose, macro detail, National Geographic style"},
 {"name":"蓝闪蝶","englishName":"Blue Morpho Butterfly","scientificName":"Morpho peleides","category":"昆虫类","habitat":"中南美洲的热带雨林","diet":"腐烂果实和树液","size":"翼展10-15cm,体重1-3g","weight":"1-3g","length":"0.12m","status":"无危(LC)","emoji":"🦋","description":"翅膀闪耀着金属蓝光,如蓝色绸缎在林间飞舞,是雨林最美的宝石。","imagePrompt":"A photorealistic macro photograph of a blue morpho butterfly (Morpho peleides) with iridescent metallic blue wings spread on a rainforest leaf, vivid blue shimmer, dark background, National Geographic style"},
 {"name":"兰花螳螂","englishName":"Orchid Mantis","scientificName":"Hymenopus coronatus","category":"昆虫类","habitat":"东南亚的热带雨林","diet":"昆虫和小型动物","size":"体长4-7cm,体重2-6g","weight":"2-6g","length":"0.055m","status":"无危(LC)","emoji":"🦗","description":"伪装成兰花的螳螂,粉色花瓣般的身体,是自然界最惊艳的拟态大师。","imagePrompt":"A photorealistic macro photograph of an orchid mantis (Hymenopus coronatus) with pink petal-like body perched on an orchid flower, perfect camouflage, macro detail, soft light, National Geographic style"},
 {"name":"萤火虫","englishName":"Firefly","scientificName":"Luciola lateralis","category":"昆虫类","habitat":"东亚的湿地和稻田","diet":"幼虫吃蜗牛,成虫喝露水","size":"体长1-1.5cm,体重0.05-0.1g","weight":"0.05-0.1g","length":"0.012m","status":"近危(NT)","emoji":"✨","description":"夏夜里的童话之光,腹末发光器闪烁如流星,是环境良好的指示物种。","imagePrompt":"A photorealistic macro photograph of fireflies (Luciola lateralis) glowing in a summer meadow at night, tiny yellow-green lights in darkness, magical atmosphere, National Geographic style"},
 {"name":"帝王蝶","englishName":"Monarch Butterfly","scientificName":"Danaus plexippus","category":"昆虫类","habitat":"北美洲,迁徙至墨西哥越冬","diet":"幼虫吃马利筋,成虫吸花蜜","size":"翼展8-10cm,体重0.3-0.5g","weight":"0.3-0.5g","length":"0.09m","status":"无危(LC)","emoji":"🦋","description":"橙黑相间的王者之蝶,每年数百万只迁徙4000公里,是迁徙奇迹。","imagePrompt":"A photorealistic macro photograph of monarch butterflies (Danaus plexippus) with orange and black wings clustered on a tree branch, thousands of butterflies, forest background, soft light, National Geographic style"},
]
