# -*- coding: utf-8 -*-
"""生成40种新增昆虫数据 → new_insects.json(覆盖写入)"""
import json, os, sys

INSECTS = [
    {
        "name": "斐豹蛱蝶",
        "englishName": "Indian Fritillary",
        "scientificName": "Argyreus hyperbius",
        "category": "昆虫类",
        "habitat": "中国各地山地林缘、草坡及农田边",
        "diet": "幼虫取食堇菜科植物,成虫吸食花蜜",
        "size": "翅展约5-7厘米",
        "weight": "约0.5克",
        "length": 0.025,
        "status": "无危(LC)",
        "emoji": "🦋",
        "description": "橙黄色翅面布满黑色豹纹斑点,是蛱蝶科常见的大型蝴蝶,雄蝶喜在阳光下追逐飞舞,幼虫以堇菜等植物为食,我国南北均有分布。",
        "imagePrompt": "A photorealistic macro photograph of a Indian Fritillary (Argyreus hyperbius), orange wings covered with black leopard-like spots, resting on a violet flower, delicate wing scales visible, soft natural light, National Geographic style."
    },
    {
        "name": "鹤顶粉蝶",
        "englishName": "Great Orange-tip",
        "scientificName": "Hebomoia glaucippe",
        "category": "昆虫类",
        "habitat": "华南及东南亚低山丘陵、林缘地带",
        "diet": "幼虫取食白花菜科植物,成虫访花吸蜜",
        "size": "翅展约8-10厘米",
        "weight": "约0.6克",
        "length": 0.03,
        "status": "无危(LC)",
        "emoji": "🦋",
        "description": "前翅顶端有醒目的橙红色大斑,如同仙鹤头顶,是粉蝶科中体型最大的种类之一,飞行迅速敏捷,常见于华南山地林缘访花吸蜜。",
        "imagePrompt": "A photorealistic macro photograph of a Great Orange-tip (Hebomoia glaucippe), creamy white wings with brilliant orange-red tips, perched on a branch in a tropical forest, sharp detail, National Geographic style."
    },
    {
        "name": "鬼脸天蛾",
        "englishName": "Lesser Death's-head Hawkmoth",
        "scientificName": "Acherontia lachesis",
        "category": "昆虫类",
        "habitat": "中国南方及东南亚的林地、果园",
        "diet": "幼虫取食茄科等植物,成虫吸食花蜜和树汁",
        "size": "翅展约10-13厘米",
        "weight": "约2克",
        "length": 0.05,
        "status": "无危(LC)",
        "emoji": "🦋",
        "description": "前胸背板有骷髅状斑纹故得名,飞行时悬停吸蜜如同蜂鸟,幼虫粗壮末端有尾角,取食茄科植物,是著名的夜行性大型天蛾。",
        "imagePrompt": "A photorealistic macro photograph of a Lesser Death's-head Hawkmoth (Acherontia lachesis), large hawk moth with skull-like marking on thorax, spread wings showing intricate brown patterns, hovering at dusk, National Geographic style."
    },
    {
        "name": "桃红颈天牛",
        "englishName": "Red-necked Longhorn Beetle",
        "scientificName": "Aromia bungii",
        "category": "昆虫类",
        "habitat": "中国各地桃、李、梅等果园及阔叶林",
        "diet": "幼虫蛀食树干木质部,成虫啃食树皮嫩枝",
        "size": "体长约2.8-3.5厘米",
        "weight": "1-2克",
        "length": 0.03,
        "status": "无危(LC)",
        "emoji": "🪲",
        "description": "鞘翅漆黑发亮,前胸背板呈桃红色,是桃李等果树的重要钻蛀性害虫,幼虫在树干内蛀食两三年,成虫夏季在枝干上活动。",
        "imagePrompt": "A photorealistic macro photograph of a Red-necked Longhorn Beetle (Aromia bungii), glossy black wing covers and brilliant ruby-red neck, very long segmented antennae, clinging to a peach tree trunk, National Geographic style."
    },
    {
        "name": "黄边胡蜂",
        "englishName": "European Hornet",
        "scientificName": "Vespa crabro",
        "category": "昆虫类",
        "habitat": "中国北方及欧洲的林地、村落屋檐下",
        "diet": "捕食昆虫,也取食树汁和成熟果实",
        "size": "体长约2-3.5厘米",
        "weight": "约1克",
        "length": 0.025,
        "status": "无危(LC)",
        "emoji": "🐝",
        "description": "欧洲最大的胡蜂,体黄黑相间,腹部有黄边,肉食性,捕食多种昆虫,巢筑于树洞或屋檐下,蜇人疼痛剧烈,是社会性蜂类。",
        "imagePrompt": "A photorealistic macro photograph of a European Hornet (Vespa crabro), large yellow and black wasp with reddish-brown markings, resting on tree bark, fierce faceted eyes, National Geographic style."
    },
    {
        "name": "墨西哥蜜蚁",
        "englishName": "Honeypot Ant",
        "scientificName": "Myrmecocystus mexicanus",
        "category": "昆虫类",
        "habitat": "北美和墨西哥的沙漠及半干旱地带",
        "diet": "采集花蜜和蜜露,储存于工蚁腹部",
        "size": "工蚁体长0.5-0.8厘米,蜜罐蚁可达1厘米",
        "weight": "蜜罐蚁约0.1克",
        "length": 0.006,
        "status": "无危(LC)",
        "emoji": "🐜",
        "description": "巢内有一类专职储存食物的蜜罐蚁,腹部被花蜜撑成半透明琥珀色圆球,倒挂在蚁巢顶部,干旱时节供全巢取用,十分神奇。",
        "imagePrompt": "A photorealistic macro photograph of a Honeypot Ant (Myrmecocystus mexicanus), amber translucent swollen abdomen storing nectar, hanging in underground nest chamber, extreme macro detail, National Geographic style."
    },
    {
        "name": "刺花螳螂",
        "englishName": "Spiny Flower Mantis",
        "scientificName": "Pseudocreobotra wahlbergii",
        "category": "昆虫类",
        "habitat": "非洲南部的灌木丛和花丛中",
        "diet": "伏击捕食蜜蜂、蝴蝶等访花昆虫",
        "size": "体长约3-4厘米",
        "weight": "约1克",
        "length": 0.035,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "酷似一朵盛开的兰花,体表生有棘刺,腿节宽扁如花瓣,体色随花朵变化,静伏花间伏击访花昆虫,是昆虫界的伪装大师。",
        "imagePrompt": "A photorealistic macro photograph of a Spiny Flower Mantis (Pseudocreobotra wahlbergii), white and green mantis with spiky body mimicking an orchid flower, perched on a pink bloom, National Geographic style."
    },
    {
        "name": "蓝豆娘",
        "englishName": "Beautiful Demoiselle",
        "scientificName": "Calopteryx virgo",
        "category": "昆虫类",
        "habitat": "欧洲及亚洲的清澈溪流沿岸",
        "diet": "捕食蚊、蝇等小型飞行昆虫",
        "size": "体长约4-4.5厘米",
        "weight": "约0.3克",
        "length": 0.04,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "雄性通体泛金属蓝紫色光泽,停歇时四翅合拢竖立,与蜻蜓明显不同,飞行缓慢优雅,常沿清澈溪流低飞,是溪流的美丽精灵。",
        "imagePrompt": "A photorealistic macro photograph of a Beautiful Demoiselle (Calopteryx virgo), iridescent metallic blue damselfly with translucent wings held together, resting on a streamside leaf, National Geographic style."
    },
    {
        "name": "食虫虻",
        "englishName": "Robber Fly",
        "scientificName": "Promachus yesonicus",
        "category": "昆虫类",
        "habitat": "中国及东亚的草原、林缘和农田",
        "diet": "在空中捕食蜜蜂、甲虫、蝗虫等昆虫",
        "size": "体长约2-4厘米",
        "weight": "0.1-0.3克",
        "length": 0.03,
        "status": "无危(LC)",
        "emoji": "🪰",
        "description": "大型捕食性蝇类,复眼巨大,口器尖锐如针,常在枝头居高临下,突袭拦截飞行中的蜜蜂和甲虫,飞行迅猛,堪称蝇中猛禽。",
        "imagePrompt": "A photorealistic macro photograph of a Robber Fly (Promachus yesonicus), large predatory fly with huge compound eyes and bristly body, gripping a captured insect on a twig, National Geographic style."
    },
    {
        "name": "大蚊",
        "englishName": "Crane Fly",
        "scientificName": "Tipula oleracea",
        "category": "昆虫类",
        "habitat": "水边湿地、草丛及农田",
        "diet": "幼虫取食植物根茎,成虫不取食或吸食露水",
        "size": "体长约1-2.5厘米",
        "weight": "约0.05克",
        "length": 0.02,
        "status": "无危(LC)",
        "emoji": "🦟",
        "description": "外形像巨大的蚊子但绝不吸血,六条腿细长易断,飞行笨拙,常在草丛中静止悬挂,幼虫生活于潮湿土壤或水中,是常见昆虫。",
        "imagePrompt": "A photorealistic macro photograph of a Crane Fly (Tipula oleracea), slender body with extremely long delicate legs and narrow wings, resting on a green leaf, National Geographic style."
    },
    {
        "name": "麻蝇",
        "englishName": "Flesh Fly",
        "scientificName": "Sarcophaga carnaria",
        "category": "昆虫类",
        "habitat": "全球广布,常见于腐肉、垃圾和粪便处",
        "diet": "幼虫腐食性,取食腐肉和有机物",
        "size": "体长约0.8-1.4厘米",
        "weight": "约0.05克",
        "length": 0.01,
        "status": "无危(LC)",
        "emoji": "🪰",
        "description": "体灰黑色带棋盘状斑纹,腹部有银色闪光,卵胎生直接产下幼虫,幼虫在腐肉中取食发育,是法医推断死亡时间的重要指示昆虫。",
        "imagePrompt": "A photorealistic macro photograph of a Flesh Fly (Sarcophaga carnaria), grey checkered body with silvery metallic abdomen and large red eyes, resting on a wooden surface, National Geographic style."
    },
    {
        "name": "牛虻",
        "englishName": "Horse-fly",
        "scientificName": "Tabanus bovinus",
        "category": "昆虫类",
        "habitat": "牧场、水边及林间草地",
        "diet": "雌虫吸食牛马等动物血液,雄虫吸食花蜜",
        "size": "体长约2-2.5厘米",
        "weight": "0.1-0.2克",
        "length": 0.02,
        "status": "无危(LC)",
        "emoji": "🪰",
        "description": "体粗壮,复眼大而色彩鲜艳,雌虫口器如利刃割开皮肤吸血,牛马等家畜深受其害,雄虫只吸食花蜜,飞行时发出响亮嗡嗡声。",
        "imagePrompt": "A photorealistic macro photograph of a Horse-fly (Tabanus bovinus), stout fly with large iridescent compound eyes and brown banded abdomen, perched on a cattle farm fence, National Geographic style."
    },
    {
        "name": "丽蝇",
        "englishName": "Bluebottle Fly",
        "scientificName": "Calliphora vomitoria",
        "category": "昆虫类",
        "habitat": "全球广布,常见于腐肉、垃圾堆附近",
        "diet": "幼虫腐食性,成虫取食腐液和花蜜",
        "size": "体长约1-1.3厘米",
        "weight": "约0.06克",
        "length": 0.011,
        "status": "无危(LC)",
        "emoji": "🪰",
        "description": "体金属蓝色并带紫色光泽,对腐肉气味极为敏感,可飞行数公里前来产卵,幼虫在腐肉中发育,是法医昆虫学的关键研究对象。",
        "imagePrompt": "A photorealistic macro photograph of a Bluebottle Fly (Calliphora vomitoria), shiny metallic blue body with large red compound eyes, resting on a weathered log, National Geographic style."
    },
    {
        "name": "露螽",
        "englishName": "Sickle-bearing Bush-cricket",
        "scientificName": "Phaneroptera falcata",
        "category": "昆虫类",
        "habitat": "中国及欧洲的草丛、灌丛和林缘",
        "diet": "取食植物叶片,也捕食小虫",
        "size": "体长约2-3.5厘米",
        "weight": "0.5-1克",
        "length": 0.028,
        "status": "无危(LC)",
        "emoji": "🦗",
        "description": "通体翠绿如同嫩叶,前翅细长,触角长度超过身体,栖息于草丛灌丛中,雄虫夜晚鸣叫求偶,是螽斯家族中常见的绿色种类。",
        "imagePrompt": "A photorealistic macro photograph of a Sickle-bearing Bush-cricket (Phaneroptera falcata), bright green katydid with long threadlike antennae and leaf-like wings, perched on grass, National Geographic style."
    },
    {
        "name": "双斑蟋",
        "englishName": "Two-spotted Cricket",
        "scientificName": "Gryllus bimaculatus",
        "category": "昆虫类",
        "habitat": "中国及东南亚的田野、荒地石缝中",
        "diet": "杂食性,取食植物茎叶和小虫",
        "size": "体长约2-2.6厘米",
        "weight": "0.3-0.6克",
        "length": 0.023,
        "status": "无危(LC)",
        "emoji": "🦗",
        "description": "体黑褐色,前翅基部有两个黄白色大斑,后足发达善跳跃,雄虫昼夜鸣叫,是生物学实验的常用模式昆虫,也常作鸣虫饲养。",
        "imagePrompt": "A photorealistic macro photograph of a Two-spotted Cricket (Gryllus bimaculatus), glossy black cricket with two yellow spots at wing base and long antennae, on sandy ground, National Geographic style."
    },
    {
        "name": "东方蝼蛄",
        "englishName": "Oriental Mole Cricket",
        "scientificName": "Gryllotalpa orientalis",
        "category": "昆虫类",
        "habitat": "中国各地农田、菜园和潮湿疏松土壤",
        "diet": "啃食植物根茎,兼食土壤中小虫",
        "size": "体长约3-4厘米",
        "weight": "1-2克",
        "length": 0.035,
        "status": "无危(LC)",
        "emoji": "🦗",
        "description": "前足特化为铲状开掘足,在地下掘出隧道,昼伏夜出,啃食庄稼根茎,是农田重要地下害虫,雄虫在洞中发出低沉连绵的鸣声。",
        "imagePrompt": "A photorealistic macro photograph of a Oriental Mole Cricket (Gryllotalpa orientalis), brown burrowing cricket with shovel-like front legs and velvet body, emerging from soil, National Geographic style."
    },
    {
        "name": "云斑车蝗",
        "englishName": "Marbled Grasshopper",
        "scientificName": "Gastrimargus marmoratus",
        "category": "昆虫类",
        "habitat": "中国及东亚的草地、山坡和农田",
        "diet": "取食禾本科等植物的叶片",
        "size": "体长约4-6厘米",
        "weight": "2-4克",
        "length": 0.05,
        "status": "无危(LC)",
        "emoji": "🦗",
        "description": "大型蝗虫,前翅具云状暗色斑纹,后翅基部黄色带黑色宽带,飞行时色彩鲜明,常见于草地农田,取食禾本科植物,属植食性害虫。",
        "imagePrompt": "A photorealistic macro photograph of a Marbled Grasshopper (Gastrimargus marmoratus), large grasshopper with cloud-patterned brown wings and bright yellow hind wings, on grassland, National Geographic style."
    },
    {
        "name": "灶马",
        "englishName": "Camel Cricket",
        "scientificName": "Diestrammena japonica",
        "category": "昆虫类",
        "habitat": "厨房灶台、地下室等潮湿阴暗角落",
        "diet": "杂食性,取食残渣、霉菌和小虫",
        "size": "体长约2-3厘米",
        "weight": "0.5-1克",
        "length": 0.025,
        "status": "无危(LC)",
        "emoji": "🦗",
        "description": "又称灶蟋,背部隆起如驼峰,触角极长,无翅不善跳跃,常栖息于厨房灶台和潮湿角落,夜晚出来觅食,是常见的家居昆虫。",
        "imagePrompt": "A photorealistic macro photograph of a Camel Cricket (Diestrammena japonica), humpbacked wingless cricket with extremely long antennae, in a dim corner near a stove, National Geographic style."
    },
    {
        "name": "稻绿蝽",
        "englishName": "Southern Green Stink Bug",
        "scientificName": "Nezara viridula",
        "category": "昆虫类",
        "habitat": "中国及全球热带亚热带稻田和菜地",
        "diet": "刺吸水稻、豆类等作物汁液",
        "size": "体长约1.2-1.6厘米",
        "weight": "约0.1克",
        "length": 0.014,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "通体鲜绿色,盾片宽大,是水稻等作物的重要害虫,成若虫群集刺吸稻穗和茎叶汁液,受惊时释放刺鼻臭气,俗称臭屁虫。",
        "imagePrompt": "A photorealistic macro photograph of a Southern Green Stink Bug (Nezara viridula), shield-shaped bright green bug with piercing mouthpart, on a rice panicle, National Geographic style."
    },
    {
        "name": "黄足猎蝽",
        "englishName": "Yellow-legged Assassin Bug",
        "scientificName": "Sirthenea flavipes",
        "category": "昆虫类",
        "habitat": "中国南方稻田、草丛和灌木丛",
        "diet": "捕食毛虫、叶蝉等害虫",
        "size": "体长约1.5-2厘米",
        "weight": "约0.15克",
        "length": 0.017,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "体黑色,足黄褐色,口器短而弯,能刺吸猎物体液,专门捕食毛虫等农田害虫,是重要益虫,捕猎动作迅猛,被蜇有刺痛感。",
        "imagePrompt": "A photorealistic macro photograph of a Yellow-legged Assassin Bug (Sirthenea flavipes), black bug with yellow legs and curved beak, stalking prey on a leaf, National Geographic style."
    },
    {
        "name": "吹绵蚧",
        "englishName": "Cottony Cushion Scale",
        "scientificName": "Icerya purchasi",
        "category": "昆虫类",
        "habitat": "柑橘等果树的枝干和叶片上",
        "diet": "刺吸树木汁液",
        "size": "雌虫体长约0.5-0.8厘米",
        "weight": "不足0.01克",
        "length": 0.006,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "雌虫体表被白色蜡质绵絮状物覆盖,成群吸食柑橘等树木汁液,曾是著名检疫害虫,后引入澳洲瓢虫成功生物防治,成为经典案例。",
        "imagePrompt": "A photorealistic macro photograph of a Cottony Cushion Scale (Icerya purchasi), female scale insect covered in white waxy cotton-like filaments, on a citrus branch, National Geographic style."
    },
    {
        "name": "中华高冠角蝉",
        "englishName": "Chinese Treehopper",
        "scientificName": "Hypsauchenia chinensis",
        "category": "昆虫类",
        "habitat": "中国南方山地的树林和灌木上",
        "diet": "刺吸植物嫩枝汁液",
        "size": "体长约0.8-1厘米",
        "weight": "不足0.01克",
        "length": 0.009,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "前胸背板高高隆起如同头戴高冠,形态奇特仿佛小恐龙,静伏枝头极难被发现,以刺吸式口器取食植物汁液,是角蝉家族代表。",
        "imagePrompt": "A photorealistic macro photograph of a Chinese Treehopper (Hypsauchenia chinensis), bizarre treehopper with tall helmet-like pronotum and thorn-like projection, on a twig, National Geographic style."
    },
    {
        "name": "龙眼鸡",
        "englishName": "Litchi Lantern Bug",
        "scientificName": "Pyrops candelaria",
        "category": "昆虫类",
        "habitat": "华南及东南亚的龙眼、荔枝园",
        "diet": "刺吸龙眼、荔枝等树木汁液",
        "size": "体长约4-5厘米(含头突)",
        "weight": "0.3-0.5克",
        "length": 0.045,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "体色艳丽,头部向前伸出细长的吻突形似鸡嘴,翅面有黄绿花纹,吸食龙眼荔枝汁液,飞行缓慢,色彩华丽,极具观赏性。",
        "imagePrompt": "A photorealistic macro photograph of a Litchi Lantern Bug (Pyrops candelaria), colorful lantern bug with long curved snout and patterned green-yellow wings, on a lychee branch, National Geographic style."
    },
    {
        "name": "柑橘木虱",
        "englishName": "Asian Citrus Psyllid",
        "scientificName": "Diaphorina citri",
        "category": "昆虫类",
        "habitat": "柑橘产区的新梢嫩芽上",
        "diet": "刺吸柑橘嫩芽汁液",
        "size": "体长约0.3厘米",
        "weight": "不足0.001克",
        "length": 0.003,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "体极小,灰褐色,翅上有褐色斑纹,是柑橘黄龙病的传播媒介,危害极大,若虫分泌白色蜡丝,防治木虱是保护柑橘产业的关键。",
        "imagePrompt": "A photorealistic macro photograph of a Asian Citrus Psyllid (Diaphorina citri), tiny grey-brown psyllid with mottled wings and aphid-like body, on citrus shoot, extreme macro, National Geographic style."
    },
    {
        "name": "姬蜂",
        "englishName": "Ichneumon Wasp",
        "scientificName": "Ichneumon sarcitorius",
        "category": "昆虫类",
        "habitat": "林地、草地和农田边,寄主为鳞翅目幼虫",
        "diet": "幼虫寄生毛虫等寄主体内,成虫吸食花蜜",
        "size": "体长约1.5-3厘米",
        "weight": "0.1-0.3克",
        "length": 0.02,
        "status": "无危(LC)",
        "emoji": "🐝",
        "description": "体细长,腹部柄状,产卵管长如细针,将卵产入毛虫体内,幼虫在寄主体内寄生取食,是抑制农林害虫的重要天敌昆虫。",
        "imagePrompt": "A photorealistic macro photograph of a Ichneumon Wasp (Ichneumon sarcitorius), slender black and yellow wasp with long thin ovipositor and stalked abdomen, on a leaf, National Geographic style."
    },
    {
        "name": "蛛蜂",
        "englishName": "Spider Wasp",
        "scientificName": "Anoplius viaticus",
        "category": "昆虫类",
        "habitat": "林缘、草地和墙壁缝隙,常见于地面",
        "diet": "成蜂捕食蜘蛛,幼虫以麻痹的蜘蛛为食",
        "size": "体长约1-2厘米",
        "weight": "0.1-0.2克",
        "length": 0.015,
        "status": "无危(LC)",
        "emoji": "🐝",
        "description": "体黑色带蓝紫色光泽,足细长有棘刺,会蜇麻醉蜘蛛并拖入土中巢穴供幼虫食用,常低飞搜索地面,是蜘蛛的主要天敌。",
        "imagePrompt": "A photorealistic macro photograph of a Spider Wasp (Anoplius viaticus), black wasp with iridescent blue sheen and long spiny legs, dragging a paralyzed spider across the ground, National Geographic style."
    },
    {
        "name": "青蜂",
        "englishName": "Cuckoo Wasp",
        "scientificName": "Chrysis ignita",
        "category": "昆虫类",
        "habitat": "向阳的墙壁、朽木和沙质地面附近",
        "diet": "幼虫寄生于其他蜂类巢中,成虫访花",
        "size": "体长约0.6-1.2厘米",
        "weight": "不足0.05克",
        "length": 0.009,
        "status": "无危(LC)",
        "emoji": "🐝",
        "description": "体表具蓝绿紫红相间的金属光泽,如宝石般艳丽,幼虫寄居其他蜂类巢中偷食其幼虫,受惊时蜷缩成球假死,人称宝石蜂。",
        "imagePrompt": "A photorealistic macro photograph of a Cuckoo Wasp (Chrysis ignita), jewel-like metallic green and blue wasp with sculptured abdomen, resting on sunlit wood, National Geographic style."
    },
    {
        "name": "蠼螋",
        "englishName": "European Earwig",
        "scientificName": "Forficula auricularia",
        "category": "昆虫类",
        "habitat": "石块下、树皮下等潮湿阴暗处",
        "diet": "杂食性,捕食小虫也啃食植物",
        "size": "体长约1.2-2厘米",
        "weight": "0.1-0.3克",
        "length": 0.016,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "腹部末端长有一对钳状尾铗,常高高翘起,昼伏夜出,喜潮湿阴暗处,杂食性,既捕食小虫也啃食植物,是常见隐蔽性昆虫。",
        "imagePrompt": "A photorealistic macro photograph of a European Earwig (Forficula auricularia), dark brown insect with curved pincers at abdomen tip, under a damp stone, National Geographic style."
    },
    {
        "name": "衣鱼",
        "englishName": "Silverfish",
        "scientificName": "Lepisma saccharina",
        "category": "昆虫类",
        "habitat": "书柜、衣柜和潮湿的居室角落",
        "diet": "取食纸张、衣物、淀粉和糖类物质",
        "size": "体长约0.8-1.2厘米",
        "weight": "不足0.1克",
        "length": 0.01,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "银灰色,体表密覆细鳞片,行动迅速,夜行性,喜食含糖和淀粉的纸张衣物,常出没于书柜衣柜,是典型的家居储藏物害虫。",
        "imagePrompt": "A photorealistic macro photograph of a Silverfish (Lepisma saccharina), silvery grey wingless insect with three tail filaments and scaled body, on old paper, National Geographic style."
    },
    {
        "name": "蝎蛉",
        "englishName": "Common Scorpionfly",
        "scientificName": "Panorpa communis",
        "category": "昆虫类",
        "habitat": "潮湿林下、溪边灌丛和草丛",
        "diet": "腐食性,取食死虫和腐烂果实",
        "size": "体长约1.5-2.5厘米",
        "weight": "0.1-0.2克",
        "length": 0.02,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "雄虫腹部末端膨大上翘如蝎尾但无毒刺,头部喙状延长,翅面有黑色斑纹,栖息于潮湿林下,以死虫和腐殖质为食,不伤人。",
        "imagePrompt": "A photorealistic macro photograph of a Common Scorpionfly (Panorpa communis), male scorpionfly with upturned tail and elongated beak-like head, spotted wings, on forest floor leaf litter, National Geographic style."
    },
    {
        "name": "人蚤",
        "englishName": "Human Flea",
        "scientificName": "Pulex irritans",
        "category": "昆虫类",
        "habitat": "全球广布,寄生于人和家畜体表",
        "diet": "吸食人和动物血液",
        "size": "体长约0.2-0.35厘米",
        "weight": "不足0.001克",
        "length": 0.003,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "体侧扁,后足极发达,跳跃力惊人,可跳出自身身高数百倍的距离,吸食人和动物血液,历史上曾传播鼠疫,危害巨大。",
        "imagePrompt": "A photorealistic macro photograph of a Human Flea (Pulex irritans), tiny laterally flattened brown flea with powerful jumping legs and bristles, extreme macro on fabric, National Geographic style."
    },
    {
        "name": "体虱",
        "englishName": "Human Louse",
        "scientificName": "Pediculus humanus",
        "category": "昆虫类",
        "habitat": "寄生人体,藏匿于内衣缝和床褥",
        "diet": "吸食人血",
        "size": "体长约0.3-0.5厘米",
        "weight": "不足0.001克",
        "length": 0.004,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "灰白色小型无翅昆虫,寄生于人体藏于衣缝,吸食人血引起瘙痒,可传播斑疹伤寒等疾病,讲究个人卫生即可有效防除。",
        "imagePrompt": "A photorealistic macro photograph of a Human Louse (Pediculus humanus), greyish-white wingless louse with clawed legs clinging to fabric thread, extreme macro, National Geographic style."
    },
    {
        "name": "花蓟马",
        "englishName": "Flower Thrips",
        "scientificName": "Frankliniella intonsa",
        "category": "昆虫类",
        "habitat": "各种开花作物的花朵和嫩梢上",
        "diet": "锉吸花朵和嫩叶汁液",
        "size": "体长约0.1-0.15厘米",
        "weight": "不足0.001克",
        "length": 0.001,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "体极小,细长如线,翅狭长周缘有缨毛,锉吸式口器刮吸花朵和嫩叶汁液,为害多种作物,还能传播植物病毒,发生量很大。",
        "imagePrompt": "A photorealistic macro photograph of a Flower Thrips (Frankliniella intonsa), tiny slender thrips with fringed wings inside a flower blossom, extreme macro, National Geographic style."
    },
    {
        "name": "石蝇",
        "englishName": "Stonefly",
        "scientificName": "Perla marginata",
        "category": "昆虫类",
        "habitat": "清澈溪流、山涧的石块和岸边",
        "diet": "稚虫捕食水中昆虫,成虫不取食",
        "size": "体长约1.5-3厘米",
        "weight": "0.1-0.3克",
        "length": 0.022,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "体扁平柔软,翅平叠在背上,稚虫只生活在清澈溪流的石下,对水质要求极高,是水质监测的指示生物,成虫常栖于水边石上。",
        "imagePrompt": "A photorealistic macro photograph of a Stonefly (Perla marginata), flattened grey insect with long antennae and veined wings folded flat, resting on a wet river stone, National Geographic style."
    },
    {
        "name": "蝶角蛉",
        "englishName": "Owlfly",
        "scientificName": "Ascalaphus macaronius",
        "category": "昆虫类",
        "habitat": "林缘、草地的低矮灌丛上",
        "diet": "成虫捕食小虫,幼虫在土中伏击猎物",
        "size": "体长约3-4厘米",
        "weight": "0.2-0.4克",
        "length": 0.035,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "外形似蜻蜓又似蝴蝶,触角末端膨大成棒状,翅面有黑白花纹,成虫白天捕食小虫,幼虫在土中伏击猎物,是脉翅目大型昆虫。",
        "imagePrompt": "A photorealistic macro photograph of a Owlfly (Ascalaphus macaronius), dragonfly-like insect with clubbed antennae and patterned black-white wings, perched on a twig, National Geographic style."
    },
    {
        "name": "书虱",
        "englishName": "Booklouse",
        "scientificName": "Liposcelis bostrychophila",
        "category": "昆虫类",
        "habitat": "书籍纸张、粮仓和档案室",
        "diet": "取食霉菌、淀粉和纸张浆料",
        "size": "体长约0.1-0.15厘米",
        "weight": "不足0.001克",
        "length": 0.001,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "体不足1毫米,半透明,常成群出现在书籍、粮食和档案中,以霉菌和淀粉为食,是粮仓和图书馆的常见害虫,危害储藏物。",
        "imagePrompt": "A photorealistic macro photograph of a Booklouse (Liposcelis bostrychophila), minute translucent wingless insect crawling on old book pages, extreme macro, National Geographic style."
    },
    {
        "name": "蜉蝣",
        "englishName": "Mayfly",
        "scientificName": "Ephemera vulgata",
        "category": "昆虫类",
        "habitat": "池塘、溪流等洁净淡水水域附近",
        "diet": "稚虫取食藻类和水中有机碎屑,成虫不取食",
        "size": "体长约1-2.5厘米",
        "weight": "约0.05克",
        "length": 0.018,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "成虫寿命极短,有的仅活数小时,故有朝生暮死之说,前翅大后翅小,尾须细长,稚虫水生,成虫常在傍晚成群飞舞求偶。",
        "imagePrompt": "A photorealistic macro photograph of a Mayfly (Ephemera vulgata), delicate insect with translucent netted wings and three long tail filaments, hovering over water at dusk, National Geographic style."
    },
    {
        "name": "石蛾",
        "englishName": "Caddisfly",
        "scientificName": "Limnephilus lunatus",
        "category": "昆虫类",
        "habitat": "溪流、湖泊等洁净水域的岸边",
        "diet": "幼虫取食水生植物和碎屑,成虫吸食花蜜",
        "size": "体长约1-2厘米",
        "weight": "约0.05克",
        "length": 0.015,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "外形似蛾,翅面覆细毛,幼虫生活在溪流水中,用砂粒枝叶筑成巢管随身携带,是水质指示生物,成虫多栖息在水边植物上。",
        "imagePrompt": "A photorealistic macro photograph of a Caddisfly (Limnephilus lunatus), moth-like insect with hairy brown wings and long antennae, resting on a waterside plant, National Geographic style."
    },
    {
        "name": "螳蛉",
        "englishName": "Mantidfly",
        "scientificName": "Mantispa styriaca",
        "category": "昆虫类",
        "habitat": "林缘灌丛和草丛,常见于枝叶间",
        "diet": "成虫捕食小虫,幼虫寄生蜘蛛卵囊",
        "size": "体长约1-2厘米",
        "weight": "0.05-0.1克",
        "length": 0.015,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "前足为捕捉足似螳螂,翅脉又如草蛉,兼具两类特征,幼虫寄生在蜘蛛卵囊中取食,是形态奇特、习性特殊的捕食性昆虫。",
        "imagePrompt": "A photorealistic macro photograph of a Mantidfly (Mantispa styriaca), slender insect with raptorial mantis-like front legs and delicate veined wings, on a green leaf, National Geographic style."
    },
    {
        "name": "蚁蛉",
        "englishName": "Antlion",
        "scientificName": "Myrmeleon formicarius",
        "category": "昆虫类",
        "habitat": "沙地、松软土坡和林缘空地",
        "diet": "幼虫捕食坠入陷阱的蚂蚁等小虫",
        "size": "体长约3-4厘米(含翅)",
        "weight": "0.2-0.5克",
        "length": 0.03,
        "status": "无危(LC)",
        "emoji": "🐛",
        "description": "成虫似蜻蜓,幼虫称蚁狮,在沙地掘漏斗状陷阱,埋伏坑底捕食滑落的蚂蚁,故得名,幼虫耐饿本领惊人,可数月不食。",
        "imagePrompt": "A photorealistic macro photograph of a Antlion (Myrmeleon formicarius), slender winged insect resembling a damselfly with clubbed antennae, resting on sandy ground near its pit trap, National Geographic style."
    },
]

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "new_insects.json")

def main():
    # 校验
    assert len(INSECTS) == 40, f"条数={len(INSECTS)},必须恰好40"
    names = [i["name"] for i in INSECTS]
    scis = [i["scientificName"] for i in INSECTS]
    assert len(set(names)) == 40, "存在重复 name"
    assert len(set(scis)) == 40, "存在重复 scientificName"
    assert all(i["category"] == "昆虫类" for i in INSECTS)
    dlens = []
    for i in INSECTS:
        d = i["description"]
        n = len(d)
        dlens.append(n)
        assert 40 <= n <= 80, f"{i['name']} description {n} 字,超出40-80"
        p = i["imagePrompt"]
        assert p.startswith("A photorealistic macro photograph of a "), i["name"]
        assert p.rstrip().endswith("National Geographic style."), i["name"]
        assert "(" + i["scientificName"] + ")" in p, i["name"]
        assert isinstance(i["length"], (int, float)) and 0 < i["length"] < 1, i["name"]
        for f in ("name", "englishName", "scientificName", "category", "habitat",
                  "diet", "size", "weight", "status", "emoji"):
            assert i.get(f), f"{i['name']} 缺少字段 {f}"
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(INSECTS, f, ensure_ascii=False, indent=1)
    print("== 生成摘要 ==")
    print("文件路径:", OUT)
    print("记录条数:", len(INSECTS))
    print("文件大小: %.1f KB" % (os.path.getsize(OUT) / 1024))
    print("description 字数: min=%d, max=%d (要求40-80)" % (min(dlens), max(dlens)))
    print("imagePrompt 前缀/后缀: 全部符合规范")
    orders = {}
    for i in INSECTS:
        g = i["scientificName"].split()[0]
        orders.setdefault(g, []).append(i["name"])
    print("不同属(学名首词)数量:", len(orders))

if __name__ == "__main__":
    main()
