# -*- coding: utf-8 -*-
"""生成120种新增昆虫数据(昆虫类),写入 new_insects.json"""
import json, os, re, sys

# 已存在昆虫(严禁重复): 中华蜜蜂、帝王蝶、枯叶蝶、柑橘凤蝶、乌桕大蚕蛾、独角仙、锹甲、萤火虫、
# 中华大刀螳、碧伟蜓、黑蚱蝉、斗蟋、东亚飞蝗、日本弓背蚁、七星瓢虫、竹节虫、吉丁虫、家蚕

def E(name, en, sci, hab, diet, size, weight, length, status, emoji, desc, prompt):
    return dict(name=name, englishName=en, scientificName=sci, category="昆虫类",
                habitat=hab, diet=diet, size=size, weight=weight, length=length,
                status=status, emoji=emoji, description=desc, imagePrompt=prompt)

D = []
A = D.append

# ============ 鞘翅目 (22) ============
A(E("星天牛","Citrus Long-horned Beetle","Anoplophora chinensis","中国南方柑橘园及阔叶林中","幼虫蛀食树干,成虫啃食嫩枝树皮","体长约3.5厘米","2-4克",0.035,"无危(LC)","🪲","体黑色带光泽,鞘翅上有白色星状斑点,触角极长如鞭,是柑橘类果树的重要害虫,幼虫蛀食树干形成隧道,成虫啃食嫩枝树皮。","A photorealistic macro photograph of a Citrus Long-horned Beetle (Anoplophora chinensis), glossy black body with white star-like spots on the wing covers, extremely long black-and-white banded antennae, perched on a citrus branch with green leaves, National Geographic style."))
A(E("云斑天牛","White-spotted Long-horned Beetle","Batocera lineolata","杨树、核桃等阔叶林","幼虫蛀食树干,成虫取食嫩枝树皮","体长约5厘米","5-8克",0.05,"无危(LC)","🪲","大型天牛,鞘翅布满云状白色斑纹,触角超过体长,幼虫蛀食杨树、核桃等树干,是林业重要害虫,成虫夜晚活动取食嫩枝。","A photorealistic macro photograph of a White-spotted Long-horned Beetle (Batocera lineolata), large grayish-brown beetle with cloud-like white markings on the wing covers, antennae longer than its body, on a poplar trunk with rough bark, National Geographic style."))
A(E("中华虎甲","Chinese Tiger Beetle","Cicindela chinensis","沙地、河滩及林间小路","捕食小型昆虫","体长约2厘米","0.5-1克",0.02,"无危(LC)","🪲","体色艳丽,鞘翅呈铜绿与金色光泽,行动极为敏捷,是陆地上跑得最快的昆虫之一,常在沙地小径上奔跑,捕食小型昆虫。","A photorealistic macro photograph of a Chinese Tiger Beetle (Cicindela chinensis), iridescent metallic green and coppery wing covers, large compound eyes, long slender legs, standing on a sandy path in bright sunlight, National Geographic style."))
A(E("金星步甲","Chinese Caterpillar Hunter","Calosoma chinense","林地地表及农田","捕食毛毛虫等小型昆虫","体长约3厘米","1-2克",0.03,"无危(LC)","🪲","体黑色带金属光泽,鞘翅边缘泛金色,是凶猛的地表捕食者,捕食毛毛虫等小型昆虫,对控制森林害虫有重要作用。","A photorealistic macro photograph of a Chinese Caterpillar Hunter (Calosoma chinense), shiny black ground beetle with golden metallic rim on the wing covers, long legs, walking on forest floor leaf litter, National Geographic style."))
A(E("白星花金龟","White-spotted Flower Chafer","Protaetia brevitarsis","果园、林缘及花丛","取食花粉、花蜜和成熟果实","体长约2.5厘米","1-2克",0.025,"无危(LC)","🪲","体宽椭圆形,黑褐色带铜绿色金属光泽,鞘翅上有数条白色云纹状斑块,白天在花朵和果实上活动,取食花粉、花蜜和成熟果实。","A photorealistic macro photograph of a White-spotted Flower Chafer (Protaetia brevitarsis), broad blackish-brown body with metallic green sheen and white wavy markings on the wing covers, perched on a ripe peach fruit, National Geographic style."))
A(E("铜绿丽金龟","Copper-green Chafer","Anomala corpulenta","果园、农田及林地","成虫取食树叶,幼虫啃食植物根系","体长约2厘米","0.5-1克",0.02,"无危(LC)","🪲","体背铜绿色带金属光泽,腹面黄褐色,鞘翅有细密刻点,成虫取食多种果树叶片,幼虫在地下啃食植物根部,是常见地下害虫。","A photorealistic macro photograph of a Copper-green Chafer (Anomala corpulenta), metallic copper-green wing covers, yellowish underside, resting on a green leaf, soft morning light, National Geographic style."))
A(E("华北大黑鳃金龟","Northern Black Chafer","Holotrichia oblita","华北农田、果园及林地","成虫取食树叶,幼虫蛴螬啃食根系","体长约2厘米","0.5-1克",0.02,"无危(LC)","🪲","体黑褐色至黑色,鞘翅有光泽并具纵隆线,成虫取食树木和作物叶片,幼虫蛴螬在地下啃食根系,是华北地区重要地下害虫。","A photorealistic macro photograph of a Northern Black Chafer (Holotrichia oblita), glossy dark brown-black beetle with ridged wing covers, resting on tree bark at dusk, National Geographic style."))
A(E("神农洁蜣螂","Chinese Dung Beetle","Catharsius molossus","草原、田野及牧场","以动物粪便为食","体长约4.5厘米","8-15克",0.045,"无危(LC)","🪲","体宽短厚实,黑色带强烈光泽,雄虫头上有角状突起,以动物粪便为食,将粪球滚成团埋入地下作为食物和育幼场所,俗称屎壳郎。","A photorealistic macro photograph of a Chinese Dung Beetle (Catharsius molossus), large shiny black beetle with a horn on the head, rolling a ball of dung across sunlit sandy ground, National Geographic style."))
A(E("黄缘龙虱","Yellow-margined Diving Beetle","Cybister limbatus","池塘、湖泊等静水水域","捕食蝌蚪、小鱼等小型水生动物","体长约3.5厘米","2-3克",0.035,"无危(LC)","🪲","体扁平流线型,背面暗绿色,鞘翅外缘有黄色窄边,后足扁平如桨,是凶猛的水中捕食者,捕食蝌蚪、小鱼等小型水生动物。","A photorealistic macro photograph of a Yellow-margined Diving Beetle (Cybister limbatus), flattened dark green diving beetle with yellow margins on the wing covers, paddle-shaped hind legs, swimming in clear pond water, National Geographic style."))
A(E("大黑埋葬虫","Black Burying Beetle","Nicrophorus concolor","林地地表及草丛","取食小型动物尸体并用于育幼","体长约2.5厘米","1-2克",0.025,"无危(LC)","🪲","体黑色,鞘翅末端有橙红色斑纹,嗅觉灵敏,能发现并埋葬小型动物尸体,在其上产卵,幼虫以尸体为食,被称为自然界的清洁工。","A photorealistic macro photograph of a Black Burying Beetle (Nicrophorus concolor), black burying beetle with orange-red bands at the tips of the wing covers, antennae with orange clubs, on forest floor soil, National Geographic style."))
A(E("异色瓢虫","Asian Lady Beetle","Harmonia axyridis","农田、果园及城市绿地","捕食蚜虫、介壳虫等害虫","体长约0.7厘米","0.02-0.05克",0.007,"无危(LC)","🐞","体半球形,颜色变化极大,从橙黄色到黑色都有,斑点数目也不固定,是著名的益虫,成虫和幼虫都捕食蚜虫等害虫。","A photorealistic macro photograph of an Asian Lady Beetle (Harmonia axyridis), round dome-shaped beetle with orange-red wing covers and numerous black spots, crawling on a green leaf covered with aphids, National Geographic style."))
A(E("龟纹瓢虫","Japanese Tortoise Ladybug","Propylea japonica","菜园、棉田及草地","捕食蚜虫、飞虱等害虫","体长约0.4厘米","0.01-0.02克",0.004,"无危(LC)","🐞","体小,橙黄色鞘翅上有龟甲状黑色花纹,花纹变化多样,主要捕食蚜虫、飞虱等害虫,常见于菜园和棉田,是优良天敌昆虫。","A photorealistic macro photograph of a Japanese Tortoise Ladybug (Propylea japonica), tiny yellow-orange ladybird with black tortoise-shell-like pattern, perched on a cotton leaf, National Geographic style."))
A(E("红棕象甲","Red Palm Weevil","Rhynchophorus ferrugineus","棕榈科植物种植区","幼虫蛀食树心,成虫取食树液","体长约4厘米","2-4克",0.04,"无危(LC)","🪲","体红褐色,前胸背板有黑色斑块,喙长而弯曲,是棕榈科植物的重要害虫,幼虫蛀食树心造成整株枯死,在热带地区危害严重。","A photorealistic macro photograph of a Red Palm Weevil (Rhynchophorus ferrugineus), reddish-brown weevil with black spots on the thorax and a long curved snout, on a palm trunk with fibrous bark, National Geographic style."))
A(E("甘薯蚁象","Sweet Potato Weevil","Cylas formicarius","甘薯田及旋花科植物上","幼虫蛀食薯块,成虫取食藤蔓","体长约0.6厘米","0.02-0.04克",0.006,"无危(LC)","🪲","体细长如蚁,深褐色或黑褐色,触角和足细长,是甘薯的重要害虫,幼虫蛀食薯块形成苦味孔道,严重影响甘薯品质和产量。","A photorealistic macro photograph of a Sweet Potato Weevil (Cylas formicarius), slender ant-like weevil with dark brown body, long thin antennae and legs, crawling on a sweet potato vine leaf, National Geographic style."))
A(E("沟金针虫","Grooved Click Beetle","Pleonomus canaliculatus","农田土壤及草丛","幼虫啃食作物种子和根系","体长约1.4厘米","0.1-0.3克",0.014,"无危(LC)","🪲","体细长,深褐色,鞘翅上有纵沟,受惊时会弹跳发出咔哒声,幼虫俗称金针虫,在地下啃食作物种子和根系,是常见的地下害虫。","A photorealistic macro photograph of a Grooved Click Beetle (Pleonomus canaliculatus), slender dark brown click beetle with grooved wing covers, on dry soil, National Geographic style."))
A(E("长戟大兜虫","Hercules Beetle","Dynastes hercules","中美洲及南美热带雨林","幼虫腐食朽木,成虫取食树液和果实","体长含角可达17厘米","30-100克",0.15,"未评估(NE)","🪲","世界最著名的巨型甲虫之一,雄虫前胸有长角,头部有向上弯曲的犄角,呈Y字形,体长可达17厘米,是甲虫爱好者心中的明星。","A photorealistic macro photograph of a Hercules Beetle (Dynastes hercules), gigantic beetle with a long curved horn on the head and a smaller horn on the thorax, glossy dark body, climbing a tropical tree branch, National Geographic style."))
A(E("阳彩臂金龟","Jansoni's Jewel Scarab","Cheirotonus jansoni","我国南方山地阔叶林","幼虫腐食朽木,成虫取食树液","体长约8厘米(含前足)","10-20克",0.08,"国家二级保护动物","🪲","体形硕大,体色金绿色带强烈金属光泽,前足极长,行动缓慢,是我国特有的珍稀甲虫,被列为国家二级保护动物,野外数量稀少。","A photorealistic macro photograph of a Jansoni's Jewel Scarab (Cheirotonus jansoni), large golden-green scarab with metallic sheen and extremely long front legs, on a mossy tree trunk in a misty forest, National Geographic style."))
A(E("茄二十八星瓢虫","28-spotted Ladybird","Henosepilachna vigintioctopunctata","菜园及茄科作物上","啃食茄科植物叶片","体长约0.8厘米","0.03-0.05克",0.008,"无危(LC)","🐞","体半球形,红褐色鞘翅上有28个黑色斑点,与七星瓢虫不同,它是植食性害虫,成虫和幼虫都啃食茄科植物的叶片,造成网状危害。","A photorealistic macro photograph of a 28-spotted Ladybird (Henosepilachna vigintioctopunctata), rounded reddish-brown ladybird with 28 black spots, feeding on an eggplant leaf with bite holes, National Geographic style."))
A(E("黄粉虫","Mealworm Beetle","Tenebrio molitor","粮仓及人工饲养环境","幼虫取食麦麸、谷物","体长约1.8厘米","0.5-1克",0.018,"无危(LC)","🪲","体长椭圆形,黑褐色,鞘翅有纵纹,幼虫俗称面包虫,是重要的饲料昆虫,人工养殖历史悠久,也常作为宠物鸟和爬宠的活体饲料。","A photorealistic macro photograph of a Mealworm Beetle (Tenebrio molitor), elongated dark brown darkling beetle with striated wing covers, on wheat bran in a breeding box, National Geographic style."))
A(E("大牙甲","Great Silver Water Beetle","Hydrophilus acuminatus","池塘、水田等静水水域","取食水草和动物残体","体长约4厘米","3-5克",0.04,"无危(LC)","🪲","体大,黑色带强烈光泽,腹面有银白色防水毛层,在水中行走时如被水银包裹,取食水草和动物残体,是常见的大型水生甲虫。","A photorealistic macro photograph of a Great Silver Water Beetle (Hydrophilus acuminatus), large black water scavenger beetle with glossy body and silvery air film on the underside, swimming in a shallow pond, National Geographic style."))
A(E("马铃薯叶甲","Colorado Potato Beetle","Leptinotarsa decemlineata","马铃薯田及茄科作物上","取食马铃薯等茄科植物叶片","体长约1厘米","0.1-0.2克",0.01,"无危(LC)","🪲","体橙黄色,鞘翅上有十条黑色纵纹,是马铃薯的著名害虫,曾横扫欧美农田,对农药产生抗性,是昆虫学研究的经典对象。","A photorealistic macro photograph of a Colorado Potato Beetle (Leptinotarsa decemlineata), rounded yellow-orange beetle with ten black stripes on the wing covers, on a potato plant leaf, National Geographic style."))
A(E("大斑芫菁","Large Blister Beetle","Mylabris phalerata","豆科植物及草地","成虫取食豆科植物,幼虫寄生于蝗虫卵块","体长约3厘米","0.5-1克",0.03,"无危(LC)","🪲","体黑色,鞘翅上有黄色横带和黑斑,受惊时腿节分泌含斑蝥素的黄色液体,具有刺激性,幼虫寄生于蝗虫卵块,成虫取食豆科植物。","A photorealistic macro photograph of a Large Blister Beetle (Mylabris phalerata), black blister beetle with yellow transverse bands on the wing covers, on a legume flower, National Geographic style."))

# ============ 鳞翅目 (18) ============
A(E("蓝闪蝶","Blue Morpho Butterfly","Morpho peleides","中南美洲热带雨林","幼虫取食豆科植物叶片,成虫吸食发酵果汁","翼展约12厘米","3-6克",0.12,"无危(LC)","🦋","大型蝴蝶,翅面呈明亮的金属蓝色,飞行时如蓝色闪光,翅背为褐色带眼斑,栖息于南美热带雨林,是世界上最著名的观赏蝴蝶。","A photorealistic macro photograph of a Blue Morpho Butterfly (Morpho peleides), brilliant metallic blue wings with black margins, brown underside with eye spots, perched on a rainforest leaf, National Geographic style."))
A(E("裳凤蝶","Common Birdwing","Troides helena","东南亚及我国南方山地","幼虫取食马兜铃植物,成虫吸食花蜜","翼展约15厘米","4-7克",0.08,"无危(LC)","🦋","大型蝴蝶,前翅黑色,后翅金黄色带黑色脉纹,飞行缓慢优美,雄蝶后翅有黑色缘带,分布于东南亚及我国南方,是受保护的观赏蝶种。","A photorealistic macro photograph of a Common Birdwing (Troides helena), large butterfly with black forewings and bright golden-yellow hindwings with black veins, hovering over tropical flowers, National Geographic style."))
A(E("金斑喙凤蝶","Golden Kaiserihind","Teinopalpus aureus","我国南方高山林带","幼虫取食木兰科植物,成虫吸食花蜜","翼展约10厘米","2-4克",0.05,"国家一级保护动物","🦋","我国特有珍稀蝴蝶,翅面金绿色,后翅有金黄色大斑,雌蝶更为珍贵,被列为国家一级保护动物,被誉为蝶中皇后,极为罕见。","A photorealistic macro photograph of a Golden Kaiserihind (Teinopalpus aureus), rare golden-green swallowtail butterfly with large golden patches on the hindwings, resting on a mountain flower with misty forest background, National Geographic style."))
A(E("菜粉蝶","Small Cabbage White","Pieris rapae","菜园、田野及城市绿地","幼虫取食十字花科蔬菜叶片","翼展约5厘米","0.2-0.4克",0.02,"无危(LC)","🦋","最常见的白色蝴蝶,翅面白色,前翅顶角有黑斑,幼虫俗称菜青虫,取食十字花科蔬菜叶片,是菜园里最常见的害虫之一。","A photorealistic macro photograph of a Small Cabbage White (Pieris rapae), white butterfly with black tips on the forewings, resting on a cabbage leaf in a vegetable garden, National Geographic style."))
A(E("黑纹粉蝶","Gray-veined White","Pieris melete","山地林缘及田野","幼虫取食十字花科植物,成虫吸食花蜜","翼展约6厘米","0.3-0.5克",0.025,"无危(LC)","🦋","翅白色,翅脉处有黑色条纹,春天最早出现的粉蝶之一,幼虫取食十字花科植物,常见于田野和山地林缘,飞行姿态轻盈。","A photorealistic macro photograph of a Gray-veined White (Pieris melete), white butterfly with dark veins along the wings, on a wild flower in a spring meadow, National Geographic style."))
A(E("大红蛱蝶","Indian Red Admiral","Vanessa indica","林缘、庭院及山地","幼虫取食荨麻等植物,成虫吸食树汁","翼展约6.5厘米","0.3-0.5克",0.028,"无危(LC)","🦋","翅面橙红色,有黑色斑纹,前翅顶角有白色小斑,幼虫以荨麻等植物为食,成虫常吸食树汁和腐烂果实,飞行迅速而敏捷。","A photorealistic macro photograph of an Indian Red Admiral (Vanessa indica), orange-red butterfly with black patches and white spots on the wing tips, basking on a tree trunk with sap, National Geographic style."))
A(E("电蛱蝶","Constable Butterfly","Dichorragia nesimachus","山地林间及溪谷","幼虫取食清风藤科植物,成虫吸食树汁","翼展约7厘米","0.4-0.6克",0.03,"无危(LC)","🦋","翅面深蓝色带金属光泽,有白色小斑点,如夜空中的闪电,栖息于山地林间,成虫喜吸食树汁,飞行快速,姿态优雅。","A photorealistic macro photograph of a Constable Butterfly (Dichorragia nesimachus), dark blue butterfly with metallic sheen and white speckles, wings spread on a mossy rock in a mountain forest, National Geographic style."))
A(E("苎麻珍蝶","Yellow Coster","Acraea issoria","我国南方田野及林缘","幼虫取食苎麻等荨麻科植物","翼展约6厘米","0.3-0.5克",0.025,"无危(LC)","🦋","翅面橙黄色,前翅外缘有黑色宽带和白斑,幼虫群集取食苎麻等荨麻科植物,常见于我国南方田野,色彩明艳引人注目。","A photorealistic macro photograph of a Yellow Coster (Acraea issoria), orange-yellow butterfly with black outer border and white spots, on a ramie leaf in bright daylight, National Geographic style."))
A(E("直纹稻弄蝶","Rice Swift Butterfly","Parnara guttata","水稻田及禾本科草丛","幼虫吐丝卷叶取食稻叶","翼展约4厘米","0.1-0.2克",0.018,"无危(LC)","🦋","小型蝴蝶,翅暗褐色,后翅有四个白色小斑排成直线,幼虫吐丝卷叶为害水稻,是稻田最常见的弄蝶,飞行快速带跳跃感。","A photorealistic macro photograph of a Rice Swift Butterfly (Parnara guttata), small brown skipper butterfly with four white spots in a straight row on the hindwings, resting on a rice leaf, National Geographic style."))
A(E("小豆长喙天蛾","Hummingbird Hawk-moth","Macroglossum stellatarum","花园、田野及山地","成虫悬停吸食花蜜,幼虫取食茜草科植物","体长约4厘米,翼展5厘米","1-2克",0.04,"无危(LC)","🦋","蛾类中的蜂鸟,白天活动,悬停于花前用长喙吸食花蜜,翅快速振动发出嗡嗡声,常被误认为蜂鸟,是昆虫界的拟态趣闻。","A photorealistic macro photograph of a Hummingbird Hawk-moth (Macroglossum stellatarum), brownish moth with a long proboscis, hovering in front of a pink flower like a hummingbird, blurred garden background, National Geographic style."))
A(E("豆天蛾","Bean Hawk-moth","Clanis bilineata","大豆田及豆科植物上","幼虫取食大豆叶片","体长约4.5厘米,翼展10厘米","2-4克",0.045,"无危(LC)","🦋","大型蛾类,翅黄褐色带复杂波纹,幼虫俗称豆虫,取食大豆叶片,是重要的农业害虫,其幼虫是山东等地著名的传统美食原料。","A photorealistic macro photograph of a Bean Hawk-moth (Clanis bilineata), large tan hawk moth with wavy brown patterns on the wings, resting on a soybean plant, National Geographic style."))
A(E("柞蚕","Chinese Tussar Moth","Antheraea pernyi","柞树林及人工放养区","幼虫取食柞树叶片","体长约6厘米,翼展13厘米","3-6克",0.06,"无危(LC)","🦋","大型蛾类,翅黄褐色带眼斑,幼虫以柞树叶片为食,吐丝结茧,是我国的传统经济昆虫,柞蚕丝可织造高档丝绸面料。","A photorealistic macro photograph of a Chinese Tussar Moth (Antheraea pernyi), large yellow-brown silk moth with eye spots on the wings, perched on oak leaves in soft evening light, National Geographic style."))
A(E("樟蚕","Giant Silkworm Moth","Eriogyna pyretorum","樟树、枫香等阔叶林","幼虫取食樟树等叶片","体长约5厘米,翼展11厘米","2-5克",0.05,"无危(LC)","🦋","大型蛾类,翅灰褐色带复杂波纹和眼状斑,幼虫取食樟树等叶片,吐丝结茧,茧丝坚韧,是重要的野生吐丝昆虫资源。","A photorealistic macro photograph of a Giant Silkworm Moth (Eriogyna pyretorum), large gray-brown silk moth with wavy lines and eye spots on the wings, resting on a camphor tree leaf, National Geographic style."))
A(E("小地老虎","Black Cutworm Moth","Agrotis ipsilon","农田及菜地土壤","幼虫夜间咬断农作物幼苗","体长约2厘米,翼展4厘米","0.3-0.6克",0.02,"无危(LC)","🦋","中型蛾类,前翅灰褐色带肾形纹和剑形纹,幼虫俗称地蚕,夜间咬断农作物幼苗,是重要的地下害虫,几乎危害所有作物。","A photorealistic macro photograph of a Black Cutworm Moth (Agrotis ipsilon), grayish-brown noctuid moth with kidney-shaped markings on the forewings, resting on dark soil at night, National Geographic style."))
A(E("棉铃虫","Cotton Bollworm Moth","Helicoverpa armigera","棉花田及蔬菜地","幼虫蛀食蕾铃和果实","体长约1.8厘米,翼展3.5厘米","0.2-0.5克",0.018,"无危(LC)","🦋","中型蛾类,前翅黄褐色带环状纹,幼虫蛀食棉花蕾铃和番茄果实,是世界性的重要农业害虫,对多种农药产生抗性。","A photorealistic macro photograph of a Cotton Bollworm Moth (Helicoverpa armigera), yellowish-brown moth with ring-shaped markings on the forewings, resting on a cotton boll, National Geographic style."))
A(E("桦尺蠖","Peppered Moth","Biston betularia","桦树、橡树林","幼虫取食树木叶片","体长约2.5厘米,翼展5厘米","0.3-0.5克",0.025,"无危(LC)","🦋","翅灰白色带黑色斑点,深浅色型差异显著,是达尔文进化论的经典例证,工业革命期间深色型比例上升,称为工业黑化现象。","A photorealistic macro photograph of a Peppered Moth (Biston betularia), pale wings speckled with black dots, resting on a lichen-covered birch trunk, National Geographic style."))
A(E("红缘灯蛾","Red-edged Buff Moth","Amsacta lactinea","农田、林缘及草地","幼虫取食多种植物叶片","体长约3.5厘米,翼展7厘米","0.8-1.5克",0.035,"无危(LC)","🦋","翅白色,前翅有数条红色横带,后翅有红色斑点,幼虫体色鲜艳有黑色长毛,取食多种植物,成虫夜间活动,色彩对比鲜明。","A photorealistic macro photograph of a Red-edged Buff Moth (Amsacta lactinea), white-winged moth with red stripes and spots, resting on a green leaf at night, National Geographic style."))
A(E("黄刺蛾","Oriental Nettle Moth","Cnidocampa flavescens","果园及城市绿化树","幼虫取食果树叶片","体长约1.5厘米,翼展3厘米","0.1-0.2克",0.015,"无危(LC)","🦋","翅面黄色带褐色斑纹,幼虫俗称洋辣子,体表布满有毒刺毛,接触皮肤会刺痛红肿,取食果树叶片,是常见的园林害虫。","A photorealistic macro photograph of an Oriental Nettle Moth (Cnidocampa flavescens), yellow moth with brown markings, resting on a fruit tree leaf, National Geographic style."))

# ============ 膜翅目 (16) ============
A(E("金环胡蜂","Asian Giant Hornet","Vespa mandarinia","山地森林及果园","捕食蜜蜂等昆虫,取食树液和果实","体长约5厘米","1-2克",0.05,"无危(LC)","🐝","世界上体型最大的胡蜂,头部橙黄色,腹部有金黄与黑色环带,性情凶猛,捕食其他昆虫和蜜蜂,毒刺威力强大,是蜂中猛虎。","A photorealistic macro photograph of an Asian Giant Hornet (Vespa mandarinia), giant hornet with orange head and golden-and-black banded abdomen, hovering near a forest clearing, National Geographic style."))
A(E("墨胸胡蜂","Yellow-legged Hornet","Vespa velutina","城镇屋檐、树洞及灌丛","捕食蜜蜂和小型昆虫,取食花蜜","体长约2.5厘米","0.3-0.6克",0.025,"无危(LC)","🐝","体黑色带黄色环纹,胸背黑色,常见于城镇屋檐下筑巢,捕食蜜蜂和小型昆虫,是中华蜜蜂的重要天敌,蜇人疼痛剧烈。","A photorealistic macro photograph of a Yellow-legged Hornet (Vespa velutina), black hornet with yellow bands on the abdomen, on a paper nest under a rooftop eave, National Geographic style."))
A(E("德国黄胡蜂","German Wasp","Vespula germanica","城市、村庄及林缘","捕食昆虫,取食甜食和果实","体长约1.3厘米","0.1-0.2克",0.013,"无危(LC)","🐝","体黑黄相间,腹部有连续黄斑,是社会性胡蜂,常在垃圾和食物周围活动,秋季性情暴躁,是城市中最常见的胡蜂之一。","A photorealistic macro photograph of a German Wasp (Vespula germanica), black-and-yellow wasp with continuous yellow bands on the abdomen, on a picnic table near a glass of juice, National Geographic style."))
A(E("亚非马蜂","Yellow Paper Wasp","Polistes olivaceus","屋檐、树枝及草丛","捕食害虫,取食花蜜","体长约2厘米","0.1-0.3克",0.02,"无危(LC)","🐝","细腰胡蜂,体黄褐色带黑色斑纹,巢为单层纸状圆盘,悬挂于屋檐或树枝下,捕食害虫也取食花蜜,是半社会性昆虫。","A photorealistic macro photograph of a Yellow Paper Wasp (Polistes olivaceus), slender yellow-brown paper wasp with black markings and a narrow waist, on a single-comb paper nest, National Geographic style."))
A(E("明亮熊蜂","White-tailed Bumblebee","Bombus lucorum","草地、果园及温室","采集花蜜和花粉","体长约2厘米","0.4-0.8克",0.02,"无危(LC)","🐝","体大而圆胖,黑色绒毛带白色尾端,全身密布细毛,是重要的授粉昆虫,温室番茄等作物常依靠熊蜂授粉,性情温顺。","A photorealistic macro photograph of a White-tailed Bumblebee (Bombus lucorum), large fuzzy black bumblebee with a white tail, collecting nectar on a purple clover flower, National Geographic style."))
A(E("红光熊蜂","Red-tailed Bumblebee","Bombus ignitus","高寒山地及草原","采集花蜜和花粉","体长约1.8厘米","0.3-0.7克",0.018,"无危(LC)","🐝","体型大,黑色绒毛,腹部末端红色,是高寒地区的授粉主力,对低温适应能力强,为高山植物传粉,是生态系统中重要一环。","A photorealistic macro photograph of a Red-tailed Bumblebee (Bombus ignitus), large fuzzy black bumblebee with a reddish-orange tail, on a yellow alpine flower, National Geographic style."))
A(E("西方蜜蜂","Western Honey Bee","Apis mellifera","蜂场、果园及花田","采集花蜜和花粉","体长约1.3厘米","0.08-0.15克",0.013,"无危(LC)","🐝","世界上最广泛饲养的蜜蜂,体黄褐色带黑色环带,酿蜜和授粉能力极强,是农业生产中最重要的授粉昆虫,蜂群社会结构复杂。","A photorealistic macro photograph of a Western Honey Bee (Apis mellifera), yellowish-brown honey bee with black bands, on a honeycomb frame with hexagonal cells, National Geographic style."))
A(E("中华木蜂","Chinese Carpenter Bee","Xylocopa sinensis","庭院、果园及林地","采集花蜜和花粉","体长约2.5厘米","0.4-0.8克",0.025,"无危(LC)","🐝","大型蜂类,体黑色带蓝紫色金属光泽,在枯木中筑巢,在花朵间飞行时如一团黑紫影子,是重要的野生传粉昆虫,独居生活。","A photorealistic macro photograph of a Chinese Carpenter Bee (Xylocopa sinensis), large dark bee with blue-violet metallic sheen, hovering near a wooden beam with a round nest hole, National Geographic style."))
A(E("南美切叶蚁","Leaf-cutter Ant","Atta cephalotes","中南美洲热带雨林","切割树叶培养真菌为食","工蚁体长约1.2厘米","0.05-0.1克",0.012,"未评估(NE)","🐜","大型切叶蚁,工蚁用锋利的上颚切割树叶碎片运回巢中,用于培养真菌作为食物,巢穴巨大,是南美雨林中最壮观的昆虫社会。","A photorealistic macro photograph of a Leaf-cutter Ant (Atta cephalotes), large reddish leaf-cutter ants carrying green leaf fragments in a long trail across the rainforest floor, National Geographic style."))
A(E("伯切尔行军蚁","Army Ant","Eciton burchellii","中南美洲热带雨林","成群捕食小型昆虫","工蚁体长约1.2厘米","0.05-0.1克",0.012,"未评估(NE)","🐜","没有固定巢穴的蚂蚁,成千上万只组成庞大军团迁徙,捕食途中一切小型昆虫,蜂拥而过时声势浩大,是雨林中的移动军团。","A photorealistic macro photograph of an Army Ant (Eciton burchellii), swarm of reddish army ants marching in a dense column across the jungle floor, National Geographic style."))
A(E("子弹蚁","Bullet Ant","Paraponera clavata","中南美洲热带雨林","取食花蜜和小型节肢动物","体长约2.5厘米","0.5-1克",0.025,"未评估(NE)","🐜","体型巨大的蚂蚁,蜇刺疼痛号称昆虫界第一,疼痛如中弹,生活在南美雨林,工蚁体红褐色,以花蜜和小型节肢动物为食。","A photorealistic macro photograph of a Bullet Ant (Paraponera clavata), giant reddish-brown ant with powerful mandibles, on a rainforest tree trunk, National Geographic style."))
A(E("红火蚁","Red Imported Fire Ant","Solenopsis invicta","农田、草坪及路边","杂食性,取食种子、昆虫和蜜露","工蚁体长约0.5厘米","0.002-0.005克",0.005,"无危(LC)","🐜","红褐色小型蚂蚁,攻击性强,蜇人后出现灼烧感并起脓疱,是入侵性害虫,原产南美,现已扩散至全球多地,危害农业和生态。","A photorealistic macro photograph of a Red Imported Fire Ant (Solenopsis invicta), small reddish-brown fire ants swarming on a mound of soil, National Geographic style."))
A(E("黄猄蚁","Weaver Ant","Oecophylla smaragdina","柑橘园及热带树冠","捕食果树害虫,取食蜜露","工蚁体长约0.9厘米","0.02-0.05克",0.009,"无危(LC)","🐜","体黄绿色,在树冠上吐丝将叶片缀合筑巢,是著名的捕食性蚂蚁,捕食柑橘等果树害虫,我国南方果农自古利用其防治害虫。","A photorealistic macro photograph of a Weaver Ant (Oecophylla smaragdina), greenish-yellow weaver ants stitching leaves together with silk on a citrus tree, National Geographic style."))
A(E("螟蛉悬茧姬蜂","Bicolored Ichneumon Wasp","Charops bicolor","稻田及草丛","幼虫寄生于螟虫体内","体长约1.2厘米","0.02-0.05克",0.012,"无危(LC)","🐝","细长姬蜂,腹部有黄黑环带,幼虫寄生于螟虫体内,成熟后在寄主体外吐丝悬挂作茧,是稻田中重要的天敌昆虫。","A photorealistic macro photograph of a Bicolored Ichneumon Wasp (Charops bicolor), slender ichneumon wasp with yellow-and-black banded abdomen, hanging white cocoons on a rice stem, National Geographic style."))
A(E("扁头泥蜂","Emerald Cockroach Wasp","Ampulex compressa","热带及亚热带地区","幼虫以蟑螂为食,成虫取食花蜜","体长约2厘米","0.1-0.2克",0.02,"未评估(NE)","🐝","体具翠绿色金属光泽,是著名的翡翠蜚蠊蜂,雌蜂蜇刺蟑螂将其控制后拖入洞穴产卵,幼虫以蟑螂为食,行为令人惊叹。","A photorealistic macro photograph of an Emerald Cockroach Wasp (Ampulex compressa), emerald green metallic wasp with blue reflections, on a wooden floor beside a cockroach, National Geographic style."))
A(E("松毛虫赤眼蜂","Dendrolimus Egg Parasitoid Wasp","Trichogramma dendrolimi","松林及人工释放区","幼虫寄生于松毛虫卵内","体长不足1毫米","不足0.001克",0.0004,"无危(LC)","🐝","体长不足1毫米,是世界上最小的昆虫之一,雌蜂将卵产入松毛虫卵内,幼虫在寄主卵中发育,是林业上广泛应用的生防天敌。","A photorealistic macro photograph of a Dendrolimus Egg Parasitoid Wasp (Trichogramma dendrolimi), microscopic golden-yellow parasitic wasp with red eyes, standing on a pine moth egg cluster, extreme magnification, National Geographic style."))

# ============ 双翅目 (11) ============
A(E("家蝇","Housefly","Musca domestica","住宅、畜舍及垃圾堆","取食腐烂有机物和人类食物","体长约0.7厘米","0.01-0.02克",0.007,"无危(LC)","🪰","最常见的蝇类,体灰黑色,复眼红色,胸部有四条黑色纵纹,与人类生活密切,幼虫蛆在腐败有机物中发育,需注意卫生防范。","A photorealistic macro photograph of a Housefly (Musca domestica), gray fly with red compound eyes and four black stripes on the thorax, on a kitchen windowsill, National Geographic style."))
A(E("大头金蝇","Oriental Latrine Fly","Chrysomya megacephala","腐物、垃圾及花丛","取食腐烂有机物和花蜜","体长约1厘米","0.02-0.04克",0.01,"无危(LC)","🪰","体亮绿色带金属光泽,复眼巨大红色,常聚集在腐物周围,幼虫在腐烂有机物中发育,是法医昆虫学的重要研究对象。","A photorealistic macro photograph of an Oriental Latrine Fly (Chrysomya megacephala), metallic green blow fly with large red eyes, on a ripe fruit, National Geographic style."))
A(E("中华按蚊","Chinese Malaria Mosquito","Anopheles sinensis","稻田、沼泽及住宅区","雄蚊吸食花蜜,雌蚊繁殖期吸食动物体液","体长约0.6厘米","0.002-0.005克",0.006,"无危(LC)","🦟","体灰褐色,翅面有暗斑,停落时身体与停留面成角度,雌蚊繁殖期吸食动物体液,是传播疟疾的重要媒介,常见于水稻田区。","A photorealistic macro photograph of a Chinese Malaria Mosquito (Anopheles sinensis), gray-brown mosquito with spotted wings, resting at an angle on a rice leaf, National Geographic style."))
A(E("埃及伊蚊","Yellow Fever Mosquito","Aedes aegypti","城镇及热带住宅区","雄蚊吸食花蜜,雌蚊繁殖期吸食动物体液","体长约0.6厘米","0.002-0.005克",0.006,"无危(LC)","🦟","体黑色带银白色斑纹,是传播登革热、黄热病的重要媒介蚊种,白天活动,喜在室内外容器积水中繁殖,世界性分布。","A photorealistic macro photograph of a Yellow Fever Mosquito (Aedes aegypti), black mosquito with white lyre-shaped markings and banded legs, resting on the edge of a water container, National Geographic style."))
A(E("致倦库蚊","Southern House Mosquito","Culex quinquefasciatus","住宅区及污水沟","雄蚊吸食花蜜,雌蚊繁殖期吸食动物体液","体长约0.5厘米","0.002-0.004克",0.005,"无危(LC)","🦟","体褐色,是城市中最常见的蚊子,夜晚叮咬人和家畜,在污水和积水中繁殖,是住宅区的主要骚扰蚊种,需注意防护。","A photorealistic macro photograph of a Southern House Mosquito (Culex quinquefasciatus), brown house mosquito with pale bands on the abdomen, resting on a wall, National Geographic style."))
A(E("蜂虻","Large Bee Fly","Bombylius major","草地、林缘及花丛","成虫吸食花蜜,幼虫寄生于蜂类巢穴","体长约1.2厘米","0.05-0.1克",0.012,"无危(LC)","🪰","外形酷似蜜蜂的蝇类,体覆金黄色绒毛,以长喙悬停吸食花蜜,幼虫寄生于蜂类巢穴中,是双翅目中拟态昆虫的典型代表。","A photorealistic macro photograph of a Large Bee Fly (Bombylius major), fuzzy golden-brown bee fly with a long proboscis, hovering above a violet flower, National Geographic style."))
A(E("沼泽大蚊","European Crane Fly","Tipula paludosa","潮湿草地及沼泽","幼虫取食植物根茎,成虫取食花蜜","体长约3厘米","0.1-0.2克",0.03,"无危(LC)","🪰","体细长,足极长而脆弱,飞行缓慢,常被误认为巨型蚊子,但成虫不叮咬,取食花蜜,幼虫在潮湿土壤中取食植物根茎。","A photorealistic macro photograph of a European Crane Fly (Tipula paludosa), slender crane fly with extremely long fragile legs, resting on a grass blade in a damp meadow, National Geographic style."))
A(E("黑腹果蝇","Common Fruit Fly","Drosophila melanogaster","果园、发酵水果及实验室","取食发酵水果和酵母","体长约0.3厘米","0.001-0.002克",0.003,"无危(LC)","🪰","小型蝇类,红眼黄褐色,腹背有黑色环纹,是遗传学研究最重要的模式生物,繁殖快,饲养容易,多项诺贝尔奖研究以它为对象。","A photorealistic macro photograph of a Common Fruit Fly (Drosophila melanogaster), tiny yellow-brown fruit fly with red eyes and black-ringed abdomen, on a rotting banana slice, National Geographic style."))
A(E("中华斑虻","Chinese Deer Fly","Chrysops sinensis","牧场、林缘及溪流边","雌虫叮咬牲畜,雄虫取食花蜜","体长约1.2厘米","0.05-0.1克",0.012,"无危(LC)","🪰","体黄褐色,翅面有云雾状斑纹,复眼巨大带金属光泽,雌虻叮咬牲畜和人的皮肤,雄虻取食花蜜,是牧场常见的大型虻类。","A photorealistic macro photograph of a Chinese Deer Fly (Chrysops sinensis), deer fly with large golden-green eyes and cloud-patterned wings, perched on a blade of grass near a pasture, National Geographic style."))
A(E("黑带食蚜蝇","Marmalade Hoverfly","Episyrphus balteatus","花田、菜园及草地","幼虫捕食蚜虫,成虫吸食花蜜","体长约1厘米","0.02-0.04克",0.01,"无危(LC)","🪰","外形酷似蜜蜂的蝇类,腹部有黑黄相间条纹,常在花丛中悬停,幼虫捕食蚜虫,是农田中重要的天敌昆虫,成虫帮助传粉。","A photorealistic macro photograph of a Marmalade Hoverfly (Episyrphus balteatus), hoverfly with black-and-yellow striped abdomen, hovering beside an orange flower, National Geographic style."))
A(E("羽摇蚊","Feathered Midge","Chironomus plumosus","湖泊、池塘等静水水域","幼虫取食水底有机物,成虫不取食","体长约0.8厘米","0.01-0.02克",0.008,"无危(LC)","🪰","体细长,足长,雄虫触角呈羽毛状,不叮人不吸血,常在水面成群飞舞,幼虫红色俗称红虫,是水生态监测的重要指示生物。","A photorealistic macro photograph of a Feathered Midge (Chironomus plumosus), slender midge with feathery male antennae, resting on a water surface near red larvae, National Geographic style."))

# ============ 半翅目 (12) ============
A(E("蟪蛄","Kaempfer's Cicada","Platypleura kaempferi","树林及果园","若虫吸食树根汁液,成虫吸食树液","体长约2.5厘米","1-2克",0.025,"无危(LC)","🪰","小型蝉,体褐色带绿色斑纹,翅透明有褐色斑,盛夏时节在树林中鸣叫,声音细弱连绵,幼虫在地下吸食树根汁液数年。","A photorealistic macro photograph of a Kaempfer's Cicada (Platypleura kaempferi), small brown cicada with green markings and transparent spotted wings, clinging to a tree trunk, National Geographic style."))
A(E("蒙古寒蝉","Mongolian Cicada","Meimuna mongolica","城市行道树及山林","若虫吸食树根汁液,成虫吸食树液","体长约3厘米","1.5-3克",0.03,"无危(LC)","🪰","中型蝉,体灰绿色带黑色斑纹,秋季鸣叫声音嘹亮,常见于城市行道树,幼虫在地下生活数年,羽化后仅存活数周。","A photorealistic macro photograph of a Mongolian Cicada (Meimuna mongolica), medium gray-green cicada with black markings and translucent wings, on a city street tree, National Geographic style."))
A(E("棉蚜","Cotton Aphid","Aphis gossypii","棉田及瓜类作物上","群集吸食植物汁液","体长约0.2厘米","不足0.001克",0.002,"无危(LC)","🪰","体小,淡黄色至深绿色,群集于棉花等植物嫩梢和叶背吸食汁液,繁殖极快,分泌蜜露引发煤污病,是重要的农业害虫。","A photorealistic macro photograph of a Cotton Aphid (Aphis gossypii), tiny pale yellow-green aphids clustered on a cotton shoot with an ant nearby, National Geographic style."))
A(E("桃蚜","Green Peach Aphid","Myzus persicae","桃树、蔬菜及花卉上","群集吸食植物汁液","体长约0.2厘米","不足0.001克",0.002,"无危(LC)","🪰","体小,绿色或粉红色,寄主范围极广,取食桃树、蔬菜等数百种植物,传播植物病毒病,是分布最广的蚜虫之一。","A photorealistic macro photograph of a Green Peach Aphid (Myzus persicae), small green and pink aphids on the underside of a peach leaf with dewdrops, National Geographic style."))
A(E("荔蝽","Lychee Giant Stink Bug","Tessaratoma papillosa","荔枝、龙眼果园","吸食果实和嫩梢汁液","体长约2.5厘米","1-2克",0.025,"无危(LC)","🪰","大型蝽象,体黄褐色,老熟若虫体色鲜艳,遇敌时喷射臭液,吸食荔枝、龙眼果实汁液,是华南地区重要的果树害虫。","A photorealistic macro photograph of a Lychee Giant Stink Bug (Tessaratoma papillosa), large brown stink bug with yellow markings, on a lychee fruit cluster, National Geographic style."))
A(E("麻皮蝽","Yellow-spotted Stink Bug","Erthesina fullo","城市绿化带及果园","吸食树木和果实汁液","体长约2厘米","0.5-1克",0.02,"无危(LC)","🪰","体灰褐色,背面有细密刻点,前胸背板有黄色细边,臭腺发达,受惊时散发臭味,取食多种树木和果树,常见于城市绿化带。","A photorealistic macro photograph of a Yellow-spotted Stink Bug (Erthesina fullo), gray-brown stink bug with dense punctures and a yellow lateral line, on a tree trunk, National Geographic style."))
A(E("水黾","Common Water Strider","Aquarius paludum","池塘、湖泊等静水水面","捕食落水的小型昆虫","体长约1.5厘米","0.1-0.2克",0.015,"无危(LC)","🪰","体细长,足极长,利用水的表面张力在水面滑行,如水上漂的精灵,捕食落水的昆虫,是池塘水面的常见居民,足部有拒水细毛。","A photorealistic macro photograph of a Common Water Strider (Aquarius paludum), slender water strider with long legs dimpling the water surface, skating across a pond with reflected sky, National Geographic style."))
A(E("大田鳖","Giant Water Bug","Kirkaldyia deyrolli","稻田、池塘等静水水域","捕食小鱼、蝌蚪等小型水生动物","体长约6厘米","3-6克",0.06,"近危(NT)","🪰","大型水生昆虫,体扁平暗褐色,前足镰刀状,捕食小鱼、蝌蚪等小型水生动物,雄虫背负卵块孵化,是水田中的顶级捕食者。","A photorealistic macro photograph of a Giant Water Bug (Kirkaldyia deyrolli), large flat brown water bug with raptorial front legs, male carrying eggs on its back, in shallow pond water, National Geographic style."))
A(E("日本蝎蝽","Water Scorpion","Laccotrephes japonensis","静水池塘及水沟","伏击捕食小型水生动物","体长约4厘米","1-2克",0.04,"无危(LC)","🪰","体暗褐色,前足镰刀状,尾部有细长呼吸管,形似蝎子,栖息于静水中,捕食小型水生动物,是池塘中的伏击猎手。","A photorealistic macro photograph of a Water Scorpion (Laccotrephes japonensis), dark brown water scorpion with pincer-like front legs and a long breathing tube, in still pond water among reeds, National Geographic style."))
A(E("斑衣蜡蝉","Spotted Lanternfly","Lycorma delicatula","臭椿、葡萄及果园","吸食树木汁液","体长约2厘米","0.3-0.6克",0.02,"无危(LC)","🪰","体灰褐色,后翅鲜红色带黑斑,飞行时红黑相间十分醒目,若虫体白色带黑点,群集吸食臭椿等树木汁液,是常见的观赏性害虫。","A photorealistic macro photograph of a Spotted Lanternfly (Lycorma delicatula), lanternfly with gray forewings and bright red hindwings with black spots, wings spread on a tree trunk, National Geographic style."))
A(E("沫蝉","Meadow Spittlebug","Philaenus spumarius","草地及农田","若虫吸食植物汁液","体长约0.6厘米","0.02-0.05克",0.006,"无危(LC)","🪰","体黄褐色,若虫分泌泡沫包裹身体躲避天敌,俗称吹泡虫,泡沫如唾沫挂在草茎上,成虫善于跳跃,取食多种草本植物汁液。","A photorealistic macro photograph of a Meadow Spittlebug (Philaenus spumarius), brown spittlebug nymph surrounded by white foam bubbles on a grass stem, National Geographic style."))
A(E("悬铃木方翅网蝽","Sycamore Lace Bug","Corythucha ciliata","城市悬铃木行道树","群集吸食叶背汁液","体长约0.3厘米","不足0.001克",0.003,"无危(LC)","🪰","体极小,翅透明呈网状花纹,群集于悬铃木叶背吸食汁液,造成叶片枯黄,是入侵性害虫,近年在我国城市迅速扩散。","A photorealistic macro photograph of a Sycamore Lace Bug (Corythucha ciliata), tiny lace bug with transparent netted wings, group on the underside of a plane tree leaf, National Geographic style."))

# ============ 直翅目 (12) ============
A(E("优雅蝈螽","Chinese Bush Cricket","Gampsocleis gratiosa","草丛、灌丛及农田","取食昆虫和植物嫩叶","体长约5厘米","2-4克",0.05,"无危(LC)","🦗","体翠绿色,翅短,雄虫翅摩擦发出响亮叫声,俗称蝈蝈,是深受喜爱的鸣虫,取食昆虫和植物嫩叶,笼养历史悠久。","A photorealistic macro photograph of a Chinese Bush Cricket (Gampsocleis gratiosa), bright green bush cricket with long antennae, singing on a vine leaf in morning light, National Geographic style."))
A(E("暗褐蝈螽","Sedakov's Bush Cricket","Gampsocleis sedakovii","北方草原及灌丛","取食植物叶片和小型昆虫","体长约4.5厘米","1.5-3克",0.045,"无危(LC)","🦗","体暗褐色或黄褐色,体型较大,栖息于草丛和灌丛,雄虫鸣声清脆,是北方常见的鸣虫,取食植物叶片和小型昆虫。","A photorealistic macro photograph of a Sedakov's Bush Cricket (Gampsocleis sedakovii), dark brown katydid with long antennae, perched on grass in a meadow, National Geographic style."))
A(E("纺织娘","Long-winged Katydid","Mecopoda elongata","草丛、瓜架及灌丛","取食植物叶片","体长约5厘米","2-4克",0.05,"无危(LC)","🦗","体绿色,翅极长超过腹部,鸣声如纺车转动,因而得名,夜间活动,栖息于草丛瓜架上,取食植物叶片,是著名的鸣虫。","A photorealistic macro photograph of a Long-winged Katydid (Mecopoda elongata), green katydid with very long wings, on a gourd vine at night, National Geographic style."))
A(E("黄脸油葫芦","Emma Field Cricket","Teleogryllus emma","田间、地头及墙缝","取食植物嫩芽和昆虫","体长约2厘米","0.3-0.6克",0.02,"无危(LC)","🦗","体黑褐色,头面部黄色,两雄相遇会激烈搏斗,鸣声油亮圆润,俗称油葫芦,是民间斗蟋的主要种类之一,常见于田间地头。","A photorealistic macro photograph of an Emma Field Cricket (Teleogryllus emma), dark brown field cricket with a yellow face, on soil near a field ridge, National Geographic style."))
A(E("棺头蟋","Doenitz's Ground Cricket","Loxoblemmus doenitzi","土缝、石块下及草丛","取食植物和昆虫尸体","体长约1.5厘米","0.2-0.4克",0.015,"无危(LC)","🦗","体黑褐色,雄虫头部向前突出如棺材状,因而得名,栖息于土缝和石块下,鸣声短促,是田间常见的蟋蟀种类。","A photorealistic macro photograph of a Doenitz's Ground Cricket (Loxoblemmus doenitzi), dark cricket with a flattened protruding head, under a stone at dusk, National Geographic style."))
A(E("金铃","Japanese Bell Cricket","Homoeogryllus japonicus","草丛及灌木丛","取食植物嫩叶","体长约1.5厘米","0.1-0.3克",0.015,"无危(LC)","🦗","小型蟋蟀,体色金黄,鸣声清脆悦耳如铃声,是鸣虫爱好者珍爱的品种,栖息于草丛,夜间鸣叫,体型小巧玲珑。","A photorealistic macro photograph of a Japanese Bell Cricket (Homoeogryllus japonicus), tiny golden bell cricket on a grass blade at night, National Geographic style."))
A(E("华北蝼蛄","Northern Mole Cricket","Gryllotalpa unispina","农田土壤及湿润地带","取食作物根系和种子","体长约4.5厘米","3-5克",0.045,"无危(LC)","🦗","体黄褐色,前足特化为开掘足如铲子,在地下挖掘隧道,取食作物根系和种子,是重要地下害虫,有趋光性,夜间飞出地面。","A photorealistic macro photograph of a Northern Mole Cricket (Gryllotalpa unispina), large yellowish-brown mole cricket with shovel-like front legs, on freshly dug soil, National Geographic style."))
A(E("中华蚱蜢","Oriental Long-headed Grasshopper","Acrida cinerea","田野、荒地及路边","取食禾本科植物叶片","体长约6厘米","2-4克",0.06,"无危(LC)","🦗","体绿色或黄褐色,头呈锥形向前突出,后足发达善跳,是田野最常见的蚱蜢,取食禾本科植物叶片,飞行时发出噼啪声。","A photorealistic macro photograph of an Oriental Long-headed Grasshopper (Acrida cinerea), green long-headed grasshopper with a cone-shaped head, on a rice paddy leaf, National Geographic style."))
A(E("短额负蝗","Chinese Atractomorpha","Atractomorpha sinensis","农田、荒地及菜园","取食多种植物叶片","体长约4厘米","1-2克",0.04,"无危(LC)","🦗","体绿色或褐色,头短,后足腿节粗壮,善于跳跃,常见于农田和荒地,取食多种植物叶片,是常见的杂食性蝗虫。","A photorealistic macro photograph of a Chinese Atractomorpha (Atractomorpha sinensis), green short-horned grasshopper with thick hind legs, on a weed in a field, National Geographic style."))
A(E("中华稻蝗","Chinese Rice Grasshopper","Oxya chinensis","水稻田及禾本科草丛","取食水稻等禾本科叶片","体长约3厘米","0.8-1.5克",0.03,"无危(LC)","🦗","体黄绿色带褐色条纹,是水稻的重要害虫,群集取食稻叶,分布广泛,是我国稻田中最常见的蝗虫种类之一。","A photorealistic macro photograph of a Chinese Rice Grasshopper (Oxya chinensis), yellow-green grasshopper with brown stripes, on a rice plant, National Geographic style."))
A(E("棉蝗","Rose-winged Grasshopper","Chondracris rosea","南方棉区及灌丛","取食棉花等作物叶片","体长约6厘米","3-6克",0.06,"无危(LC)","🦗","大型蝗虫,体黄绿色,后翅基部玫瑰红色,飞行时如红花飞舞,取食棉花等作物叶片,是南方棉区的重要害虫,体型硕大。","A photorealistic macro photograph of a Rose-winged Grasshopper (Chondracris rosea), large green grasshopper with rosy-red hindwings, wings spread in flight over a cotton field, National Geographic style."))
A(E("黄脊竹蝗","Yellow-spined Bamboo Locust","Ceracris kiangsu","竹林及山地草丛","取食竹叶","体长约4.5厘米","2-4克",0.045,"无危(LC)","🦗","体黄绿色,前胸背板中央有黄色纵脊,是竹林的重要害虫,大发生时成千上万取食竹叶,可造成竹林大片枯黄。","A photorealistic macro photograph of a Yellow-spined Bamboo Locust (Ceracris kiangsu), yellow-green bamboo locust with a yellow mid-dorsal ridge, on bamboo leaves, National Geographic style."))

# ============ 蜻蜓目 (6) ============
A(E("红蜻","Scarlet Skimmer","Crocothemis servilia","池塘、湖泊等水域","捕食蚊蝇等小型飞虫","体长约4厘米","0.5-1克",0.04,"无危(LC)","🪰","雄虫全身鲜红色,翅脉红色,雌虫黄褐色,是最常见的红色蜻蜓,常停栖在水边枯枝上,捕食蚊蝇等小型飞虫,是秋日水塘的标志。","A photorealistic macro photograph of a Scarlet Skimmer (Crocothemis servilia), bright scarlet dragonfly with red wing veins, perching on a withered twig by a pond, National Geographic style."))
A(E("黄蜻","Wandering Glider","Pantala flavescens","池塘、田野及开阔水域","捕食蚊蝇等小型飞虫","体长约4.5厘米","0.5-1克",0.045,"无危(LC)","🪰","体黄褐色,翅透明,是分布最广的蜻蜓,常成群长距离迁徙,飞行能力极强,被称为环球旅行家,捕食大量蚊蝇等害虫。","A photorealistic macro photograph of a Wandering Glider (Pantala flavescens), yellowish dragonfly with transparent wings, flying over a pond at sunset, National Geographic style."))
A(E("白尾灰蜻","White-tailed Skimmer","Orthetrum albistylum","池塘及溪流边","捕食小型飞虫","体长约5厘米","0.8-1.5克",0.05,"无危(LC)","🪰","体灰蓝色,腹部末端白色,常见于池塘和溪流边,雄虫领地意识强,在水面来回巡视,捕食小型飞虫,是常见蜻蜓种类。","A photorealistic macro photograph of a White-tailed Skimmer (Orthetrum albistylum), blue-gray skimmer dragonfly with a white-tipped abdomen, hovering above calm water, National Geographic style."))
A(E("黑纹伟蜓","Blue-eyed Darner","Anax nigrofasciatus","湖泊、池塘等开阔水域","捕食蚊蝇和蝴蝶等飞虫","体长约7厘米","1.5-3克",0.07,"无危(LC)","🪰","大型蜻蜓,胸部绿色,腹部黑色带蓝色斑纹,飞行迅捷,是水域上空的大型捕食者,捕食蚊蝇和蝴蝶等飞虫,飞行能力极强。","A photorealistic macro photograph of a Blue-eyed Darner (Anax nigrofasciatus), large dragonfly with a green thorax and black abdomen with blue spots, flying over a lake, National Geographic style."))
A(E("黑丽翅蜻","Dusky-winged Skimmer","Rhyothemis fuliginosa","池塘及湿地","捕食小型飞虫","体长约4厘米","0.5-1克",0.04,"无危(LC)","🪰","翅面黑色带蓝紫色金属光泽,飞行时如黑色绸缎飘舞,是蜻蜓中的黑色贵族,常停栖在水边,捕食小型飞虫,观赏价值高。","A photorealistic macro photograph of a Dusky-winged Skimmer (Rhyothemis fuliginosa), black dragonfly with blue-violet metallic sheen on the wings, perching on a lotus leaf, National Geographic style."))
A(E("白扇蟌","White-legged Damselfly","Platycnemis foliacea","溪流及池塘边","捕食小型飞虫","体长约4厘米","0.2-0.4克",0.04,"无危(LC)","🪰","豆娘的一种,体细长,足胫节白色扁平如扇,飞行轻盈,停栖时四翅合拢竖立,常见于溪流和池塘边,捕食小型飞虫。","A photorealistic macro photograph of a White-legged Damselfly (Platycnemis foliacea), slender damselfly with paddle-shaped white tibiae, perching on a waterside grass stem with wings closed, National Geographic style."))

# ============ 螳螂目 (4) ============
A(E("兰花螳螂","Orchid Mantis","Hymenopus coronatus","东南亚热带雨林及花丛","伏击捕食传粉昆虫","体长约6厘米","2-4克",0.06,"未评估(NE)","🦗","世界最美丽的螳螂,体色粉白如兰花花瓣,腿部有花瓣状扩展,伪装成兰花伏击传粉昆虫,是昆虫界的顶级伪装大师。","A photorealistic macro photograph of an Orchid Mantis (Hymenopus coronatus), pink and white mantis with petal-like leg lobes, sitting on an orchid flower, National Geographic style."))
A(E("魔花螳螂","Devil's Flower Mantis","Idolomantis diabolica","东非干旱灌丛","伏击捕食小型昆虫","体长约9厘米","5-8克",0.09,"未评估(NE)","🦗","非洲大型螳螂,体色艳丽,前足内侧有复杂花纹,静止时如花朵,受惊时展开前足恐吓敌人,是螳螂中的王者,观赏价值极高。","A photorealistic macro photograph of a Devil's Flower Mantis (Idolomantis diabolica), large colorful mantis with intricate patterns on the raptorial forelegs, displaying a threat posture on a dry branch, National Geographic style."))
A(E("枯叶螳螂","Dead Leaf Mantis","Deroplatys desiccata","东南亚热带雨林落叶层","伏击捕食小型昆虫","体长约7厘米","3-6克",0.07,"未评估(NE)","🦗","体褐色,前翅纹理如枯叶,静止时与落叶融为一体,是拟态大师,埋伏于落叶中捕食经过的小型昆虫,伪装天衣无缝。","A photorealistic macro photograph of a Dead Leaf Mantis (Deroplatys desiccata), brown mantis with dead-leaf patterned wings, motionless among fallen leaves, National Geographic style."))
A(E("欧洲螳螂","European Mantis","Mantis religiosa","草地、灌丛及花园","捕食小型昆虫","体长约7厘米","3-6克",0.07,"无危(LC)","🦗","体绿色或褐色,前足镰刀状,是欧洲最常见的螳螂,雌虫交配后常吃掉雄虫,以小型昆虫为食,是著名的捕食性昆虫。","A photorealistic macro photograph of a European Mantis (Mantis religiosa), green praying mantis with folded raptorial forelegs, on a garden hedge, National Geographic style."))

# ============ 竹节虫目 (3) ============
A(E("印度竹节虫","Indian Stick Insect","Carausius morosus","灌丛及园林植物","取食植物叶片","体长约9厘米","2-4克",0.09,"无危(LC)","🐛","体细长如竹枝,绿色或褐色,静止时极似植物枝条,以植物叶片为食,善于拟态,饲养容易,是昆虫爱好者常养的宠物。","A photorealistic macro photograph of an Indian Stick Insect (Carausius morosus), slender green stick insect resembling a twig, resting motionless on a plant stem, National Geographic style."))
A(E("叶䗛","Leaf Insect","Phyllium siccifolium","东南亚热带雨林","取食植物叶片","体长约6厘米","3-6克",0.06,"未评估(NE)","🐛","体形酷似树叶,翅上有叶脉状纹理和枯斑,静止时与绿叶或枯叶难分彼此,是拟态昆虫的极致代表,栖息于热带雨林。","A photorealistic macro photograph of a Leaf Insect (Phyllium siccifolium), insect with a body shaped like a green leaf with veins and edge damage, on a rainforest branch, National Geographic style."))
A(E("查尼巨竹节虫","Chan's Megastick","Phobaeticus chani","马来西亚热带雨林","取食植物叶片","体长可达56厘米","30-60克",0.5,"未评估(NE)","🐛","世界上最长的昆虫,体长可达56厘米,细如竹枝,发现于马来西亚雨林,以植物叶片为食,是昆虫纲长度的纪录保持者。","A photorealistic macro photograph of a Chan's Megastick (Phobaeticus chani), extremely long slender stick insect, the longest insect in the world, on a rainforest vine, National Geographic style."))

# ============ 脉翅目 (3) ============
A(E("日本螳蛉","Japanese Mantidfly","Mantispa japonica","林缘及草丛","幼虫寄生于蜘蛛卵囊,成虫捕食小虫","体长约2厘米","0.1-0.2克",0.02,"未评估(NE)","🪰","外形介于螳螂和草蛉之间,前足捕捉足如螳螂,翅透明如脉翅目,幼虫寄生于蜘蛛卵囊,是形态独特的小型捕食者。","A photorealistic macro photograph of a Japanese Mantidfly (Mantispa japonica), small mantidfly with raptorial forelegs and delicate netted wings, on a leaf, National Geographic style."))
A(E("中华东蚁蛉","Chinese Antlion","Euroleon sinicus","沙地、林缘及屋檐下","幼虫捕食蚂蚁等小虫,成虫捕食飞虫","体长约3厘米","0.3-0.5克",0.03,"无危(LC)","🪰","外形似蜻蜓,触角棍棒状,幼虫俗称蚁狮,在沙地挖漏斗状陷阱捕食蚂蚁等小虫,成虫黄昏活动,捕食小型飞虫。","A photorealistic macro photograph of a Chinese Antlion (Euroleon sinicus), antlion adult resembling a damselfly with clubbed antennae, resting on a twig at dusk, National Geographic style."))
A(E("大草蛉","Golden-eyed Lacewing","Chrysopa pallens","农田、果园及林缘","幼虫捕食蚜虫等害虫","体长约1.5厘米","0.1-0.2克",0.015,"无危(LC)","🪰","体绿色,复眼金色,翅脉如网状,幼虫俗称蚜狮,捕食蚜虫等软体害虫,是农田重要天敌,成虫趋光,卵有长柄悬挂叶面。","A photorealistic macro photograph of a Golden-eyed Lacewing (Chrysopa pallens), green lacewing with golden eyes and delicate netted wings, on a wheat stalk with eggs on thin stalks nearby, National Geographic style."))

# ============ 广翅目 (2) ============
A(E("东方巨齿蛉","Oriental Dobsonfly","Acanthacorydalis orientalis","山溪及林间水域","幼虫捕食小型水生动物,成虫取食树液","体长约10厘米(含上颚)","10-20克",0.1,"未评估(NE)","🪰","广翅目巨虫,雄虫上颚长达体长一半,形如獠牙,雄虫虽凶猛却不咬人,幼虫水生,是山溪水质优良的指示生物。","A photorealistic macro photograph of an Oriental Dobsonfly (Acanthacorydalis orientalis), giant dobsonfly with enormous curved mandibles, resting on a riverside rock, National Geographic style."))
A(E("中华斑鱼蛉","Chinese Fishfly","Neochauliodes sinensis","溪流附近及林间","幼虫捕食小型水生动物,成虫夜间活动","体长约4厘米","1-2克",0.04,"未评估(NE)","🪰","体黄褐色,翅面有褐色斑纹,触角丝状,栖息于溪流附近,幼虫水生捕食小型水生动物,成虫夜间活动,外形似蛇蛉。","A photorealistic macro photograph of a Chinese Fishfly (Neochauliodes sinensis), yellowish fishfly with brown mottled wings, on a streamside leaf, National Geographic style."))

# ============ 毛翅目 (1) ============
A(E("石蛾","Caddisfly","Hydropsyche pellucidula","溪流、池塘及河边草丛","幼虫取食水底有机物,成虫取食花蜜","体长约1.5厘米","0.1-0.2克",0.015,"无危(LC)","🪰","外形似蛾,翅面密布细毛,触角长,幼虫在水底用砂石、枯枝筑巢藏身,是水质监测的重要指示生物,成虫多夜间活动。","A photorealistic macro photograph of a Caddisfly (Hydropsyche pellucidula), moth-like insect with hairy brown wings and long antennae, near a stream with a larva case made of pebbles, National Geographic style."))

# ============ 蜉蝣目 (1) ============
A(E("蜉蝣","Mayfly","Ephemera danica","溪流、湖泊等水域","幼虫取食水底藻类,成虫不取食","体长约2厘米","0.1-0.2克",0.02,"无危(LC)","🪰","体细弱,翅薄而透明,尾须细长,幼虫在水中生活数年,羽化后成虫仅存活数小时至数天,朝生暮死,是古老的昆虫类群。","A photorealistic macro photograph of a Mayfly (Ephemera danica), delicate insect with translucent wings and long tail filaments, resting on a reed by the water at dawn, National Geographic style."))

# ============ 蛇蛉目 (1) ============
A(E("蛇蛉","Snakefly","Raphidia ophiopsis","林地树皮下及草丛","幼虫捕食树皮下小虫,成虫捕食小虫","体长约1.5厘米","0.1-0.2克",0.015,"无危(LC)","🪰","头胸部细长如蛇颈,前胸可活动,翅长而窄,雌虫产卵器细长,幼虫生活在树皮下捕食小虫,是形态奇特的小型捕食者。","A photorealistic macro photograph of a Snakefly (Raphidia ophiopsis), insect with an elongated neck-like prothorax and narrow wings, on tree bark, National Geographic style."))

# ============ 捻翅目 (1) ============
A(E("捻翅虫","Twisted-wing Parasite","Xenos vesparum","蜂类巢穴附近","雄虫不取食,雌虫终生寄生蜂类体内","体长约0.4厘米","不足0.01克",0.004,"未评估(NE)","🪰","雄虫有翅善飞,雌虫终生寄生在蜂类体内,仅头部露出寄主体表,是昆虫中最奇特的寄生者,雄虫触角呈扇状十分特别。","A photorealistic macro photograph of a Twisted-wing Parasite (Xenos vesparum), tiny male twisted-wing parasite with fan-shaped antennae and reduced forewings, on a leaf, National Geographic style."))

# ============ 弹尾目 (1) ============
A(E("白符跳","White Springtail","Folsomia candida","落叶层及土壤中","取食真菌和腐殖质","体长约0.3厘米","不足0.01克",0.003,"无危(LC)","🐛","体小,白色,腹部末端有弹跳器,受惊时能弹跳数十倍体长,生活在落叶层和土壤中,取食真菌和腐殖质,是土壤健康指示生物。","A photorealistic macro photograph of a White Springtail (Folsomia candida), tiny white springtail with a furcula, on dark forest soil among leaf litter, extreme close-up, National Geographic style."))

# ============ 蜚蠊目 (5) ============
A(E("美洲大蠊","American Cockroach","Periplaneta americana","温暖潮湿的室内及下水道","杂食性,取食各种有机物","体长约4厘米","1-2克",0.04,"无危(LC)","🪳","大型蟑螂,体红褐色,前胸背板有黑褐色斑纹,原产热带美洲,现广布全球,喜温暖潮湿环境,是城市中常见的卫生害虫。","A photorealistic macro photograph of an American Cockroach (Periplaneta americana), large reddish-brown cockroach with a pale band on the pronotum, in a warm damp basement corner, National Geographic style."))
A(E("德国小蠊","German Cockroach","Blattella germanica","厨房、餐馆等室内环境","杂食性,取食各种食物残渣","体长约1.3厘米","0.1-0.2克",0.013,"无危(LC)","🪳","小型蟑螂,体浅褐色,前胸背板有两条黑色纵纹,繁殖极快,是厨房和餐馆最常见的蟑螂,抗药性强,治理难度大。","A photorealistic macro photograph of a German Cockroach (Blattella germanica), small light brown cockroach with two dark stripes on the pronotum, near a kitchen crack, National Geographic style."))
A(E("中华真地鳖","Chinese Ground Cockroach","Eupolyphaga sinensis","阴暗潮湿的墙角及土缝","取食植物残体和腐殖质","体长约3.5厘米","2-4克",0.035,"无危(LC)","🪳","体椭圆形,黑褐色,雌虫无翅,雄虫有翅,栖息于阴暗潮湿的墙角土缝,是传统中药材土鳖虫,人工养殖历史悠久。","A photorealistic macro photograph of a Chinese Ground Cockroach (Eupolyphaga sinensis), oval dark brown wingless female, in a dark damp corner under a brick, National Geographic style."))
A(E("台湾乳白蚁","Formosan Subterranean Termite","Coptotermes formosanus","房屋木构件及地下","取食木材和植物纤维","兵蚁体长约0.6厘米","不足0.01克",0.006,"无危(LC)","🪳","白蚁的一种,工蚁乳白色,兵蚁头部有分泌乳汁状液体的额腺,能在地下修筑庞大蚁道,蛀食房屋木构件,是危害极大的建筑害虫。","A photorealistic macro photograph of a Formosan Subterranean Termite (Coptotermes formosanus), pale cream termite soldiers and workers inside a wooden structure tunnel, National Geographic style."))
A(E("黑翅土白蚁","Black-winged Subterranean Termite","Odontotermes formosanus","林地、农田及堤坝","取食树木和农作物","有翅蚁体长约1厘米","0.02-0.05克",0.01,"无危(LC)","🪳","有翅繁殖蚁翅黑色,工蚁在地下筑巢,取食树木和农作物,菌圃中培养真菌,是南方农林的重要害虫,能蛀蚀堤坝造成隐患。","A photorealistic macro photograph of a Black-winged Subterranean Termite (Odontotermes formosanus), black-winged termite alates and pale workers on a soil mound, National Geographic style."))

# ============ 缨翅目 (1) ============
A(E("烟蓟马","Onion Thrips","Thrips tabaci","葱蒜田及农作物上","锉吸植物汁液","体长约0.1厘米","不足0.001克",0.001,"无危(LC)","🪰","体极小,细长,翅缘有长缨毛,锉吸式口器刮吸植物汁液,是葱蒜等作物的重要害虫,也能传播植物病毒,田间发生隐蔽。","A photorealistic macro photograph of an Onion Thrips (Thrips tabaci), tiny slender thrips with fringed wings, on an onion leaf, extreme close-up, National Geographic style."))

# ---------- 校验 ----------
def check():
    errs = []
    names = [x['name'] for x in D]
    scis = [x['scientificName'] for x in D]
    if len(D) != 120: errs.append("数量=%d(应为120)" % len(D))
    dup_name = [n for n in set(names) if names.count(n) > 1]
    dup_sci = [s for s in set(scis) if scis.count(s) > 1]
    if dup_name: errs.append("重复中文名:" + str(dup_name))
    if dup_sci: errs.append("重复学名:" + str(dup_sci))
    forbid = {"中华蜜蜂","帝王蝶","枯叶蝶","柑橘凤蝶","乌桕大蚕蛾","独角仙","锹甲","萤火虫","中华大刀螳","碧伟蜓","黑蚱蝉","斗蟋","东亚飞蝗","日本弓背蚁","七星瓢虫","竹节虫","吉丁虫","家蚕"}
    hit = [n for n in names if n in forbid]
    if hit: errs.append("与已有昆虫重复:" + str(hit))
    for i, e in enumerate(D):
        if not (40 <= len(e['description']) <= 80): errs.append("[%d]%s 描述字数=%d" % (i+1, e['name'], len(e['description'])))
        p = e['imagePrompt']
        if not (p.startswith("A photorealistic macro photograph of a ") or p.startswith("A photorealistic macro photograph of an ")): errs.append("[%d]%s 提示词开头错误" % (i+1, e['name']))
        if not p.endswith("National Geographic style."): errs.append("[%d]%s 提示词结尾错误" % (i+1, e['name']))
        if 'blood' in p.lower() or 'Blood' in p: errs.append("[%d]%s 提示词含敏感词" % (i+1, e['name']))
        if e['category'] != "昆虫类": errs.append("[%d]%s category错误" % (i+1, e['name']))
        if not re.match(r'^[A-Z][a-z]+ [a-z]+$', e['scientificName']): errs.append("[%d]%s 学名格式可疑:%s" % (i+1, e['name'], e['scientificName']))
    return errs

# ---------- 打印计划清单 ----------
print("=" * 70)
print("计划清单(共%d种):序号. 中文名 拉丁学名 (英文名)" % len(D))
print("=" * 70)
for i, e in enumerate(D, 1):
    print("%3d. %s  %s  (%s)" % (i, e['name'], e['scientificName'], e['englishName']))

errs = check()
print("-" * 70)
if errs:
    print("!! 校验发现 %d 个问题:" % len(errs))
    for x in errs: print("  - " + x)
    sys.exit(1)
print("校验通过:120种,无重复,描述40-80字,提示词格式正确,无敏感词。")

# ---------- 写文件 ----------
out = r"C:/Users/Administrator/Desktop/animal-world-mini-program/data_batches/new_insects.json"
with open(out, "w", encoding="utf-8") as f:
    json.dump(D, f, ensure_ascii=False, indent=1)
size = os.path.getsize(out)
print("写入了%d条 -> %s" % (len(D), out))
print("文件大小: %.2f KB (%d 字节)" % (size / 1024.0, size))
